-- Topic 15: Food & Cuisine - Add 50 questions (food_151 to food_200)
INSERT INTO questions (id, question, answers, audience, third, source_category, topic_id) VALUES
('food_151', 'Melyik országból származik a sushi?', '[{"key":"A","text":"Japán","correct":true},{"key":"B","text":"Kína","correct":false},{"key":"C","text":"Thaiföld","correct":false}]', '[70,15,15]', 'A', 'mixed', 15),
('food_152', 'Mi a fő összetevője a guacamolének?', '[{"key":"A","text":"Paradicsom","correct":false},{"key":"B","text":"Avokádó","correct":true},{"key":"C","text":"Uborka","correct":false}]', '[20,65,15]', 'B', 'mixed', 15),
('food_153', 'Melyik országból származik a paella?', '[{"key":"A","text":"Olaszország","correct":false},{"key":"B","text":"Spanyolország","correct":true},{"key":"C","text":"Portugália","correct":false}]', '[20,60,20]', 'B', 'mixed', 15),
('food_154', 'Mi a wasabi növény valódi színe?', '[{"key":"A","text":"Zöld","correct":true},{"key":"B","text":"Fehér","correct":false},{"key":"C","text":"Sárga","correct":false}]', '[60,20,20]', 'A', 'mixed', 15),
('food_155', 'Melyik országból származik a tiramisu?', '[{"key":"A","text":"Franciaország","correct":false},{"key":"B","text":"Olaszország","correct":true},{"key":"C","text":"Ausztria","correct":false}]', '[20,65,15]', 'B', 'mixed', 15),
('food_156', 'Mi a főzés alapja a ramen levesnek?', '[{"key":"A","text":"Csontlé","correct":true},{"key":"B","text":"Zöldséglé","correct":false},{"key":"C","text":"Halászlé","correct":false}]', '[55,25,20]', 'A', 'mixed', 15),
('food_157', 'Melyik étel a nemzeti étele Mexikónak?', '[{"key":"A","text":"Taco","correct":true},{"key":"B","text":"Burrito","correct":false},{"key":"C","text":"Quesadilla","correct":false}]', '[55,25,20]', 'A', 'mixed', 15),
('food_158', 'Mi a szarvasgomba?', '[{"key":"A","text":"Gomba","correct":true},{"key":"B","text":"Gyökérzöldség","correct":false},{"key":"C","text":"Fűszer","correct":false}]', '[60,20,20]', 'A', 'mixed', 15),
('food_159', 'Melyik országból származik a croissant?', '[{"key":"A","text":"Franciaország","correct":false},{"key":"B","text":"Ausztria","correct":true},{"key":"C","text":"Belgium","correct":false}]', '[35,45,20]', 'B', 'mixed', 15),
('food_160', 'Mi a tofu fő alapanyaga?', '[{"key":"A","text":"Szójabab","correct":true},{"key":"B","text":"Rizs","correct":false},{"key":"C","text":"Búza","correct":false}]', '[60,20,20]', 'A', 'mixed', 15),
('food_161', 'Melyik fűszernövény adja a pesto zöld színét?', '[{"key":"A","text":"Petrezselyem","correct":false},{"key":"B","text":"Bazsalikom","correct":true},{"key":"C","text":"Oregánó","correct":false}]', '[25,55,20]', 'B', 'mixed', 15),
('food_162', 'Mi a fő összetevője a humusznak?', '[{"key":"A","text":"Csicseriborsó","correct":true},{"key":"B","text":"Lencse","correct":false},{"key":"C","text":"Bab","correct":false}]', '[60,20,20]', 'A', 'mixed', 15),
('food_163', 'Melyik ország híres a fondue-ről?', '[{"key":"A","text":"Svájc","correct":true},{"key":"B","text":"Belgium","correct":false},{"key":"C","text":"Hollandia","correct":false}]', '[60,20,20]', 'A', 'mixed', 15),
('food_164', 'Mi a sáfrány?', '[{"key":"A","text":"Fűszer","correct":true},{"key":"B","text":"Zöldség","correct":false},{"key":"C","text":"Gyümölcs","correct":false}]', '[65,20,15]', 'A', 'mixed', 15),
('food_165', 'Melyik országból származik a kimchi?', '[{"key":"A","text":"Japán","correct":false},{"key":"B","text":"Dél-Korea","correct":true},{"key":"C","text":"Kína","correct":false}]', '[20,60,20]', 'B', 'mixed', 15),
('food_166', 'Mi a risotto rizsfajtája?', '[{"key":"A","text":"Arborio","correct":true},{"key":"B","text":"Basmati","correct":false},{"key":"C","text":"Jázmin","correct":false}]', '[55,25,20]', 'A', 'mixed', 15),
('food_167', 'Melyik ország híres a waffle-ről?', '[{"key":"A","text":"Hollandia","correct":false},{"key":"B","text":"Belgium","correct":true},{"key":"C","text":"Németország","correct":false}]', '[25,55,20]', 'B', 'mixed', 15),
('food_168', 'Mi a tahini fő összetevője?', '[{"key":"A","text":"Szezámmag","correct":true},{"key":"B","text":"Mogyoró","correct":false},{"key":"C","text":"Mandula","correct":false}]', '[55,25,20]', 'A', 'mixed', 15),
('food_169', 'Melyik országból származik a pad thai?', '[{"key":"A","text":"Vietnam","correct":false},{"key":"B","text":"Thaiföld","correct":true},{"key":"C","text":"Indonézia","correct":false}]', '[20,60,20]', 'B', 'mixed', 15),
('food_170', 'Mi a miso leves fő íze?', '[{"key":"A","text":"Umami","correct":true},{"key":"B","text":"Édes","correct":false},{"key":"C","text":"Savanyú","correct":false}]', '[55,25,20]', 'A', 'mixed', 15),
('food_171', 'Melyik országból származik a goulash?', '[{"key":"A","text":"Magyarország","correct":true},{"key":"B","text":"Ausztria","correct":false},{"key":"C","text":"Csehország","correct":false}]', '[65,20,15]', 'A', 'mixed', 15),
('food_172', 'Mi a főzési módja a ceviche-nek?', '[{"key":"A","text":"Citromlével főzve","correct":true},{"key":"B","text":"Grillezve","correct":false},{"key":"C","text":"Sütőben sütve","correct":false}]', '[55,25,20]', 'A', 'mixed', 15),
('food_173', 'Melyik ország híres a sörfőzési hagyományairól?', '[{"key":"A","text":"Németország","correct":true},{"key":"B","text":"Franciaország","correct":false},{"key":"C","text":"Olaszország","correct":false}]', '[60,20,20]', 'A', 'mixed', 15),
('food_174', 'Mi a paneer?', '[{"key":"A","text":"Indiai sajt","correct":true},{"key":"B","text":"Fűszer","correct":false},{"key":"C","text":"Kenyér","correct":false}]', '[55,25,20]', 'A', 'mixed', 15),
('food_175', 'Melyik országból származik a falafel?', '[{"key":"A","text":"Izrael/Közel-Kelet","correct":true},{"key":"B","text":"India","correct":false},{"key":"C","text":"Törökország","correct":false}]', '[55,25,20]', 'A', 'mixed', 15),
('food_176', 'Mi a baklava fő összetevője?', '[{"key":"A","text":"Filotészta","correct":true},{"key":"B","text":"Leveles tészta","correct":false},{"key":"C","text":"Rizsliszt","correct":false}]', '[55,25,20]', 'A', 'mixed', 15),
('food_177', 'Melyik ország híres a curry-ről?', '[{"key":"A","text":"India","correct":true},{"key":"B","text":"Thaiföld","correct":false},{"key":"C","text":"Malajzia","correct":false}]', '[60,20,20]', 'A', 'mixed', 15),
('food_178', 'Mi a mascarpone?', '[{"key":"A","text":"Olasz krémsajt","correct":true},{"key":"B","text":"Francia sajt","correct":false},{"key":"C","text":"Görög joghurt","correct":false}]', '[60,20,20]', 'A', 'mixed', 15),
('food_179', 'Melyik országból származik a börök (börek)?', '[{"key":"A","text":"Görögország","correct":false},{"key":"B","text":"Törökország","correct":true},{"key":"C","text":"Libanon","correct":false}]', '[25,55,20]', 'B', 'mixed', 15),
('food_180', 'Mi a ponzu szósz alapja?', '[{"key":"A","text":"Citrus","correct":true},{"key":"B","text":"Ecet","correct":false},{"key":"C","text":"Méz","correct":false}]', '[55,25,20]', 'A', 'mixed', 15),
('food_181', 'Melyik országból származik a cous-cous?', '[{"key":"A","text":"Észak-Afrika","correct":true},{"key":"B","text":"Dél-Amerika","correct":false},{"key":"C","text":"Közép-Ázsia","correct":false}]', '[55,25,20]', 'A', 'mixed', 15),
('food_182', 'Mi a tempeh?', '[{"key":"A","text":"Fermentált szójabab","correct":true},{"key":"B","text":"Rizstészta","correct":false},{"key":"C","text":"Fűszerezett hús","correct":false}]', '[50,25,25]', 'A', 'mixed', 15),
('food_183', 'Melyik országból származik a pierogi?', '[{"key":"A","text":"Lengyelország","correct":true},{"key":"B","text":"Ukrajna","correct":false},{"key":"C","text":"Oroszország","correct":false}]', '[55,25,20]', 'A', 'mixed', 15),
('food_184', 'Mi a ghee?', '[{"key":"A","text":"Tisztított vaj","correct":true},{"key":"B","text":"Olaj","correct":false},{"key":"C","text":"Zsír","correct":false}]', '[55,25,20]', 'A', 'mixed', 15),
('food_185', 'Melyik országból származik a pho leves?', '[{"key":"A","text":"Thaiföld","correct":false},{"key":"B","text":"Vietnam","correct":true},{"key":"C","text":"Kambodzsa","correct":false}]', '[25,55,20]', 'B', 'mixed', 15),
('food_186', 'Mi a sriracha?', '[{"key":"A","text":"Csípős szósz","correct":true},{"key":"B","text":"Édes szósz","correct":false},{"key":"C","text":"Savanyú szósz","correct":false}]', '[60,20,20]', 'A', 'mixed', 15),
('food_187', 'Melyik országból származik a tzatziki?', '[{"key":"A","text":"Törökország","correct":false},{"key":"B","text":"Görögország","correct":true},{"key":"C","text":"Libanon","correct":false}]', '[25,55,20]', 'B', 'mixed', 15),
('food_188', 'Mi a mirin?', '[{"key":"A","text":"Japán rizsbor","correct":true},{"key":"B","text":"Kínai ecet","correct":false},{"key":"C","text":"Koreai szósz","correct":false}]', '[55,25,20]', 'A', 'mixed', 15),
('food_189', 'Melyik országból származik a churros?', '[{"key":"A","text":"Mexikó","correct":false},{"key":"B","text":"Spanyolország","correct":true},{"key":"C","text":"Portugália","correct":false}]', '[25,55,20]', 'B', 'mixed', 15),
('food_190', 'Mi a dashi?', '[{"key":"A","text":"Japán alaplé","correct":true},{"key":"B","text":"Kínai fűszer","correct":false},{"key":"C","text":"Koreai tészta","correct":false}]', '[55,25,20]', 'A', 'mixed', 15),
('food_191', 'Melyik országból származik a moussaka?', '[{"key":"A","text":"Görögország","correct":true},{"key":"B","text":"Törökország","correct":false},{"key":"C","text":"Libanon","correct":false}]', '[55,25,20]', 'A', 'mixed', 15),
('food_192', 'Mi a nori?', '[{"key":"A","text":"Tengeri alga","correct":true},{"key":"B","text":"Fűszer","correct":false},{"key":"C","text":"Rizsfajta","correct":false}]', '[60,20,20]', 'A', 'mixed', 15),
('food_193', 'Melyik országból származik a borscs leves?', '[{"key":"A","text":"Oroszország/Ukrajna","correct":true},{"key":"B","text":"Lengyelország","correct":false},{"key":"C","text":"Románia","correct":false}]', '[55,25,20]', 'A', 'mixed', 15),
('food_194', 'Mi a garam masala?', '[{"key":"A","text":"Indiai fűszerkeverék","correct":true},{"key":"B","text":"Curry típus","correct":false},{"key":"C","text":"Szósz","correct":false}]', '[55,25,20]', 'A', 'mixed', 15),
('food_195', 'Melyik országból származik a dim sum?', '[{"key":"A","text":"Japán","correct":false},{"key":"B","text":"Kína","correct":true},{"key":"C","text":"Vietnam","correct":false}]', '[20,60,20]', 'B', 'mixed', 15),
('food_196', 'Mi a harissa?', '[{"key":"A","text":"Észak-afrikai fűszerpaszta","correct":true},{"key":"B","text":"Görög szósz","correct":false},{"key":"C","text":"Indiai fűszer","correct":false}]', '[50,25,25]', 'A', 'mixed', 15),
('food_197', 'Melyik országból származik a ceviche?', '[{"key":"A","text":"Mexikó","correct":false},{"key":"B","text":"Peru","correct":true},{"key":"C","text":"Chile","correct":false}]', '[25,55,20]', 'B', 'mixed', 15),
('food_198', 'Mi a bonito?', '[{"key":"A","text":"Tonhalfajta","correct":true},{"key":"B","text":"Fűszer","correct":false},{"key":"C","text":"Zöldség","correct":false}]', '[55,25,20]', 'A', 'mixed', 15),
('food_199', 'Melyik országból származik a naan kenyér?', '[{"key":"A","text":"India","correct":true},{"key":"B","text":"Törökország","correct":false},{"key":"C","text":"Irán","correct":false}]', '[60,20,20]', 'A', 'mixed', 15),
('food_200', 'Mi a galangal?', '[{"key":"A","text":"Gyömbérféle","correct":true},{"key":"B","text":"Paprikafajta","correct":false},{"key":"C","text":"Citrusfélék","correct":false}]', '[50,25,25]', 'A', 'mixed', 15);

-- English translations for Topic 15
INSERT INTO question_translations (question_id, lang, question_text, answer_a, answer_b, answer_c) VALUES
('food_151', 'en', 'Which country does sushi originate from?', 'Japan', 'China', 'Thailand'),
('food_152', 'en', 'What is the main ingredient in guacamole?', 'Tomato', 'Avocado', 'Cucumber'),
('food_153', 'en', 'Which country does paella come from?', 'Italy', 'Spain', 'Portugal'),
('food_154', 'en', 'What is the real color of the wasabi plant?', 'Green', 'White', 'Yellow'),
('food_155', 'en', 'Which country does tiramisu come from?', 'France', 'Italy', 'Austria'),
('food_156', 'en', 'What is the base for ramen soup?', 'Bone broth', 'Vegetable broth', 'Fish broth'),
('food_157', 'en', 'What is the national dish of Mexico?', 'Taco', 'Burrito', 'Quesadilla'),
('food_158', 'en', 'What is a truffle?', 'Mushroom', 'Root vegetable', 'Spice'),
('food_159', 'en', 'Which country does the croissant originate from?', 'France', 'Austria', 'Belgium'),
('food_160', 'en', 'What is the main ingredient in tofu?', 'Soybeans', 'Rice', 'Wheat'),
('food_161', 'en', 'Which herb gives pesto its green color?', 'Parsley', 'Basil', 'Oregano'),
('food_162', 'en', 'What is the main ingredient in hummus?', 'Chickpeas', 'Lentils', 'Beans'),
('food_163', 'en', 'Which country is famous for fondue?', 'Switzerland', 'Belgium', 'Netherlands'),
('food_164', 'en', 'What is saffron?', 'Spice', 'Vegetable', 'Fruit'),
('food_165', 'en', 'Which country does kimchi come from?', 'Japan', 'South Korea', 'China'),
('food_166', 'en', 'What type of rice is used in risotto?', 'Arborio', 'Basmati', 'Jasmine'),
('food_167', 'en', 'Which country is famous for waffles?', 'Netherlands', 'Belgium', 'Germany'),
('food_168', 'en', 'What is the main ingredient in tahini?', 'Sesame seeds', 'Peanuts', 'Almonds'),
('food_169', 'en', 'Which country does pad thai come from?', 'Vietnam', 'Thailand', 'Indonesia'),
('food_170', 'en', 'What is the main flavor of miso soup?', 'Umami', 'Sweet', 'Sour'),
('food_171', 'en', 'Which country does goulash come from?', 'Hungary', 'Austria', 'Czech Republic'),
('food_172', 'en', 'What is the cooking method for ceviche?', 'Cooked in citrus juice', 'Grilled', 'Baked in oven'),
('food_173', 'en', 'Which country is famous for brewing traditions?', 'Germany', 'France', 'Italy'),
('food_174', 'en', 'What is paneer?', 'Indian cheese', 'Spice', 'Bread'),
('food_175', 'en', 'Which region does falafel come from?', 'Israel/Middle East', 'India', 'Turkey'),
('food_176', 'en', 'What is the main component of baklava?', 'Phyllo dough', 'Puff pastry', 'Rice flour'),
('food_177', 'en', 'Which country is famous for curry?', 'India', 'Thailand', 'Malaysia'),
('food_178', 'en', 'What is mascarpone?', 'Italian cream cheese', 'French cheese', 'Greek yogurt'),
('food_179', 'en', 'Which country does börek come from?', 'Greece', 'Turkey', 'Lebanon'),
('food_180', 'en', 'What is the base of ponzu sauce?', 'Citrus', 'Vinegar', 'Honey'),
('food_181', 'en', 'Which region does couscous come from?', 'North Africa', 'South America', 'Central Asia'),
('food_182', 'en', 'What is tempeh?', 'Fermented soybeans', 'Rice noodles', 'Spiced meat'),
('food_183', 'en', 'Which country does pierogi come from?', 'Poland', 'Ukraine', 'Russia'),
('food_184', 'en', 'What is ghee?', 'Clarified butter', 'Oil', 'Fat'),
('food_185', 'en', 'Which country does pho soup come from?', 'Thailand', 'Vietnam', 'Cambodia'),
('food_186', 'en', 'What is sriracha?', 'Hot sauce', 'Sweet sauce', 'Sour sauce'),
('food_187', 'en', 'Which country does tzatziki come from?', 'Turkey', 'Greece', 'Lebanon'),
('food_188', 'en', 'What is mirin?', 'Japanese rice wine', 'Chinese vinegar', 'Korean sauce'),
('food_189', 'en', 'Which country does churros come from?', 'Mexico', 'Spain', 'Portugal'),
('food_190', 'en', 'What is dashi?', 'Japanese stock', 'Chinese spice', 'Korean noodle'),
('food_191', 'en', 'Which country does moussaka come from?', 'Greece', 'Turkey', 'Lebanon'),
('food_192', 'en', 'What is nori?', 'Seaweed', 'Spice', 'Rice variety'),
('food_193', 'en', 'Which country does borscht soup come from?', 'Russia/Ukraine', 'Poland', 'Romania'),
('food_194', 'en', 'What is garam masala?', 'Indian spice mix', 'Type of curry', 'Sauce'),
('food_195', 'en', 'Which country does dim sum come from?', 'Japan', 'China', 'Vietnam'),
('food_196', 'en', 'What is harissa?', 'North African spice paste', 'Greek sauce', 'Indian spice'),
('food_197', 'en', 'Which country does ceviche come from?', 'Mexico', 'Peru', 'Chile'),
('food_198', 'en', 'What is bonito?', 'Type of tuna', 'Spice', 'Vegetable'),
('food_199', 'en', 'Which country does naan bread come from?', 'India', 'Turkey', 'Iran'),
('food_200', 'en', 'What is galangal?', 'Ginger-like root', 'Type of pepper', 'Citrus family');