-- Topic 12: Music - Add 50 questions (music_151 to music_200)
INSERT INTO questions (id, question, answers, audience, third, source_category, topic_id) VALUES
('music_151', 'Melyik zeneszerző komponálta a "Holdfény szonátát"?', '[{"key":"A","text":"Mozart","correct":false},{"key":"B","text":"Beethoven","correct":true},{"key":"C","text":"Chopin","correct":false}]', '[25,50,25]', 'B', 'mixed', 12),
('music_152', 'Melyik hangszer tartozik a vonós családhoz?', '[{"key":"A","text":"Fuvola","correct":false},{"key":"B","text":"Kürt","correct":false},{"key":"C","text":"Gordonka","correct":true}]', '[20,20,60]', 'C', 'mixed', 12),
('music_153', 'Ki volt a "pop zenei király"?', '[{"key":"A","text":"Elvis Presley","correct":false},{"key":"B","text":"Michael Jackson","correct":true},{"key":"C","text":"Prince","correct":false}]', '[25,50,25]', 'B', 'mixed', 12),
('music_154', 'Melyik országból származik a flamenco zene?', '[{"key":"A","text":"Olaszország","correct":false},{"key":"B","text":"Portugália","correct":false},{"key":"C","text":"Spanyolország","correct":true}]', '[20,20,60]', 'C', 'mixed', 12),
('music_155', 'Hány húrja van egy standard gitárnak?', '[{"key":"A","text":"Hat","correct":true},{"key":"B","text":"Nyolc","correct":false},{"key":"C","text":"Tíz","correct":false}]', '[60,25,15]', 'A', 'mixed', 12),
('music_156', 'Melyik zenekar írta a "Bohemian Rhapsody" dalt?', '[{"key":"A","text":"The Beatles","correct":false},{"key":"B","text":"Queen","correct":true},{"key":"C","text":"Led Zeppelin","correct":false}]', '[20,60,20]', 'B', 'mixed', 12),
('music_157', 'Mi a zene legkisebb egysége?', '[{"key":"A","text":"Hang","correct":true},{"key":"B","text":"Akkord","correct":false},{"key":"C","text":"Dallam","correct":false}]', '[55,25,20]', 'A', 'mixed', 12),
('music_158', 'Melyik országból származik a reggae zene?', '[{"key":"A","text":"Jamaica","correct":true},{"key":"B","text":"Kuba","correct":false},{"key":"C","text":"Brazília","correct":false}]', '[60,20,20]', 'A', 'mixed', 12),
('music_159', 'Ki komponálta a négy évszak című művet?', '[{"key":"A","text":"Bach","correct":false},{"key":"B","text":"Vivaldi","correct":true},{"key":"C","text":"Händel","correct":false}]', '[20,60,20]', 'B', 'mixed', 12),
('music_160', 'Hány billentyű van egy standard zongorán?', '[{"key":"A","text":"76","correct":false},{"key":"B","text":"88","correct":true},{"key":"C","text":"96","correct":false}]', '[25,55,20]', 'B', 'mixed', 12),
('music_161', 'Melyik zenei stílus született New Orleansban?', '[{"key":"A","text":"Rock","correct":false},{"key":"B","text":"Jazz","correct":true},{"key":"C","text":"Country","correct":false}]', '[20,60,20]', 'B', 'mixed', 12),
('music_162', 'Mi a neve a kottában a szünetjelnek?', '[{"key":"A","text":"Pauza","correct":true},{"key":"B","text":"Fermáta","correct":false},{"key":"C","text":"Staccato","correct":false}]', '[55,25,20]', 'A', 'mixed', 12),
('music_163', 'Melyik énekes ismert "The Voice" becenevéről?', '[{"key":"A","text":"Elvis Presley","correct":false},{"key":"B","text":"Frank Sinatra","correct":true},{"key":"C","text":"Nat King Cole","correct":false}]', '[25,55,20]', 'B', 'mixed', 12),
('music_164', 'Melyik hangszer a legnagyobb a vonósoknál?', '[{"key":"A","text":"Hegedű","correct":false},{"key":"B","text":"Brácsa","correct":false},{"key":"C","text":"Nagybőgő","correct":true}]', '[20,25,55]', 'C', 'mixed', 12),
('music_165', 'Melyik együttes a "Fab Four" becenévvel ismert?', '[{"key":"A","text":"The Rolling Stones","correct":false},{"key":"B","text":"The Beatles","correct":true},{"key":"C","text":"The Who","correct":false}]', '[20,60,20]', 'B', 'mixed', 12),
('music_166', 'Mi a neve a zenei hangjegyek öt vonalának?', '[{"key":"A","text":"Kottasor","correct":false},{"key":"B","text":"Vonalrendszer","correct":true},{"key":"C","text":"Hanglétra","correct":false}]', '[30,50,20]', 'B', 'mixed', 12),
('music_167', 'Melyik országból származik a K-pop?', '[{"key":"A","text":"Japán","correct":false},{"key":"B","text":"Kína","correct":false},{"key":"C","text":"Dél-Korea","correct":true}]', '[25,20,55]', 'C', 'mixed', 12),
('music_168', 'Hány szólam van egy kvartettnél?', '[{"key":"A","text":"Három","correct":false},{"key":"B","text":"Négy","correct":true},{"key":"C","text":"Öt","correct":false}]', '[20,60,20]', 'B', 'mixed', 12),
('music_169', 'Ki írta a "Háry János" című operát?', '[{"key":"A","text":"Bartók Béla","correct":false},{"key":"B","text":"Kodály Zoltán","correct":true},{"key":"C","text":"Liszt Ferenc","correct":false}]', '[25,55,20]', 'B', 'mixed', 12),
('music_170', 'Melyik fémből készül általában a trombita?', '[{"key":"A","text":"Sárgaréz","correct":true},{"key":"B","text":"Ezüst","correct":false},{"key":"C","text":"Acél","correct":false}]', '[55,25,20]', 'A', 'mixed', 12),
('music_171', 'Mi a "forte" jelentése a zenében?', '[{"key":"A","text":"Halkan","correct":false},{"key":"B","text":"Hangosan","correct":true},{"key":"C","text":"Lassan","correct":false}]', '[20,60,20]', 'B', 'mixed', 12),
('music_172', 'Melyik zenekar frontembere volt Freddie Mercury?', '[{"key":"A","text":"Kiss","correct":false},{"key":"B","text":"Queen","correct":true},{"key":"C","text":"Aerosmith","correct":false}]', '[15,70,15]', 'B', 'mixed', 12),
('music_173', 'Hány oktáv van egy standard zongorán?', '[{"key":"A","text":"Öt","correct":false},{"key":"B","text":"Hét és egyharmad","correct":true},{"key":"C","text":"Nyolc","correct":false}]', '[25,50,25]', 'B', 'mixed', 12),
('music_174', 'Melyik műfaj a heavy metal őse?', '[{"key":"A","text":"Blues","correct":false},{"key":"B","text":"Hard rock","correct":true},{"key":"C","text":"Punk","correct":false}]', '[25,55,20]', 'B', 'mixed', 12),
('music_175', 'Ki a "Material Girl" című dal előadója?', '[{"key":"A","text":"Cyndi Lauper","correct":false},{"key":"B","text":"Madonna","correct":true},{"key":"C","text":"Whitney Houston","correct":false}]', '[20,60,20]', 'B', 'mixed', 12),
('music_176', 'Mi a "crescendo" jelentése?', '[{"key":"A","text":"Fokozatosan hangosodva","correct":true},{"key":"B","text":"Fokozatosan halkítva","correct":false},{"key":"C","text":"Egyenletes tempóban","correct":false}]', '[55,25,20]', 'A', 'mixed', 12),
('music_177', 'Melyik zenész híres a "Thriller" albumról?', '[{"key":"A","text":"Prince","correct":false},{"key":"B","text":"Michael Jackson","correct":true},{"key":"C","text":"Stevie Wonder","correct":false}]', '[20,65,15]', 'B', 'mixed', 12),
('music_178', 'Hány tagja van egy triónak?', '[{"key":"A","text":"Kettő","correct":false},{"key":"B","text":"Három","correct":true},{"key":"C","text":"Négy","correct":false}]', '[15,70,15]', 'B', 'mixed', 12),
('music_179', 'Melyik hangszercsaládba tartozik a xilofon?', '[{"key":"A","text":"Vonós","correct":false},{"key":"B","text":"Ütős","correct":true},{"key":"C","text":"Fúvós","correct":false}]', '[15,65,20]', 'B', 'mixed', 12),
('music_180', 'Ki komponálta a "Diótörő" balettet?', '[{"key":"A","text":"Sztravinszkij","correct":false},{"key":"B","text":"Csajkovszkij","correct":true},{"key":"C","text":"Prokofjev","correct":false}]', '[20,60,20]', 'B', 'mixed', 12),
('music_181', 'Melyik hangnemben nincs előjegyzés?', '[{"key":"A","text":"C-dúr","correct":true},{"key":"B","text":"G-dúr","correct":false},{"key":"C","text":"D-dúr","correct":false}]', '[60,25,15]', 'A', 'mixed', 12),
('music_182', 'Ki az "Imagine" című dal szerzője?', '[{"key":"A","text":"Paul McCartney","correct":false},{"key":"B","text":"John Lennon","correct":true},{"key":"C","text":"George Harrison","correct":false}]', '[20,65,15]', 'B', 'mixed', 12),
('music_183', 'Mi a "staccato" előadásmód lényege?', '[{"key":"A","text":"Kötött játék","correct":false},{"key":"B","text":"Röviden, szaggatottan","correct":true},{"key":"C","text":"Lassú tempó","correct":false}]', '[25,55,20]', 'B', 'mixed', 12),
('music_184', 'Melyik zenei forma a szonáta?', '[{"key":"A","text":"Hangszeres","correct":true},{"key":"B","text":"Vokális","correct":false},{"key":"C","text":"Tánczenei","correct":false}]', '[55,25,20]', 'A', 'mixed', 12),
('music_185', 'Hány tagja volt a klasszikus Beatles felállásnak?', '[{"key":"A","text":"Három","correct":false},{"key":"B","text":"Négy","correct":true},{"key":"C","text":"Öt","correct":false}]', '[15,70,15]', 'B', 'mixed', 12),
('music_186', 'Melyik országból származik a szamba?', '[{"key":"A","text":"Argentína","correct":false},{"key":"B","text":"Brazília","correct":true},{"key":"C","text":"Kuba","correct":false}]', '[25,55,20]', 'B', 'mixed', 12),
('music_187', 'Mi a "pianissimo" rövidítése?', '[{"key":"A","text":"pp","correct":true},{"key":"B","text":"ff","correct":false},{"key":"C","text":"mf","correct":false}]', '[55,25,20]', 'A', 'mixed', 12),
('music_188', 'Melyik együttes énekelte a "Smells Like Teen Spirit" dalt?', '[{"key":"A","text":"Pearl Jam","correct":false},{"key":"B","text":"Nirvana","correct":true},{"key":"C","text":"Soundgarden","correct":false}]', '[20,60,20]', 'B', 'mixed', 12),
('music_189', 'Hány alaphang van a zenei skálában?', '[{"key":"A","text":"Öt","correct":false},{"key":"B","text":"Hét","correct":true},{"key":"C","text":"Kilenc","correct":false}]', '[20,60,20]', 'B', 'mixed', 12),
('music_190', 'Ki volt a "White Album" kiadója?', '[{"key":"A","text":"The Rolling Stones","correct":false},{"key":"B","text":"The Beatles","correct":true},{"key":"C","text":"The Doors","correct":false}]', '[20,60,20]', 'B', 'mixed', 12),
('music_191', 'Melyik hangszer a legnagyobb a fúvósok közt?', '[{"key":"A","text":"Tuba","correct":true},{"key":"B","text":"Kürt","correct":false},{"key":"C","text":"Trombita","correct":false}]', '[55,25,20]', 'A', 'mixed', 12),
('music_192', 'Mi az "allegro" tempójelzés jelentése?', '[{"key":"A","text":"Lassan","correct":false},{"key":"B","text":"Élénken, gyorsan","correct":true},{"key":"C","text":"Mérsékelt","correct":false}]', '[20,60,20]', 'B', 'mixed', 12),
('music_193', 'Melyik énekes az "I Will Always Love You" előadója?', '[{"key":"A","text":"Mariah Carey","correct":false},{"key":"B","text":"Whitney Houston","correct":true},{"key":"C","text":"Céline Dion","correct":false}]', '[20,60,20]', 'B', 'mixed', 12),
('music_194', 'Hány soros egy limerick vers?', '[{"key":"A","text":"Négy","correct":false},{"key":"B","text":"Öt","correct":true},{"key":"C","text":"Hat","correct":false}]', '[25,55,20]', 'B', 'mixed', 12),
('music_195', 'Melyik zeneszerző volt süket élete végén?', '[{"key":"A","text":"Mozart","correct":false},{"key":"B","text":"Beethoven","correct":true},{"key":"C","text":"Bach","correct":false}]', '[20,65,15]', 'B', 'mixed', 12),
('music_196', 'Mi a "legato" játékmód jelentése?', '[{"key":"A","text":"Kötötten, összefüggően","correct":true},{"key":"B","text":"Szaggatottan","correct":false},{"key":"C","text":"Hangsúlyosan","correct":false}]', '[55,25,20]', 'A', 'mixed', 12),
('music_197', 'Melyik műfaj atyja Louis Armstrong?', '[{"key":"A","text":"Blues","correct":false},{"key":"B","text":"Jazz","correct":true},{"key":"C","text":"Soul","correct":false}]', '[25,55,20]', 'B', 'mixed', 12),
('music_198', 'Hány fő részből áll egy szimfónia hagyományosan?', '[{"key":"A","text":"Három","correct":false},{"key":"B","text":"Négy","correct":true},{"key":"C","text":"Öt","correct":false}]', '[25,55,20]', 'B', 'mixed', 12),
('music_199', 'Ki írta a "Szerelmi bájital" operát?', '[{"key":"A","text":"Verdi","correct":false},{"key":"B","text":"Donizetti","correct":true},{"key":"C","text":"Puccini","correct":false}]', '[25,50,25]', 'B', 'mixed', 12),
('music_200', 'Mi a "ritardando" előadási utasítás?', '[{"key":"A","text":"Gyorsítva","correct":false},{"key":"B","text":"Lassítva","correct":true},{"key":"C","text":"Hangerő növelése","correct":false}]', '[25,55,20]', 'B', 'mixed', 12);

-- Add English translations for Topic 12 questions
INSERT INTO question_translations (question_id, lang, question_text, answer_a, answer_b, answer_c) VALUES
('music_151', 'en', 'Which composer wrote the "Moonlight Sonata"?', 'Mozart', 'Beethoven', 'Chopin'),
('music_152', 'en', 'Which instrument belongs to the string family?', 'Flute', 'Horn', 'Cello'),
('music_153', 'en', 'Who was the "King of Pop"?', 'Elvis Presley', 'Michael Jackson', 'Prince'),
('music_154', 'en', 'Which country does flamenco music come from?', 'Italy', 'Portugal', 'Spain'),
('music_155', 'en', 'How many strings does a standard guitar have?', 'Six', 'Eight', 'Ten'),
('music_156', 'en', 'Which band wrote "Bohemian Rhapsody"?', 'The Beatles', 'Queen', 'Led Zeppelin'),
('music_157', 'en', 'What is the smallest unit of music?', 'Note', 'Chord', 'Melody'),
('music_158', 'en', 'Which country does reggae music come from?', 'Jamaica', 'Cuba', 'Brazil'),
('music_159', 'en', 'Who composed "The Four Seasons"?', 'Bach', 'Vivaldi', 'Handel'),
('music_160', 'en', 'How many keys are on a standard piano?', '76', '88', '96'),
('music_161', 'en', 'Which musical style was born in New Orleans?', 'Rock', 'Jazz', 'Country'),
('music_162', 'en', 'What is the name of the rest symbol in sheet music?', 'Pause', 'Fermata', 'Staccato'),
('music_163', 'en', 'Which singer is known by the nickname "The Voice"?', 'Elvis Presley', 'Frank Sinatra', 'Nat King Cole'),
('music_164', 'en', 'Which is the largest string instrument?', 'Violin', 'Viola', 'Double bass'),
('music_165', 'en', 'Which band is known as the "Fab Four"?', 'The Rolling Stones', 'The Beatles', 'The Who'),
('music_166', 'en', 'What are the five lines of musical notes called?', 'Note row', 'Staff', 'Scale'),
('music_167', 'en', 'Which country does K-pop come from?', 'Japan', 'China', 'South Korea'),
('music_168', 'en', 'How many parts are in a quartet?', 'Three', 'Four', 'Five'),
('music_169', 'en', 'Who wrote the opera "Háry János"?', 'Béla Bartók', 'Zoltán Kodály', 'Franz Liszt'),
('music_170', 'en', 'What metal is a trumpet usually made of?', 'Brass', 'Silver', 'Steel'),
('music_171', 'en', 'What does "forte" mean in music?', 'Quietly', 'Loudly', 'Slowly'),
('music_172', 'en', 'Which band was fronted by Freddie Mercury?', 'Kiss', 'Queen', 'Aerosmith'),
('music_173', 'en', 'How many octaves are on a standard piano?', 'Five', 'Seven and a third', 'Eight'),
('music_174', 'en', 'Which genre is the ancestor of heavy metal?', 'Blues', 'Hard rock', 'Punk'),
('music_175', 'en', 'Who performs the song "Material Girl"?', 'Cyndi Lauper', 'Madonna', 'Whitney Houston'),
('music_176', 'en', 'What does "crescendo" mean?', 'Gradually getting louder', 'Gradually getting softer', 'At a steady tempo'),
('music_177', 'en', 'Which musician is famous for the "Thriller" album?', 'Prince', 'Michael Jackson', 'Stevie Wonder'),
('music_178', 'en', 'How many members are in a trio?', 'Two', 'Three', 'Four'),
('music_179', 'en', 'Which instrument family does the xylophone belong to?', 'String', 'Percussion', 'Wind'),
('music_180', 'en', 'Who composed "The Nutcracker" ballet?', 'Stravinsky', 'Tchaikovsky', 'Prokofiev'),
('music_181', 'en', 'Which key has no sharps or flats?', 'C major', 'G major', 'D major'),
('music_182', 'en', 'Who wrote the song "Imagine"?', 'Paul McCartney', 'John Lennon', 'George Harrison'),
('music_183', 'en', 'What is the essence of staccato playing?', 'Legato playing', 'Short, detached notes', 'Slow tempo'),
('music_184', 'en', 'What type of form is a sonata?', 'Instrumental', 'Vocal', 'Dance music'),
('music_185', 'en', 'How many members were in the classic Beatles lineup?', 'Three', 'Four', 'Five'),
('music_186', 'en', 'Which country does samba come from?', 'Argentina', 'Brazil', 'Cuba'),
('music_187', 'en', 'What is the abbreviation for "pianissimo"?', 'pp', 'ff', 'mf'),
('music_188', 'en', 'Which band sang "Smells Like Teen Spirit"?', 'Pearl Jam', 'Nirvana', 'Soundgarden'),
('music_189', 'en', 'How many basic notes are in a musical scale?', 'Five', 'Seven', 'Nine'),
('music_190', 'en', 'Who released the "White Album"?', 'The Rolling Stones', 'The Beatles', 'The Doors'),
('music_191', 'en', 'Which is the largest wind instrument?', 'Tuba', 'Horn', 'Trumpet'),
('music_192', 'en', 'What does the tempo marking "allegro" mean?', 'Slowly', 'Lively, fast', 'Moderate'),
('music_193', 'en', 'Who performs "I Will Always Love You"?', 'Mariah Carey', 'Whitney Houston', 'Céline Dion'),
('music_194', 'en', 'How many lines are in a limerick poem?', 'Four', 'Five', 'Six'),
('music_195', 'en', 'Which composer was deaf at the end of his life?', 'Mozart', 'Beethoven', 'Bach'),
('music_196', 'en', 'What does "legato" playing mean?', 'Connected, smoothly', 'Detached', 'Accented'),
('music_197', 'en', 'Which genre is Louis Armstrong the father of?', 'Blues', 'Jazz', 'Soul'),
('music_198', 'en', 'How many main parts does a symphony traditionally have?', 'Three', 'Four', 'Five'),
('music_199', 'en', 'Who wrote the opera "The Elixir of Love"?', 'Verdi', 'Donizetti', 'Puccini'),
('music_200', 'en', 'What is the "ritardando" performance instruction?', 'Speed up', 'Slow down', 'Increase volume');