
-- Topic 18: Film és színház - 50 új kérdés (film_151b - film_200b, új ID-kkel a konfliktus elkerülésére)
INSERT INTO public.questions (id, question, answers, audience, third, source_category, topic_id) VALUES
('film_151b', 'Ki rendezte a "Ponyvaregény" című filmet?', '[{"key":"A","text":"Quentin Tarantino","correct":true},{"key":"B","text":"Martin Scorsese","correct":false},{"key":"C","text":"Steven Spielberg","correct":false}]', '{"A":70,"B":20,"C":10}', 'A', 'mixed', 18),
('film_152b', 'Melyik színésznő játszotta Scarlett O''Harát az "Elfújta a szél" című filmben?', '[{"key":"A","text":"Vivien Leigh","correct":true},{"key":"B","text":"Bette Davis","correct":false},{"key":"C","text":"Katharine Hepburn","correct":false}]', '{"A":65,"B":20,"C":15}', 'A', 'mixed', 18),
('film_153b', 'Ki írta a "Rómeó és Júlia" című drámát?', '[{"key":"A","text":"William Shakespeare","correct":true},{"key":"B","text":"Christopher Marlowe","correct":false},{"key":"C","text":"Ben Jonson","correct":false}]', '{"A":85,"B":10,"C":5}', 'A', 'mixed', 18),
('film_154b', 'Melyik film nyerte az első Oscar-díjat a legjobb film kategóriában?', '[{"key":"A","text":"Szárnyak","correct":true},{"key":"B","text":"A dzsesszénekes","correct":false},{"key":"C","text":"Sunrise","correct":false}]', '{"A":40,"B":35,"C":25}', 'A', 'mixed', 18),
('film_155b', 'Ki alakította Jack Sparrow kapitányt?', '[{"key":"A","text":"Johnny Depp","correct":true},{"key":"B","text":"Orlando Bloom","correct":false},{"key":"C","text":"Geoffrey Rush","correct":false}]', '{"A":90,"B":5,"C":5}', 'A', 'mixed', 18),
('film_156b', 'Melyik országból származik az Akira Kurosawa rendező?', '[{"key":"A","text":"Japán","correct":true},{"key":"B","text":"Kína","correct":false},{"key":"C","text":"Dél-Korea","correct":false}]', '{"A":75,"B":15,"C":10}', 'A', 'mixed', 18),
('film_157b', 'Ki rendezte a "Psycho" című horror klasszikust?', '[{"key":"A","text":"Alfred Hitchcock","correct":true},{"key":"B","text":"Roman Polanski","correct":false},{"key":"C","text":"Stanley Kubrick","correct":false}]', '{"A":80,"B":10,"C":10}', 'A', 'mixed', 18),
('film_158b', 'Melyik musical játszódik a francia forradalomban?', '[{"key":"A","text":"Nyomorultak","correct":true},{"key":"B","text":"Az Operaház fantomja","correct":false},{"key":"C","text":"Macskák","correct":false}]', '{"A":70,"B":20,"C":10}', 'A', 'mixed', 18),
('film_159b', 'Ki játszotta Hannibál Lectert "A bárányok hallgatnak" című filmben?', '[{"key":"A","text":"Anthony Hopkins","correct":true},{"key":"B","text":"Mads Mikkelsen","correct":false},{"key":"C","text":"Gary Oldman","correct":false}]', '{"A":85,"B":10,"C":5}', 'A', 'mixed', 18),
('film_160b', 'Melyik évben mutatták be az első hangosfilmet?', '[{"key":"A","text":"1927","correct":true},{"key":"B","text":"1920","correct":false},{"key":"C","text":"1935","correct":false}]', '{"A":55,"B":25,"C":20}', 'A', 'mixed', 18),
('film_161b', 'Ki rendezte a "Schindler listája" című filmet?', '[{"key":"A","text":"Steven Spielberg","correct":true},{"key":"B","text":"Roman Polanski","correct":false},{"key":"C","text":"Martin Scorsese","correct":false}]', '{"A":80,"B":10,"C":10}', 'A', 'mixed', 18),
('film_162b', 'Melyik görög drámaíró írta az "Antigoné" című tragédiát?', '[{"key":"A","text":"Szophoklész","correct":true},{"key":"B","text":"Euripidész","correct":false},{"key":"C","text":"Aiszkhülosz","correct":false}]', '{"A":60,"B":25,"C":15}', 'A', 'mixed', 18),
('film_163b', 'Ki alakította a Terminátort az eredeti filmben?', '[{"key":"A","text":"Arnold Schwarzenegger","correct":true},{"key":"B","text":"Sylvester Stallone","correct":false},{"key":"C","text":"Jean-Claude Van Damme","correct":false}]', '{"A":90,"B":5,"C":5}', 'A', 'mixed', 18),
('film_164b', 'Melyik Broadway musical szól egy zöld boszorkányról?', '[{"key":"A","text":"Wicked","correct":true},{"key":"B","text":"Az Óz nagy varázslója","correct":false},{"key":"C","text":"Into the Woods","correct":false}]', '{"A":75,"B":15,"C":10}', 'A', 'mixed', 18),
('film_165b', 'Ki rendezte a "Taxisofőr" című filmet?', '[{"key":"A","text":"Martin Scorsese","correct":true},{"key":"B","text":"Francis Ford Coppola","correct":false},{"key":"C","text":"Brian De Palma","correct":false}]', '{"A":70,"B":20,"C":10}', 'A', 'mixed', 18),
('film_166b', 'Melyik filmben hangzik el a "Frankly, my dear, I don''t give a damn" mondat?', '[{"key":"A","text":"Elfújta a szél","correct":true},{"key":"B","text":"Casablanca","correct":false},{"key":"C","text":"Citizen Kane","correct":false}]', '{"A":65,"B":25,"C":10}', 'A', 'mixed', 18),
('film_167b', 'Ki írta "A vihar" című színdarabot?', '[{"key":"A","text":"William Shakespeare","correct":true},{"key":"B","text":"Oscar Wilde","correct":false},{"key":"C","text":"George Bernard Shaw","correct":false}]', '{"A":70,"B":20,"C":10}', 'A', 'mixed', 18),
('film_168b', 'Melyik film nyerte a legtöbb Oscar-díjat egyetlen évben?', '[{"key":"A","text":"Ben-Hur / Titanic / A Gyűrűk Ura","correct":true},{"key":"B","text":"West Side Story","correct":false},{"key":"C","text":"A Keresztapa","correct":false}]', '{"A":55,"B":25,"C":20}', 'A', 'mixed', 18),
('film_169b', 'Ki játszotta Vito Corleonét "A Keresztapa" című filmben?', '[{"key":"A","text":"Marlon Brando","correct":true},{"key":"B","text":"Al Pacino","correct":false},{"key":"C","text":"Robert De Niro","correct":false}]', '{"A":75,"B":15,"C":10}', 'A', 'mixed', 18),
('film_170b', 'Melyik drámaíró írta "Az üvegfigurák" című művet?', '[{"key":"A","text":"Tennessee Williams","correct":true},{"key":"B","text":"Arthur Miller","correct":false},{"key":"C","text":"Eugene O''Neill","correct":false}]', '{"A":50,"B":30,"C":20}', 'A', 'mixed', 18),
('film_171b', 'Ki rendezte a "2001: Űrodüsszeia" című filmet?', '[{"key":"A","text":"Stanley Kubrick","correct":true},{"key":"B","text":"Ridley Scott","correct":false},{"key":"C","text":"Steven Spielberg","correct":false}]', '{"A":75,"B":15,"C":10}', 'A', 'mixed', 18),
('film_172b', 'Melyik színész játszotta először James Bondot?', '[{"key":"A","text":"Sean Connery","correct":true},{"key":"B","text":"Roger Moore","correct":false},{"key":"C","text":"David Niven","correct":false}]', '{"A":80,"B":15,"C":5}', 'A', 'mixed', 18),
('film_173b', 'Ki írta "A nagy Gatsby" filmadaptáció alapjául szolgáló regényt?', '[{"key":"A","text":"F. Scott Fitzgerald","correct":true},{"key":"B","text":"Ernest Hemingway","correct":false},{"key":"C","text":"John Steinbeck","correct":false}]', '{"A":70,"B":20,"C":10}', 'A', 'mixed', 18),
('film_174b', 'Melyik musical Andrew Lloyd Webber szerzeménye?', '[{"key":"A","text":"Macskák","correct":true},{"key":"B","text":"Chicago","correct":false},{"key":"C","text":"Cabaret","correct":false}]', '{"A":70,"B":20,"C":10}', 'A', 'mixed', 18),
('film_175b', 'Ki alakította Neo-t a Mátrix trilógiában?', '[{"key":"A","text":"Keanu Reeves","correct":true},{"key":"B","text":"Laurence Fishburne","correct":false},{"key":"C","text":"Hugo Weaving","correct":false}]', '{"A":90,"B":5,"C":5}', 'A', 'mixed', 18),
('film_176b', 'Melyik filmben szerepel a "Here''s looking at you, kid" mondat?', '[{"key":"A","text":"Casablanca","correct":true},{"key":"B","text":"Elfújta a szél","correct":false},{"key":"C","text":"Római vakáció","correct":false}]', '{"A":70,"B":20,"C":10}', 'A', 'mixed', 18),
('film_177b', 'Ki rendezte "A piros lámpás ház" című musicalt?', '[{"key":"A","text":"Baz Luhrmann","correct":true},{"key":"B","text":"Rob Marshall","correct":false},{"key":"C","text":"Tim Burton","correct":false}]', '{"A":60,"B":25,"C":15}', 'A', 'mixed', 18),
('film_178b', 'Melyik színésznő játszotta Holly Golightlyt a "Álom luxuskivitelben" filmben?', '[{"key":"A","text":"Audrey Hepburn","correct":true},{"key":"B","text":"Marilyn Monroe","correct":false},{"key":"C","text":"Grace Kelly","correct":false}]', '{"A":80,"B":10,"C":10}', 'A', 'mixed', 18),
('film_179b', 'Ki írta "Az ember tragédiája" című drámai költeményt?', '[{"key":"A","text":"Madách Imre","correct":true},{"key":"B","text":"Katona József","correct":false},{"key":"C","text":"Vörösmarty Mihály","correct":false}]', '{"A":75,"B":15,"C":10}', 'A', 'mixed', 18),
('film_180b', 'Melyik filmben játszott először Leonardo DiCaprio főszerepet?', '[{"key":"A","text":"Gilbert Grape","correct":true},{"key":"B","text":"Titanic","correct":false},{"key":"C","text":"Rómeó + Júlia","correct":false}]', '{"A":45,"B":40,"C":15}', 'A', 'mixed', 18),
('film_181b', 'Ki rendezte a "Száll a kakukk fészkére" című filmet?', '[{"key":"A","text":"Miloš Forman","correct":true},{"key":"B","text":"Roman Polanski","correct":false},{"key":"C","text":"Stanley Kubrick","correct":false}]', '{"A":60,"B":25,"C":15}', 'A', 'mixed', 18),
('film_182b', 'Melyik színház a Broadway központja?', '[{"key":"A","text":"New York","correct":true},{"key":"B","text":"Los Angeles","correct":false},{"key":"C","text":"Chicago","correct":false}]', '{"A":85,"B":10,"C":5}', 'A', 'mixed', 18),
('film_183b', 'Ki játszotta Forrest Gumpot?', '[{"key":"A","text":"Tom Hanks","correct":true},{"key":"B","text":"Tom Cruise","correct":false},{"key":"C","text":"Robin Williams","correct":false}]', '{"A":90,"B":5,"C":5}', 'A', 'mixed', 18),
('film_184b', 'Melyik drámaíró írta "Az ügynök halála" című művet?', '[{"key":"A","text":"Arthur Miller","correct":true},{"key":"B","text":"Tennessee Williams","correct":false},{"key":"C","text":"Eugene O''Neill","correct":false}]', '{"A":55,"B":30,"C":15}', 'A', 'mixed', 18),
('film_185b', 'Ki rendezte az "Eredet" (Inception) című filmet?', '[{"key":"A","text":"Christopher Nolan","correct":true},{"key":"B","text":"Denis Villeneuve","correct":false},{"key":"C","text":"Ridley Scott","correct":false}]', '{"A":85,"B":10,"C":5}', 'A', 'mixed', 18),
('film_186b', 'Melyik filmben szerepelt először Darth Vader?', '[{"key":"A","text":"Csillagok háborúja: Egy új remény","correct":true},{"key":"B","text":"A Birodalom visszavág","correct":false},{"key":"C","text":"A Jedi visszatér","correct":false}]', '{"A":80,"B":15,"C":5}', 'A', 'mixed', 18),
('film_187b', 'Ki írta "A három nővér" című drámát?', '[{"key":"A","text":"Anton Csehov","correct":true},{"key":"B","text":"Makszim Gorkij","correct":false},{"key":"C","text":"Lev Tolsztoj","correct":false}]', '{"A":65,"B":20,"C":15}', 'A', 'mixed', 18),
('film_188b', 'Melyik színésznő nyerte a legtöbb Oscar-díjat?', '[{"key":"A","text":"Katharine Hepburn","correct":true},{"key":"B","text":"Meryl Streep","correct":false},{"key":"C","text":"Bette Davis","correct":false}]', '{"A":55,"B":35,"C":10}', 'A', 'mixed', 18),
('film_189b', 'Ki rendezte a "Hetedik pecsét" című filmet?', '[{"key":"A","text":"Ingmar Bergman","correct":true},{"key":"B","text":"Federico Fellini","correct":false},{"key":"C","text":"Andrei Tarkovszkij","correct":false}]', '{"A":60,"B":25,"C":15}', 'A', 'mixed', 18),
('film_190b', 'Melyik musical Stephen Sondheim szerzeménye?', '[{"key":"A","text":"Sweeney Todd","correct":true},{"key":"B","text":"Az Operaház fantomja","correct":false},{"key":"C","text":"Nyomorultak","correct":false}]', '{"A":50,"B":30,"C":20}', 'A', 'mixed', 18),
('film_191b', 'Ki játszotta Indiana Jonest?', '[{"key":"A","text":"Harrison Ford","correct":true},{"key":"B","text":"Sean Connery","correct":false},{"key":"C","text":"Mel Gibson","correct":false}]', '{"A":90,"B":5,"C":5}', 'A', 'mixed', 18),
('film_192b', 'Melyik országban található a Cannes-i Filmfesztivál?', '[{"key":"A","text":"Franciaország","correct":true},{"key":"B","text":"Olaszország","correct":false},{"key":"C","text":"Spanyolország","correct":false}]', '{"A":85,"B":10,"C":5}', 'A', 'mixed', 18),
('film_193b', 'Ki írta "A mizantróp" című komédiát?', '[{"key":"A","text":"Molière","correct":true},{"key":"B","text":"Pierre Corneille","correct":false},{"key":"C","text":"Jean Racine","correct":false}]', '{"A":60,"B":25,"C":15}', 'A', 'mixed', 18),
('film_194b', 'Melyik filmben hangzik el "I''ll be back" mondat?', '[{"key":"A","text":"Terminátor","correct":true},{"key":"B","text":"Predator","correct":false},{"key":"C","text":"Total Recall","correct":false}]', '{"A":85,"B":10,"C":5}', 'A', 'mixed', 18),
('film_195b', 'Ki rendezte a "Dolce Vita" című filmet?', '[{"key":"A","text":"Federico Fellini","correct":true},{"key":"B","text":"Luchino Visconti","correct":false},{"key":"C","text":"Roberto Rossellini","correct":false}]', '{"A":65,"B":20,"C":15}', 'A', 'mixed', 18),
('film_196b', 'Melyik színész alakította Jokert "A sötét lovag" című filmben?', '[{"key":"A","text":"Heath Ledger","correct":true},{"key":"B","text":"Jack Nicholson","correct":false},{"key":"C","text":"Joaquin Phoenix","correct":false}]', '{"A":80,"B":10,"C":10}', 'A', 'mixed', 18),
('film_197b', 'Ki írta "Godot-ra várva" című abszurd drámát?', '[{"key":"A","text":"Samuel Beckett","correct":true},{"key":"B","text":"Harold Pinter","correct":false},{"key":"C","text":"Eugène Ionesco","correct":false}]', '{"A":60,"B":25,"C":15}', 'A', 'mixed', 18),
('film_198b', 'Melyik film volt Pixar első egész estés animációja?', '[{"key":"A","text":"Toy Story","correct":true},{"key":"B","text":"Némó nyomában","correct":false},{"key":"C","text":"Szörny Rt.","correct":false}]', '{"A":85,"B":10,"C":5}', 'A', 'mixed', 18),
('film_199b', 'Ki rendezte a "Visszatérés a jövőbe" trilógiát?', '[{"key":"A","text":"Robert Zemeckis","correct":true},{"key":"B","text":"Steven Spielberg","correct":false},{"key":"C","text":"James Cameron","correct":false}]', '{"A":65,"B":25,"C":10}', 'A', 'mixed', 18),
('film_200b', 'Melyik Bródy Sándor műve alapján készült magyar film?', '[{"key":"A","text":"A tanítónő","correct":true},{"key":"B","text":"A Pál utcai fiúk","correct":false},{"key":"C","text":"Egri csillagok","correct":false}]', '{"A":45,"B":35,"C":20}', 'A', 'mixed', 18);

-- Topic 18 translations
INSERT INTO public.question_translations (question_id, lang, question_text, answer_a, answer_b, answer_c) VALUES
('film_151b', 'en', 'Who directed "Pulp Fiction"?', 'Quentin Tarantino', 'Martin Scorsese', 'Steven Spielberg'),
('film_152b', 'en', 'Which actress played Scarlett O''Hara in "Gone with the Wind"?', 'Vivien Leigh', 'Bette Davis', 'Katharine Hepburn'),
('film_153b', 'en', 'Who wrote the play "Romeo and Juliet"?', 'William Shakespeare', 'Christopher Marlowe', 'Ben Jonson'),
('film_154b', 'en', 'Which film won the first Academy Award for Best Picture?', 'Wings', 'The Jazz Singer', 'Sunrise'),
('film_155b', 'en', 'Who played Captain Jack Sparrow?', 'Johnny Depp', 'Orlando Bloom', 'Geoffrey Rush'),
('film_156b', 'en', 'Which country is director Akira Kurosawa from?', 'Japan', 'China', 'South Korea'),
('film_157b', 'en', 'Who directed the classic horror film "Psycho"?', 'Alfred Hitchcock', 'Roman Polanski', 'Stanley Kubrick'),
('film_158b', 'en', 'Which musical is set during the French Revolution?', 'Les Misérables', 'The Phantom of the Opera', 'Cats'),
('film_159b', 'en', 'Who played Hannibal Lecter in "The Silence of the Lambs"?', 'Anthony Hopkins', 'Mads Mikkelsen', 'Gary Oldman'),
('film_160b', 'en', 'In which year was the first sound film released?', '1927', '1920', '1935'),
('film_161b', 'en', 'Who directed "Schindler''s List"?', 'Steven Spielberg', 'Roman Polanski', 'Martin Scorsese'),
('film_162b', 'en', 'Which Greek playwright wrote the tragedy "Antigone"?', 'Sophocles', 'Euripides', 'Aeschylus'),
('film_163b', 'en', 'Who played the Terminator in the original film?', 'Arnold Schwarzenegger', 'Sylvester Stallone', 'Jean-Claude Van Damme'),
('film_164b', 'en', 'Which Broadway musical is about a green witch?', 'Wicked', 'The Wizard of Oz', 'Into the Woods'),
('film_165b', 'en', 'Who directed "Taxi Driver"?', 'Martin Scorsese', 'Francis Ford Coppola', 'Brian De Palma'),
('film_166b', 'en', 'In which film is the line "Frankly, my dear, I don''t give a damn" spoken?', 'Gone with the Wind', 'Casablanca', 'Citizen Kane'),
('film_167b', 'en', 'Who wrote the play "The Tempest"?', 'William Shakespeare', 'Oscar Wilde', 'George Bernard Shaw'),
('film_168b', 'en', 'Which film has won the most Academy Awards in a single year?', 'Ben-Hur / Titanic / The Lord of the Rings', 'West Side Story', 'The Godfather'),
('film_169b', 'en', 'Who played Vito Corleone in "The Godfather"?', 'Marlon Brando', 'Al Pacino', 'Robert De Niro'),
('film_170b', 'en', 'Which playwright wrote "The Glass Menagerie"?', 'Tennessee Williams', 'Arthur Miller', 'Eugene O''Neill'),
('film_171b', 'en', 'Who directed "2001: A Space Odyssey"?', 'Stanley Kubrick', 'Ridley Scott', 'Steven Spielberg'),
('film_172b', 'en', 'Which actor first played James Bond?', 'Sean Connery', 'Roger Moore', 'David Niven'),
('film_173b', 'en', 'Who wrote the novel that "The Great Gatsby" film is based on?', 'F. Scott Fitzgerald', 'Ernest Hemingway', 'John Steinbeck'),
('film_174b', 'en', 'Which musical is composed by Andrew Lloyd Webber?', 'Cats', 'Chicago', 'Cabaret'),
('film_175b', 'en', 'Who played Neo in The Matrix trilogy?', 'Keanu Reeves', 'Laurence Fishburne', 'Hugo Weaving'),
('film_176b', 'en', 'In which film does the line "Here''s looking at you, kid" appear?', 'Casablanca', 'Gone with the Wind', 'Roman Holiday'),
('film_177b', 'en', 'Who directed the musical "Moulin Rouge!"?', 'Baz Luhrmann', 'Rob Marshall', 'Tim Burton'),
('film_178b', 'en', 'Which actress played Holly Golightly in "Breakfast at Tiffany''s"?', 'Audrey Hepburn', 'Marilyn Monroe', 'Grace Kelly'),
('film_179b', 'en', 'Who wrote the dramatic poem "The Tragedy of Man"?', 'Imre Madách', 'József Katona', 'Mihály Vörösmarty'),
('film_180b', 'en', 'In which film did Leonardo DiCaprio first star?', 'Gilbert Grape', 'Titanic', 'Romeo + Juliet'),
('film_181b', 'en', 'Who directed "One Flew Over the Cuckoo''s Nest"?', 'Miloš Forman', 'Roman Polanski', 'Stanley Kubrick'),
('film_182b', 'en', 'Which city is the center of Broadway?', 'New York', 'Los Angeles', 'Chicago'),
('film_183b', 'en', 'Who played Forrest Gump?', 'Tom Hanks', 'Tom Cruise', 'Robin Williams'),
('film_184b', 'en', 'Which playwright wrote "Death of a Salesman"?', 'Arthur Miller', 'Tennessee Williams', 'Eugene O''Neill'),
('film_185b', 'en', 'Who directed "Inception"?', 'Christopher Nolan', 'Denis Villeneuve', 'Ridley Scott'),
('film_186b', 'en', 'In which film did Darth Vader first appear?', 'Star Wars: A New Hope', 'The Empire Strikes Back', 'Return of the Jedi'),
('film_187b', 'en', 'Who wrote the play "Three Sisters"?', 'Anton Chekhov', 'Maxim Gorky', 'Leo Tolstoy'),
('film_188b', 'en', 'Which actress has won the most Academy Awards?', 'Katharine Hepburn', 'Meryl Streep', 'Bette Davis'),
('film_189b', 'en', 'Who directed "The Seventh Seal"?', 'Ingmar Bergman', 'Federico Fellini', 'Andrei Tarkovsky'),
('film_190b', 'en', 'Which musical is composed by Stephen Sondheim?', 'Sweeney Todd', 'The Phantom of the Opera', 'Les Misérables'),
('film_191b', 'en', 'Who played Indiana Jones?', 'Harrison Ford', 'Sean Connery', 'Mel Gibson'),
('film_192b', 'en', 'In which country is the Cannes Film Festival held?', 'France', 'Italy', 'Spain'),
('film_193b', 'en', 'Who wrote the comedy "The Misanthrope"?', 'Molière', 'Pierre Corneille', 'Jean Racine'),
('film_194b', 'en', 'In which film is the line "I''ll be back" spoken?', 'The Terminator', 'Predator', 'Total Recall'),
('film_195b', 'en', 'Who directed "La Dolce Vita"?', 'Federico Fellini', 'Luchino Visconti', 'Roberto Rossellini'),
('film_196b', 'en', 'Which actor played the Joker in "The Dark Knight"?', 'Heath Ledger', 'Jack Nicholson', 'Joaquin Phoenix'),
('film_197b', 'en', 'Who wrote the absurdist play "Waiting for Godot"?', 'Samuel Beckett', 'Harold Pinter', 'Eugène Ionesco'),
('film_198b', 'en', 'What was Pixar''s first feature-length animation?', 'Toy Story', 'Finding Nemo', 'Monsters, Inc.'),
('film_199b', 'en', 'Who directed the "Back to the Future" trilogy?', 'Robert Zemeckis', 'Steven Spielberg', 'James Cameron'),
('film_200b', 'en', 'Which Hungarian film is based on Sándor Bródy''s work?', 'The Schoolmistress', 'The Paul Street Boys', 'Eclipse of the Crescent Moon');
