
-- Add missing English translations for Topic 5 (mentalis 151-200)
INSERT INTO question_translations (question_id, lang, question_text, answer_a, answer_b, answer_c)
VALUES
('mentalis_151', 'en', 'What is Cognitive Behavioral Therapy (CBT)?', 'Drug treatment', 'Talk therapy changing thought patterns', 'Hypnosis'),
('mentalis_152', 'en', 'What is the main symptom of a panic attack?', 'Sleepiness', 'Intense fear and physical symptoms', 'Increased appetite'),
('mentalis_153', 'en', 'What is bipolar disorder?', 'Personality disorder', 'Mood swings between mania and depression', 'Anxiety disorder'),
('mentalis_154', 'en', 'What is PTSD?', 'Personality disorder', 'Post-Traumatic Stress Disorder', 'Learning disability'),
('mentalis_155', 'en', 'Which is NOT a symptom of depression?', 'Hopelessness', 'Increased energy', 'Sleep problems'),
('mentalis_156', 'en', 'What is mindfulness?', 'Future planning', 'Present moment awareness', 'Memory technique'),
('mentalis_157', 'en', 'Which is a sign of generalized anxiety?', 'Euphoria', 'Excessive worry', 'Memory loss'),
('mentalis_158', 'en', 'What is schizophrenia?', 'Mood disorder', 'Serious mental disorder with delusions', 'Anxiety disorder'),
('mentalis_159', 'en', 'What helps with stress management?', 'Isolation', 'Exercise and relaxation', 'Caffeine'),
('mentalis_160', 'en', 'What is OCD?', 'Mood disorder', 'Obsessive-Compulsive Disorder', 'Personality disorder'),
('mentalis_161', 'en', 'What is social phobia?', 'Fear of animals', 'Fear of social situations', 'Fear of heights'),
('mentalis_162', 'en', 'Which is a symptom of burnout?', 'Increased productivity', 'Emotional exhaustion', 'Better focus'),
('mentalis_163', 'en', 'What is anorexia nervosa?', 'Overeating disorder', 'Eating disorder with self-starvation', 'Sleep disorder'),
('mentalis_164', 'en', 'What is the relationship between serotonin and mood?', 'No connection', 'Low serotonin linked to depression', 'High serotonin causes anxiety'),
('mentalis_165', 'en', 'What is psychotherapy?', 'Drug treatment only', 'Talk therapy for mental health', 'Brain surgery'),
('mentalis_166', 'en', 'What is ADHD?', 'Learning style', 'Attention Deficit Hyperactivity Disorder', 'Personality trait'),
('mentalis_167', 'en', 'What is emotional intelligence?', 'IQ score', 'Understanding and managing emotions', 'Memory ability'),
('mentalis_168', 'en', 'What is resilience?', 'Stubbornness', 'Ability to recover from difficulties', 'Avoidance'),
('mentalis_169', 'en', 'Which helps improve sleep quality?', 'Screen time before bed', 'Regular sleep schedule', 'Caffeine at night'),
('mentalis_170', 'en', 'What is bulimia nervosa?', 'Anorexia', 'Binge eating followed by purging', 'Overeating disorder'),
('mentalis_171', 'en', 'What is self-esteem?', 'Arrogance', 'Self-worth and confidence', 'Selfishness'),
('mentalis_172', 'en', 'Which is a physical symptom of anxiety?', 'Relaxation', 'Rapid heartbeat', 'Sleepiness'),
('mentalis_173', 'en', 'What is dissociation?', 'Focus', 'Disconnection from thoughts or surroundings', 'Sleep state'),
('mentalis_174', 'en', 'What is the main goal of meditation?', 'Problem solving', 'Inner calm and awareness', 'Physical exercise'),
('mentalis_175', 'en', 'What is the natural process of grief?', 'Immediate recovery', 'Stages of processing loss', 'Permanent sadness'),
('mentalis_176', 'en', 'What is agoraphobia?', 'Fear of spiders', 'Fear of open or crowded spaces', 'Fear of water'),
('mentalis_177', 'en', 'What is empathy?', 'Sympathy', 'Understanding others feelings', 'Apathy'),
('mentalis_178', 'en', 'What is the effect of trauma on mental health?', 'No effect', 'Long-lasting psychological impact', 'Only physical effects'),
('mentalis_179', 'en', 'What is positive psychology?', 'Denial of problems', 'Focus on wellbeing and strengths', 'Ignoring emotions'),
('mentalis_180', 'en', 'Which is a risk factor for depression?', 'Strong social support', 'Family history', 'Regular exercise'),
('mentalis_181', 'en', 'What is assertiveness?', 'Aggression', 'Confident self-expression', 'Passivity'),
('mentalis_182', 'en', 'What is somatization?', 'Physical illness', 'Psychological stress causing physical symptoms', 'Drug reaction'),
('mentalis_183', 'en', 'What is self-awareness?', 'Selfishness', 'Understanding own thoughts and feelings', 'Arrogance'),
('mentalis_184', 'en', 'Which does NOT help mental health?', 'Exercise', 'Social isolation', 'Healthy sleep'),
('mentalis_185', 'en', 'What is the role of dopamine?', 'Only causes pain', 'Reward and pleasure chemical', 'Sleep hormone'),
('mentalis_186', 'en', 'What is the stress response?', 'Relaxation', 'Fight or flight reaction', 'Sleep reflex'),
('mentalis_187', 'en', 'What is the purpose of setting boundaries?', 'Pushing others away', 'Protecting mental wellbeing', 'Being selfish'),
('mentalis_188', 'en', 'What is alexithymia?', 'Emotional intelligence', 'Difficulty identifying emotions', 'Memory problem'),
('mentalis_189', 'en', 'What is the mental health benefit of journaling?', 'No benefit', 'Processing emotions and reducing stress', 'Wasting time'),
('mentalis_190', 'en', 'What is the role of social support?', 'No impact', 'Improves mental health resilience', 'Increases stress'),
('mentalis_191', 'en', 'What is the downside of perfectionism?', 'Better work quality', 'Anxiety and never feeling good enough', 'Increased confidence'),
('mentalis_192', 'en', 'What is the effect of chronic stress?', 'No effect', 'Physical and mental health problems', 'Improved focus'),
('mentalis_193', 'en', 'What is self-love?', 'Narcissism', 'Caring for your own wellbeing', 'Selfishness'),
('mentalis_194', 'en', 'What is the psychological background of procrastination?', 'Laziness', 'Fear of failure or perfectionism', 'Good time management'),
('mentalis_195', 'en', 'What is a grounding technique?', 'Flying technique', 'Method to connect with present moment', 'Meditation only'),
('mentalis_196', 'en', 'What is rumination?', 'Positive thinking', 'Repetitive negative thinking', 'Problem solving'),
('mentalis_197', 'en', 'What is emotion regulation?', 'Suppressing emotions', 'Managing emotional responses', 'Ignoring feelings'),
('mentalis_198', 'en', 'What is the effect of stigma on mental illness?', 'No effect', 'Prevents seeking help', 'Encourages treatment'),
('mentalis_199', 'en', 'What is psychological wellbeing?', 'Only happiness', 'Overall mental health and life satisfaction', 'Absence of problems'),
('mentalis_200', 'en', 'Which is most important for mental health?', 'Isolation', 'Balance and self-care', 'Workaholism')
ON CONFLICT (question_id, lang) DO NOTHING;

-- Add missing English translations for Topic 6 (magyartor 151-200)
INSERT INTO question_translations (question_id, lang, question_text, answer_a, answer_b, answer_c)
VALUES
('magyartor_151', 'en', 'In which year was the Mongol invasion?', '1241', '1301', '1456'),
('magyartor_152', 'en', 'Who was the last Árpád dynasty king?', 'Stephen I', 'Andrew III', 'Béla IV'),
('magyartor_153', 'en', 'In which year was the Battle of Mohács?', '1456', '1526', '1541'),
('magyartor_154', 'en', 'Who was John Hunyadi?', 'King', 'Military leader and regent', 'Poet'),
('magyartor_155', 'en', 'In which year was the Golden Bull issued?', '1222', '1241', '1301'),
('magyartor_156', 'en', 'Who crowned Saint Stephen?', 'Pope Sylvester II', 'Pope Gregory VII', 'Pope Innocent III'),
('magyartor_157', 'en', 'Which city was the coronation capital?', 'Budapest', 'Székesfehérvár', 'Esztergom'),
('magyartor_158', 'en', 'Who was King Matthias mother?', 'Elizabeth Báthory', 'Elizabeth Szilágyi', 'Elizabeth Habsburg'),
('magyartor_159', 'en', 'In which year was the Siege of Belgrade?', '1456', '1526', '1541'),
('magyartor_160', 'en', 'Who founded the Corvina Library?', 'Béla IV', 'King Matthias', 'John Hunyadi'),
('magyartor_161', 'en', 'How long did Turkish occupation last?', '100 years', '150 years', '200 years'),
('magyartor_162', 'en', 'Who led Rákóczi War of Independence?', 'Lajos Kossuth', 'Francis II Rákóczi', 'Imre Thököly'),
('magyartor_163', 'en', 'In which year was the Austro-Hungarian Compromise?', '1848', '1867', '1918'),
('magyartor_164', 'en', 'Who wrote the Hungarian National Anthem?', 'Sándor Petőfi', 'Ferenc Kölcsey', 'Mihály Vörösmarty'),
('magyartor_165', 'en', 'When did the 1848 Revolution begin?', 'March 15', 'April 11', 'October 6'),
('magyartor_166', 'en', 'Who was Lajos Batthyány?', 'Poet', 'First Hungarian Prime Minister', 'General'),
('magyartor_167', 'en', 'How many Arad martyrs were there?', '12', '13', '15'),
('magyartor_168', 'en', 'Who was István Széchenyi?', 'Poet', 'Reformer and statesman', 'General'),
('magyartor_169', 'en', 'Which bridge did Széchenyi build?', 'Margaret Bridge', 'Chain Bridge', 'Elizabeth Bridge'),
('magyartor_170', 'en', 'In which year was the Treaty of Trianon?', '1918', '1920', '1921'),
('magyartor_171', 'en', 'Who was Lajos Kossuth?', 'Poet', 'Revolutionary leader', 'King'),
('magyartor_172', 'en', 'When was the 1956 Revolution?', 'March', 'October', 'November'),
('magyartor_173', 'en', 'Who was the first Hungarian king?', 'Árpád', 'Saint Stephen', 'Andrew I'),
('magyartor_174', 'en', 'Which family ruled Hungary from 1000-1301?', 'Habsburg', 'Árpád dynasty', 'Anjou'),
('magyartor_175', 'en', 'What was the Dual Monarchy?', 'Austria-Prussia', 'Austria-Hungary', 'Hungary-Poland'),
('magyartor_176', 'en', 'When did Hungary join NATO?', '1989', '1999', '2004'),
('magyartor_177', 'en', 'When did Hungary join the EU?', '1999', '2004', '2007'),
('magyartor_178', 'en', 'Who was Miklós Horthy?', 'King', 'Regent', 'Prime Minister'),
('magyartor_179', 'en', 'When was the Hungarian People Republic established?', '1946', '1949', '1956'),
('magyartor_180', 'en', 'When did the regime change happen?', '1989', '1991', '1993'),
('magyartor_181', 'en', 'What was the largest territorial loss after Trianon?', 'Transylvania', 'Slovakia', 'Croatia'),
('magyartor_182', 'en', 'Who was Imre Nagy?', 'Communist leader', '1956 revolution Prime Minister', 'Regent'),
('magyartor_183', 'en', 'When was the Holy Crown returned?', '1978', '1999', '2000'),
('magyartor_184', 'en', 'Who was the last King of Hungary?', 'Franz Joseph I', 'Charles IV', 'William II'),
('magyartor_185', 'en', 'When was the Battle of Buda Castle?', '1541', '1686', '1848'),
('magyartor_186', 'en', 'What is August 20th?', 'Independence Day', 'St. Stephens Day', 'Revolution Day'),
('magyartor_187', 'en', 'Who was Béla Bartók?', 'Poet', 'Composer', 'Politician'),
('magyartor_188', 'en', 'What is the national currency?', 'Euro', 'Forint', 'Korona'),
('magyartor_189', 'en', 'Which country did Transylvania belong to before Trianon?', 'Romania', 'Hungary', 'Austria'),
('magyartor_190', 'en', 'Who was the last Habsburg king?', 'Franz Joseph I', 'Charles IV', 'Rudolf I'),
('magyartor_191', 'en', 'When was the Hungarian constitution first written?', '1222', '1848', '1949'),
('magyartor_192', 'en', 'Which river divides Budapest?', 'Tisza', 'Danube', 'Drava'),
('magyartor_193', 'en', 'What was Pannonias historical name?', 'Dacia', 'Roman province in Hungary', 'Illyricum'),
('magyartor_194', 'en', 'When did Hungarians settle in Carpathian Basin?', '596', '896', '1000'),
('magyartor_195', 'en', 'Who was Albert Szent-Györgyi?', 'Politician', 'Nobel Prize winning scientist', 'Composer'),
('magyartor_196', 'en', 'What is rubiks cube inventor nationality?', 'American', 'Hungarian', 'German'),
('magyartor_197', 'en', 'Who was Ferenc Puskás?', 'Politician', 'Football legend', 'Composer'),
('magyartor_198', 'en', 'When was the first Hungarian university founded?', '1367', '1635', '1872'),
('magyartor_199', 'en', 'Who wrote Tragedy of Man?', 'Sándor Petőfi', 'Imre Madách', 'János Arany'),
('magyartor_200', 'en', 'What is Hungarys population approximately?', '5 million', '10 million', '15 million')
ON CONFLICT (question_id, lang) DO NOTHING;
