-- Topic 14: Art & Literature - Add 50 questions (art_151 to art_200)
INSERT INTO questions (id, question, answers, audience, third, source_category, topic_id) VALUES
('art_151', 'Ki festette a "Csillagos éj" című képet?', '[{"key":"A","text":"Claude Monet","correct":false},{"key":"B","text":"Vincent van Gogh","correct":true},{"key":"C","text":"Pablo Picasso","correct":false}]', '[20,60,20]', 'B', 'mixed', 14),
('art_152', 'Melyik író alkotta meg Sherlock Holmes karakterét?', '[{"key":"A","text":"Arthur Conan Doyle","correct":true},{"key":"B","text":"Agatha Christie","correct":false},{"key":"C","text":"Edgar Allan Poe","correct":false}]', '[60,20,20]', 'A', 'mixed', 14),
('art_153', 'Hol található a Mona Lisa?', '[{"key":"A","text":"Uffizi Galéria","correct":false},{"key":"B","text":"Louvre","correct":true},{"key":"C","text":"Prado","correct":false}]', '[20,65,15]', 'B', 'mixed', 14),
('art_154', 'Ki írta a "Hamlet" című drámát?', '[{"key":"A","text":"William Shakespeare","correct":true},{"key":"B","text":"Christopher Marlowe","correct":false},{"key":"C","text":"Ben Jonson","correct":false}]', '[70,15,15]', 'A', 'mixed', 14),
('art_155', 'Melyik festészeti irányzat képviselője Salvador Dalí?', '[{"key":"A","text":"Impresszionizmus","correct":false},{"key":"B","text":"Szürrealizmus","correct":true},{"key":"C","text":"Kubizmus","correct":false}]', '[20,60,20]', 'B', 'mixed', 14),
('art_156', 'Ki írta a "Háború és béke" című regényt?', '[{"key":"A","text":"Lev Tolsztoj","correct":true},{"key":"B","text":"Fjodor Dosztojevszkij","correct":false},{"key":"C","text":"Anton Csehov","correct":false}]', '[60,25,15]', 'A', 'mixed', 14),
('art_157', 'Melyik művész készítette a Dávid szobrot?', '[{"key":"A","text":"Donatello","correct":false},{"key":"B","text":"Michelangelo","correct":true},{"key":"C","text":"Bernini","correct":false}]', '[20,60,20]', 'B', 'mixed', 14),
('art_158', 'Ki írta az "1984" című disztópiát?', '[{"key":"A","text":"George Orwell","correct":true},{"key":"B","text":"Aldous Huxley","correct":false},{"key":"C","text":"Ray Bradbury","correct":false}]', '[60,25,15]', 'A', 'mixed', 14),
('art_159', 'Melyik stílus jellemzi Monet festményeit?', '[{"key":"A","text":"Impresszionizmus","correct":true},{"key":"B","text":"Expresszionizmus","correct":false},{"key":"C","text":"Realizmus","correct":false}]', '[60,20,20]', 'A', 'mixed', 14),
('art_160', 'Ki írta a "Bűn és bűnhődés" című regényt?', '[{"key":"A","text":"Lev Tolsztoj","correct":false},{"key":"B","text":"Fjodor Dosztojevszkij","correct":true},{"key":"C","text":"Ivan Turgenyev","correct":false}]', '[25,55,20]', 'B', 'mixed', 14),
('art_161', 'Melyik festő vágta le saját fülét?', '[{"key":"A","text":"Vincent van Gogh","correct":true},{"key":"B","text":"Paul Gauguin","correct":false},{"key":"C","text":"Edvard Munch","correct":false}]', '[60,20,20]', 'A', 'mixed', 14),
('art_162', 'Ki írta a "Kis herceg" című könyvet?', '[{"key":"A","text":"Antoine de Saint-Exupéry","correct":true},{"key":"B","text":"Jules Verne","correct":false},{"key":"C","text":"Victor Hugo","correct":false}]', '[60,20,20]', 'A', 'mixed', 14),
('art_163', 'Melyik művészeti mozgalom vezéralakja Andy Warhol?', '[{"key":"A","text":"Pop art","correct":true},{"key":"B","text":"Op art","correct":false},{"key":"C","text":"Dadaizmus","correct":false}]', '[60,20,20]', 'A', 'mixed', 14),
('art_164', 'Ki írta a "Büszkeség és balítélet" regényt?', '[{"key":"A","text":"Jane Austen","correct":true},{"key":"B","text":"Charlotte Brontë","correct":false},{"key":"C","text":"Emily Brontë","correct":false}]', '[60,25,15]', 'A', 'mixed', 14),
('art_165', 'Melyik festő alkotta a "Guernica" című művet?', '[{"key":"A","text":"Salvador Dalí","correct":false},{"key":"B","text":"Pablo Picasso","correct":true},{"key":"C","text":"Joan Miró","correct":false}]', '[20,60,20]', 'B', 'mixed', 14),
('art_166', 'Ki írta az "Anna Karenina" című regényt?', '[{"key":"A","text":"Lev Tolsztoj","correct":true},{"key":"B","text":"Anton Csehov","correct":false},{"key":"C","text":"Makszim Gorkij","correct":false}]', '[60,20,20]', 'A', 'mixed', 14),
('art_167', 'Melyik városban található a Sixtus-kápolna?', '[{"key":"A","text":"Róma","correct":false},{"key":"B","text":"Vatikán","correct":true},{"key":"C","text":"Firenze","correct":false}]', '[25,55,20]', 'B', 'mixed', 14),
('art_168', 'Ki írta a "Rómeó és Júlia" tragédiát?', '[{"key":"A","text":"William Shakespeare","correct":true},{"key":"B","text":"Molière","correct":false},{"key":"C","text":"Oscar Wilde","correct":false}]', '[70,15,15]', 'A', 'mixed', 14),
('art_169', 'Melyik festészeti technikát találta fel Leonardo da Vinci?', '[{"key":"A","text":"Sfumato","correct":true},{"key":"B","text":"Pontillizmus","correct":false},{"key":"C","text":"Chiaroscuro","correct":false}]', '[50,25,25]', 'A', 'mixed', 14),
('art_170', 'Ki írta a "Don Quijote" című regényt?', '[{"key":"A","text":"Miguel de Cervantes","correct":true},{"key":"B","text":"Federico García Lorca","correct":false},{"key":"C","text":"Gabriel García Márquez","correct":false}]', '[60,20,20]', 'A', 'mixed', 14),
('art_171', 'Melyik holland festő alkotott a 17. században?', '[{"key":"A","text":"Vermeer","correct":true},{"key":"B","text":"Van Gogh","correct":false},{"key":"C","text":"Mondrian","correct":false}]', '[55,25,20]', 'A', 'mixed', 14),
('art_172', 'Ki írta "Az Odüsszeia" eposz második felét?', '[{"key":"A","text":"Homérosz","correct":true},{"key":"B","text":"Vergilius","correct":false},{"key":"C","text":"Szophoklész","correct":false}]', '[60,20,20]', 'A', 'mixed', 14),
('art_173', 'Melyik művész híressé vált "készítmény"-szobrokról?', '[{"key":"A","text":"Marcel Duchamp","correct":true},{"key":"B","text":"Constantin Brâncuși","correct":false},{"key":"C","text":"Auguste Rodin","correct":false}]', '[50,25,25]', 'A', 'mixed', 14),
('art_174', 'Ki írta a "Nyomorultak" című regényt?', '[{"key":"A","text":"Victor Hugo","correct":true},{"key":"B","text":"Alexandre Dumas","correct":false},{"key":"C","text":"Honoré de Balzac","correct":false}]', '[60,20,20]', 'A', 'mixed', 14),
('art_175', 'Melyik stílust képviseli Klimt arany korszaka?', '[{"key":"A","text":"Art Nouveau","correct":false},{"key":"B","text":"Szecesszió","correct":true},{"key":"C","text":"Art Deco","correct":false}]', '[25,50,25]', 'B', 'mixed', 14),
('art_176', 'Ki írta a "Metamorphoses" (Átváltozások) című művet?', '[{"key":"A","text":"Ovidius","correct":true},{"key":"B","text":"Horatius","correct":false},{"key":"C","text":"Catullus","correct":false}]', '[55,25,20]', 'A', 'mixed', 14),
('art_177', 'Melyik festő alkotott kék korszakban?', '[{"key":"A","text":"Henri Matisse","correct":false},{"key":"B","text":"Pablo Picasso","correct":true},{"key":"C","text":"Georges Braque","correct":false}]', '[20,60,20]', 'B', 'mixed', 14),
('art_178', 'Ki írta a "Szép új világ" című disztópiát?', '[{"key":"A","text":"George Orwell","correct":false},{"key":"B","text":"Aldous Huxley","correct":true},{"key":"C","text":"Philip K. Dick","correct":false}]', '[25,55,20]', 'B', 'mixed', 14),
('art_179', 'Melyik múzeum őrzi a Vénusz de Milo szobrot?', '[{"key":"A","text":"British Museum","correct":false},{"key":"B","text":"Louvre","correct":true},{"key":"C","text":"Vatikáni Múzeumok","correct":false}]', '[20,60,20]', 'B', 'mixed', 14),
('art_180', 'Ki írta "A dzsungel könyve" című művet?', '[{"key":"A","text":"Rudyard Kipling","correct":true},{"key":"B","text":"Robert Louis Stevenson","correct":false},{"key":"C","text":"H.G. Wells","correct":false}]', '[60,20,20]', 'A', 'mixed', 14),
('art_181', 'Melyik festészeti stílus atyja Kandinszkij?', '[{"key":"A","text":"Absztrakt művészet","correct":true},{"key":"B","text":"Kubizmus","correct":false},{"key":"C","text":"Futurizmus","correct":false}]', '[55,25,20]', 'A', 'mixed', 14),
('art_182', 'Ki írta a "Moby Dick" című regényt?', '[{"key":"A","text":"Herman Melville","correct":true},{"key":"B","text":"Jack London","correct":false},{"key":"C","text":"Mark Twain","correct":false}]', '[55,25,20]', 'A', 'mixed', 14),
('art_183', 'Melyik képzőművészeti irányzat a bauhaus?', '[{"key":"A","text":"Építészeti-design iskola","correct":true},{"key":"B","text":"Festészeti mozgalom","correct":false},{"key":"C","text":"Szobrászati stílus","correct":false}]', '[55,25,20]', 'A', 'mixed', 14),
('art_184', 'Ki írta a "Faust" című tragédiát?', '[{"key":"A","text":"Goethe","correct":true},{"key":"B","text":"Schiller","correct":false},{"key":"C","text":"Lessing","correct":false}]', '[60,25,15]', 'A', 'mixed', 14),
('art_185', 'Melyik festő híres a "Napraforgók" sorozatról?', '[{"key":"A","text":"Vincent van Gogh","correct":true},{"key":"B","text":"Claude Monet","correct":false},{"key":"C","text":"Paul Cézanne","correct":false}]', '[65,20,15]', 'A', 'mixed', 14),
('art_186', 'Ki írta a "Karamazov testvérek" című regényt?', '[{"key":"A","text":"Lev Tolsztoj","correct":false},{"key":"B","text":"Fjodor Dosztojevszkij","correct":true},{"key":"C","text":"Ivan Goncsarov","correct":false}]', '[25,55,20]', 'B', 'mixed', 14),
('art_187', 'Melyik városban van a Rijksmuseum?', '[{"key":"A","text":"Amszterdam","correct":true},{"key":"B","text":"Rotterdam","correct":false},{"key":"C","text":"Hága","correct":false}]', '[60,20,20]', 'A', 'mixed', 14),
('art_188', 'Ki írta a "Tom Sawyer kalandjai" című könyvet?', '[{"key":"A","text":"Mark Twain","correct":true},{"key":"B","text":"Ernest Hemingway","correct":false},{"key":"C","text":"F. Scott Fitzgerald","correct":false}]', '[65,20,15]', 'A', 'mixed', 14),
('art_189', 'Melyik művész alkotott "Campbell leveses doboz" művet?', '[{"key":"A","text":"Andy Warhol","correct":true},{"key":"B","text":"Roy Lichtenstein","correct":false},{"key":"C","text":"Jasper Johns","correct":false}]', '[60,20,20]', 'A', 'mixed', 14),
('art_190', 'Ki írta "A három testőr" című regényt?', '[{"key":"A","text":"Alexandre Dumas","correct":true},{"key":"B","text":"Victor Hugo","correct":false},{"key":"C","text":"Stendhal","correct":false}]', '[60,20,20]', 'A', 'mixed', 14),
('art_191', 'Melyik művészeti korszak Botticelli?', '[{"key":"A","text":"Reneszánsz","correct":true},{"key":"B","text":"Barokk","correct":false},{"key":"C","text":"Gótika","correct":false}]', '[60,20,20]', 'A', 'mixed', 14),
('art_192', 'Ki írta a "Frankenstein" című regényt?', '[{"key":"A","text":"Mary Shelley","correct":true},{"key":"B","text":"Bram Stoker","correct":false},{"key":"C","text":"Edgar Allan Poe","correct":false}]', '[55,25,20]', 'A', 'mixed', 14),
('art_193', 'Melyik festő ismert pointillista stílusáról?', '[{"key":"A","text":"Georges Seurat","correct":true},{"key":"B","text":"Pierre-Auguste Renoir","correct":false},{"key":"C","text":"Édouard Manet","correct":false}]', '[55,25,20]', 'A', 'mixed', 14),
('art_194', 'Ki írta a "Gyűrűk Ura" trilógiát?', '[{"key":"A","text":"J.R.R. Tolkien","correct":true},{"key":"B","text":"C.S. Lewis","correct":false},{"key":"C","text":"George R.R. Martin","correct":false}]', '[65,20,15]', 'A', 'mixed', 14),
('art_195', 'Melyik szobrász alkotása "A gondolkodó"?', '[{"key":"A","text":"Auguste Rodin","correct":true},{"key":"B","text":"Henry Moore","correct":false},{"key":"C","text":"Alberto Giacometti","correct":false}]', '[60,20,20]', 'A', 'mixed', 14),
('art_196', 'Ki írta az "Isteni színjáték" című művet?', '[{"key":"A","text":"Dante Alighieri","correct":true},{"key":"B","text":"Petrarca","correct":false},{"key":"C","text":"Boccaccio","correct":false}]', '[60,20,20]', 'A', 'mixed', 14),
('art_197', 'Melyik művészeti mozgalom az Op Art?', '[{"key":"A","text":"Optikai művészet","correct":true},{"key":"B","text":"Absztrakt expresszionizmus","correct":false},{"key":"C","text":"Minimalizmus","correct":false}]', '[55,25,20]', 'A', 'mixed', 14),
('art_198', 'Ki írta a "Drakula" című regényt?', '[{"key":"A","text":"Bram Stoker","correct":true},{"key":"B","text":"Mary Shelley","correct":false},{"key":"C","text":"H.P. Lovecraft","correct":false}]', '[65,20,15]', 'A', 'mixed', 14),
('art_199', 'Melyik festő alkotott kubista stílusban Braque mellett?', '[{"key":"A","text":"Henri Matisse","correct":false},{"key":"B","text":"Pablo Picasso","correct":true},{"key":"C","text":"Fernand Léger","correct":false}]', '[20,60,20]', 'B', 'mixed', 14),
('art_200', 'Ki írta a "Harry Potter" könyvsorozatot?', '[{"key":"A","text":"J.K. Rowling","correct":true},{"key":"B","text":"Stephenie Meyer","correct":false},{"key":"C","text":"Suzanne Collins","correct":false}]', '[70,15,15]', 'A', 'mixed', 14);

-- English translations for Topic 14
INSERT INTO question_translations (question_id, lang, question_text, answer_a, answer_b, answer_c) VALUES
('art_151', 'en', 'Who painted "The Starry Night"?', 'Claude Monet', 'Vincent van Gogh', 'Pablo Picasso'),
('art_152', 'en', 'Which author created the character Sherlock Holmes?', 'Arthur Conan Doyle', 'Agatha Christie', 'Edgar Allan Poe'),
('art_153', 'en', 'Where is the Mona Lisa located?', 'Uffizi Gallery', 'Louvre', 'Prado'),
('art_154', 'en', 'Who wrote the play "Hamlet"?', 'William Shakespeare', 'Christopher Marlowe', 'Ben Jonson'),
('art_155', 'en', 'Which art movement does Salvador Dalí represent?', 'Impressionism', 'Surrealism', 'Cubism'),
('art_156', 'en', 'Who wrote the novel "War and Peace"?', 'Leo Tolstoy', 'Fyodor Dostoevsky', 'Anton Chekhov'),
('art_157', 'en', 'Which artist created the statue of David?', 'Donatello', 'Michelangelo', 'Bernini'),
('art_158', 'en', 'Who wrote the dystopian novel "1984"?', 'George Orwell', 'Aldous Huxley', 'Ray Bradbury'),
('art_159', 'en', 'Which style characterizes Monet''s paintings?', 'Impressionism', 'Expressionism', 'Realism'),
('art_160', 'en', 'Who wrote the novel "Crime and Punishment"?', 'Leo Tolstoy', 'Fyodor Dostoevsky', 'Ivan Turgenev'),
('art_161', 'en', 'Which painter cut off his own ear?', 'Vincent van Gogh', 'Paul Gauguin', 'Edvard Munch'),
('art_162', 'en', 'Who wrote "The Little Prince"?', 'Antoine de Saint-Exupéry', 'Jules Verne', 'Victor Hugo'),
('art_163', 'en', 'Which art movement is Andy Warhol a leading figure of?', 'Pop Art', 'Op Art', 'Dadaism'),
('art_164', 'en', 'Who wrote "Pride and Prejudice"?', 'Jane Austen', 'Charlotte Brontë', 'Emily Brontë'),
('art_165', 'en', 'Which painter created "Guernica"?', 'Salvador Dalí', 'Pablo Picasso', 'Joan Miró'),
('art_166', 'en', 'Who wrote the novel "Anna Karenina"?', 'Leo Tolstoy', 'Anton Chekhov', 'Maxim Gorky'),
('art_167', 'en', 'In which city is the Sistine Chapel located?', 'Rome', 'Vatican City', 'Florence'),
('art_168', 'en', 'Who wrote the tragedy "Romeo and Juliet"?', 'William Shakespeare', 'Molière', 'Oscar Wilde'),
('art_169', 'en', 'Which painting technique did Leonardo da Vinci invent?', 'Sfumato', 'Pointillism', 'Chiaroscuro'),
('art_170', 'en', 'Who wrote the novel "Don Quixote"?', 'Miguel de Cervantes', 'Federico García Lorca', 'Gabriel García Márquez'),
('art_171', 'en', 'Which Dutch painter worked in the 17th century?', 'Vermeer', 'Van Gogh', 'Mondrian'),
('art_172', 'en', 'Who wrote the second half of "The Odyssey" epic?', 'Homer', 'Virgil', 'Sophocles'),
('art_173', 'en', 'Which artist became famous for "readymade" sculptures?', 'Marcel Duchamp', 'Constantin Brâncuși', 'Auguste Rodin'),
('art_174', 'en', 'Who wrote the novel "Les Misérables"?', 'Victor Hugo', 'Alexandre Dumas', 'Honoré de Balzac'),
('art_175', 'en', 'Which style represents Klimt''s golden period?', 'Art Nouveau', 'Secession', 'Art Deco'),
('art_176', 'en', 'Who wrote "Metamorphoses"?', 'Ovid', 'Horace', 'Catullus'),
('art_177', 'en', 'Which painter had a blue period?', 'Henri Matisse', 'Pablo Picasso', 'Georges Braque'),
('art_178', 'en', 'Who wrote the dystopia "Brave New World"?', 'George Orwell', 'Aldous Huxley', 'Philip K. Dick'),
('art_179', 'en', 'Which museum houses the Venus de Milo statue?', 'British Museum', 'Louvre', 'Vatican Museums'),
('art_180', 'en', 'Who wrote "The Jungle Book"?', 'Rudyard Kipling', 'Robert Louis Stevenson', 'H.G. Wells'),
('art_181', 'en', 'Which painting style is Kandinsky the father of?', 'Abstract art', 'Cubism', 'Futurism'),
('art_182', 'en', 'Who wrote the novel "Moby Dick"?', 'Herman Melville', 'Jack London', 'Mark Twain'),
('art_183', 'en', 'What type of movement is Bauhaus?', 'Architectural-design school', 'Painting movement', 'Sculptural style'),
('art_184', 'en', 'Who wrote the tragedy "Faust"?', 'Goethe', 'Schiller', 'Lessing'),
('art_185', 'en', 'Which painter is famous for the "Sunflowers" series?', 'Vincent van Gogh', 'Claude Monet', 'Paul Cézanne'),
('art_186', 'en', 'Who wrote the novel "The Brothers Karamazov"?', 'Leo Tolstoy', 'Fyodor Dostoevsky', 'Ivan Goncharov'),
('art_187', 'en', 'In which city is the Rijksmuseum?', 'Amsterdam', 'Rotterdam', 'The Hague'),
('art_188', 'en', 'Who wrote "The Adventures of Tom Sawyer"?', 'Mark Twain', 'Ernest Hemingway', 'F. Scott Fitzgerald'),
('art_189', 'en', 'Which artist created the "Campbell''s Soup Cans" artwork?', 'Andy Warhol', 'Roy Lichtenstein', 'Jasper Johns'),
('art_190', 'en', 'Who wrote "The Three Musketeers"?', 'Alexandre Dumas', 'Victor Hugo', 'Stendhal'),
('art_191', 'en', 'Which art period does Botticelli belong to?', 'Renaissance', 'Baroque', 'Gothic'),
('art_192', 'en', 'Who wrote the novel "Frankenstein"?', 'Mary Shelley', 'Bram Stoker', 'Edgar Allan Poe'),
('art_193', 'en', 'Which painter is known for pointillist style?', 'Georges Seurat', 'Pierre-Auguste Renoir', 'Édouard Manet'),
('art_194', 'en', 'Who wrote "The Lord of the Rings" trilogy?', 'J.R.R. Tolkien', 'C.S. Lewis', 'George R.R. Martin'),
('art_195', 'en', 'Which sculptor created "The Thinker"?', 'Auguste Rodin', 'Henry Moore', 'Alberto Giacometti'),
('art_196', 'en', 'Who wrote "The Divine Comedy"?', 'Dante Alighieri', 'Petrarch', 'Boccaccio'),
('art_197', 'en', 'What type of movement is Op Art?', 'Optical art', 'Abstract Expressionism', 'Minimalism'),
('art_198', 'en', 'Who wrote the novel "Dracula"?', 'Bram Stoker', 'Mary Shelley', 'H.P. Lovecraft'),
('art_199', 'en', 'Which painter worked in cubist style alongside Braque?', 'Henri Matisse', 'Pablo Picasso', 'Fernand Léger'),
('art_200', 'en', 'Who wrote the "Harry Potter" book series?', 'J.K. Rowling', 'Stephenie Meyer', 'Suzanne Collins');