
-- Topic 23: Innováció - 50 új kérdés
INSERT INTO public.questions (id, question, answers, audience, third, source_category, topic_id) VALUES
('innov_151', 'Ki találta fel az izzólámpát?', '[{"key":"A","text":"Thomas Edison","correct":true},{"key":"B","text":"Nikola Tesla","correct":false},{"key":"C","text":"Alexander Graham Bell","correct":false}]', '{"A":85,"B":10,"C":5}', 'A', 'mixed', 23),
('innov_152', 'Melyik évben repültek először a Wright fivérek?', '[{"key":"A","text":"1903","correct":true},{"key":"B","text":"1899","correct":false},{"key":"C","text":"1910","correct":false}]', '{"A":70,"B":20,"C":10}', 'A', 'mixed', 23),
('innov_153', 'Ki találta fel a telefont?', '[{"key":"A","text":"Alexander Graham Bell","correct":true},{"key":"B","text":"Thomas Edison","correct":false},{"key":"C","text":"Nikola Tesla","correct":false}]', '{"A":85,"B":10,"C":5}', 'A', 'mixed', 23),
('innov_154', 'Melyik országban találták fel a papírt?', '[{"key":"A","text":"Kína","correct":true},{"key":"B","text":"Egyiptom","correct":false},{"key":"C","text":"India","correct":false}]', '{"A":75,"B":15,"C":10}', 'A', 'mixed', 23),
('innov_155', 'Ki fejlesztette ki az első vakcínát?', '[{"key":"A","text":"Edward Jenner","correct":true},{"key":"B","text":"Louis Pasteur","correct":false},{"key":"C","text":"Robert Koch","correct":false}]', '{"A":60,"B":30,"C":10}', 'A', 'mixed', 23),
('innov_156', 'Melyik évben szabadalmaztatta Gutenberg a nyomdát?', '[{"key":"A","text":"1440 körül","correct":true},{"key":"B","text":"1500 körül","correct":false},{"key":"C","text":"1380 körül","correct":false}]', '{"A":65,"B":25,"C":10}', 'A', 'mixed', 23),
('innov_157', 'Ki találta fel a dinamitot?', '[{"key":"A","text":"Alfred Nobel","correct":true},{"key":"B","text":"Albert Einstein","correct":false},{"key":"C","text":"Robert Oppenheimer","correct":false}]', '{"A":80,"B":15,"C":5}', 'A', 'mixed', 23),
('innov_158', 'Melyik találmány forradalmasította a textilipart?', '[{"key":"A","text":"Szövőgép","correct":true},{"key":"B","text":"Gőzgép","correct":false},{"key":"C","text":"Fonógép","correct":false}]', '{"A":55,"B":30,"C":15}', 'A', 'mixed', 23),
('innov_159', 'Ki találta fel a penicillint?', '[{"key":"A","text":"Alexander Fleming","correct":true},{"key":"B","text":"Louis Pasteur","correct":false},{"key":"C","text":"Joseph Lister","correct":false}]', '{"A":80,"B":15,"C":5}', 'A', 'mixed', 23),
('innov_160', 'Melyik évben indult az első gőzmozdony?', '[{"key":"A","text":"1804","correct":true},{"key":"B","text":"1825","correct":false},{"key":"C","text":"1850","correct":false}]', '{"A":50,"B":35,"C":15}', 'A', 'mixed', 23),
('innov_161', 'Ki találta fel a rádióhullámokat?', '[{"key":"A","text":"Guglielmo Marconi","correct":true},{"key":"B","text":"Nikola Tesla","correct":false},{"key":"C","text":"Heinrich Hertz","correct":false}]', '{"A":55,"B":30,"C":15}', 'A', 'mixed', 23),
('innov_162', 'Melyik találmány tette lehetővé a tömegtermelést?', '[{"key":"A","text":"Futószalag","correct":true},{"key":"B","text":"Gőzgép","correct":false},{"key":"C","text":"Elektromos motor","correct":false}]', '{"A":70,"B":20,"C":10}', 'A', 'mixed', 23),
('innov_163', 'Ki találta fel a villanyáramot váltóáramként terjesztő rendszert?', '[{"key":"A","text":"Nikola Tesla","correct":true},{"key":"B","text":"Thomas Edison","correct":false},{"key":"C","text":"George Westinghouse","correct":false}]', '{"A":70,"B":20,"C":10}', 'A', 'mixed', 23),
('innov_164', 'Melyik országban találták fel az iránytűt?', '[{"key":"A","text":"Kína","correct":true},{"key":"B","text":"Görögország","correct":false},{"key":"C","text":"Arábia","correct":false}]', '{"A":75,"B":15,"C":10}', 'A', 'mixed', 23),
('innov_165', 'Ki fejlesztette ki a relativitáselméletet?', '[{"key":"A","text":"Albert Einstein","correct":true},{"key":"B","text":"Isaac Newton","correct":false},{"key":"C","text":"Stephen Hawking","correct":false}]', '{"A":90,"B":5,"C":5}', 'A', 'mixed', 23),
('innov_166', 'Melyik évben szabadalmaztatták az első autót?', '[{"key":"A","text":"1886","correct":true},{"key":"B","text":"1900","correct":false},{"key":"C","text":"1875","correct":false}]', '{"A":60,"B":25,"C":15}', 'A', 'mixed', 23),
('innov_167', 'Ki találta fel a léghajót?', '[{"key":"A","text":"Ferdinand von Zeppelin","correct":true},{"key":"B","text":"Montgolfier fivérek","correct":false},{"key":"C","text":"Santos-Dumont","correct":false}]', '{"A":65,"B":25,"C":10}', 'A', 'mixed', 23),
('innov_168', 'Melyik találmány forradalmasította a kommunikációt a 19. században?', '[{"key":"A","text":"Távíró","correct":true},{"key":"B","text":"Telefon","correct":false},{"key":"C","text":"Rádió","correct":false}]', '{"A":60,"B":30,"C":10}', 'A', 'mixed', 23),
('innov_169', 'Ki találta fel a mikroszkópot?', '[{"key":"A","text":"Zacharias Janssen","correct":true},{"key":"B","text":"Galileo Galilei","correct":false},{"key":"C","text":"Anton van Leeuwenhoek","correct":false}]', '{"A":50,"B":30,"C":20}', 'A', 'mixed', 23),
('innov_170', 'Melyik évben szabadalmaztatták a fonográfot?', '[{"key":"A","text":"1877","correct":true},{"key":"B","text":"1890","correct":false},{"key":"C","text":"1865","correct":false}]', '{"A":55,"B":30,"C":15}', 'A', 'mixed', 23),
('innov_171', 'Ki találta fel a gőzgépet?', '[{"key":"A","text":"James Watt","correct":true},{"key":"B","text":"Thomas Newcomen","correct":false},{"key":"C","text":"Richard Trevithick","correct":false}]', '{"A":75,"B":15,"C":10}', 'A', 'mixed', 23),
('innov_172', 'Melyik találmány vezetett az ipari forradalomhoz?', '[{"key":"A","text":"Gőzgép","correct":true},{"key":"B","text":"Elektromos áram","correct":false},{"key":"C","text":"Belső égésű motor","correct":false}]', '{"A":80,"B":10,"C":10}', 'A', 'mixed', 23),
('innov_173', 'Ki találta fel a röntgensugárzást?', '[{"key":"A","text":"Wilhelm Röntgen","correct":true},{"key":"B","text":"Marie Curie","correct":false},{"key":"C","text":"Ernest Rutherford","correct":false}]', '{"A":80,"B":15,"C":5}', 'A', 'mixed', 23),
('innov_174', 'Melyik országban találták fel a lőport?', '[{"key":"A","text":"Kína","correct":true},{"key":"B","text":"Perzsia","correct":false},{"key":"C","text":"India","correct":false}]', '{"A":80,"B":10,"C":10}', 'A', 'mixed', 23),
('innov_175', 'Ki fejlesztette ki az első működő számítógépet?', '[{"key":"A","text":"Charles Babbage","correct":true},{"key":"B","text":"Alan Turing","correct":false},{"key":"C","text":"John von Neumann","correct":false}]', '{"A":55,"B":30,"C":15}', 'A', 'mixed', 23),
('innov_176', 'Melyik évben találták fel a cipzárt?', '[{"key":"A","text":"1893","correct":true},{"key":"B","text":"1905","correct":false},{"key":"C","text":"1880","correct":false}]', '{"A":50,"B":30,"C":20}', 'A', 'mixed', 23),
('innov_177', 'Ki találta fel a televíziót?', '[{"key":"A","text":"Philo Farnsworth","correct":true},{"key":"B","text":"John Logie Baird","correct":false},{"key":"C","text":"Guglielmo Marconi","correct":false}]', '{"A":50,"B":35,"C":15}', 'A', 'mixed', 23),
('innov_178', 'Melyik találmány tette lehetővé a modern sebészetet?', '[{"key":"A","text":"Érzéstelenítés","correct":true},{"key":"B","text":"Antibiotikumok","correct":false},{"key":"C","text":"Sterilizálás","correct":false}]', '{"A":60,"B":25,"C":15}', 'A', 'mixed', 23),
('innov_179', 'Ki találta fel a lézernyomtatót?', '[{"key":"A","text":"Gary Starkweather","correct":true},{"key":"B","text":"Chester Carlson","correct":false},{"key":"C","text":"Johannes Gutenberg","correct":false}]', '{"A":45,"B":35,"C":20}', 'A', 'mixed', 23),
('innov_180', 'Melyik évben repült először űrbe ember?', '[{"key":"A","text":"1961","correct":true},{"key":"B","text":"1957","correct":false},{"key":"C","text":"1969","correct":false}]', '{"A":70,"B":20,"C":10}', 'A', 'mixed', 23),
('innov_181', 'Ki találta fel a nylon anyagot?', '[{"key":"A","text":"Wallace Carothers","correct":true},{"key":"B","text":"Roy Plunkett","correct":false},{"key":"C","text":"Leo Baekeland","correct":false}]', '{"A":45,"B":35,"C":20}', 'A', 'mixed', 23),
('innov_182', 'Melyik találmány alapja a modern számítástechnika?', '[{"key":"A","text":"Tranzisztor","correct":true},{"key":"B","text":"Elektroncsövek","correct":false},{"key":"C","text":"Relék","correct":false}]', '{"A":70,"B":20,"C":10}', 'A', 'mixed', 23),
('innov_183', 'Ki találta fel a szintetikus műanyagot?', '[{"key":"A","text":"Leo Baekeland","correct":true},{"key":"B","text":"Wallace Carothers","correct":false},{"key":"C","text":"Stephanie Kwolek","correct":false}]', '{"A":50,"B":30,"C":20}', 'A', 'mixed', 23),
('innov_184', 'Melyik évben szabadalmaztatták a golyóstollat?', '[{"key":"A","text":"1938","correct":true},{"key":"B","text":"1950","correct":false},{"key":"C","text":"1925","correct":false}]', '{"A":55,"B":30,"C":15}', 'A', 'mixed', 23),
('innov_185', 'Ki fejlesztette ki a 3D nyomtatást?', '[{"key":"A","text":"Chuck Hull","correct":true},{"key":"B","text":"Hideo Kodama","correct":false},{"key":"C","text":"Scott Crump","correct":false}]', '{"A":50,"B":30,"C":20}', 'A', 'mixed', 23),
('innov_186', 'Melyik találmány vezetett a zöld forradalomhoz a mezőgazdaságban?', '[{"key":"A","text":"Magas hozamú vetőmagok","correct":true},{"key":"B","text":"Traktor","correct":false},{"key":"C","text":"Öntözőrendszerek","correct":false}]', '{"A":55,"B":30,"C":15}', 'A', 'mixed', 23),
('innov_187', 'Ki találta fel az insulin terápiát?', '[{"key":"A","text":"Frederick Banting","correct":true},{"key":"B","text":"Jonas Salk","correct":false},{"key":"C","text":"Alexander Fleming","correct":false}]', '{"A":55,"B":30,"C":15}', 'A', 'mixed', 23),
('innov_188', 'Melyik évben szabadalmaztatták a hűtőszekrényt?', '[{"key":"A","text":"1913","correct":true},{"key":"B","text":"1930","correct":false},{"key":"C","text":"1895","correct":false}]', '{"A":50,"B":30,"C":20}', 'A', 'mixed', 23),
('innov_189', 'Ki találta fel a polaroid kamerát?', '[{"key":"A","text":"Edwin Land","correct":true},{"key":"B","text":"George Eastman","correct":false},{"key":"C","text":"Louis Daguerre","correct":false}]', '{"A":55,"B":30,"C":15}', 'A', 'mixed', 23),
('innov_190', 'Melyik találmány tette lehetővé a modern kommunikációt?', '[{"key":"A","text":"Optikai szál","correct":true},{"key":"B","text":"Rézvezeték","correct":false},{"key":"C","text":"Műhold","correct":false}]', '{"A":60,"B":25,"C":15}', 'A', 'mixed', 23),
('innov_191', 'Ki fejlesztette ki a CRISPR génszerkesztést?', '[{"key":"A","text":"Jennifer Doudna és Emmanuelle Charpentier","correct":true},{"key":"B","text":"James Watson","correct":false},{"key":"C","text":"Francis Crick","correct":false}]', '{"A":60,"B":25,"C":15}', 'A', 'mixed', 23),
('innov_192', 'Melyik évben találták fel a számológépet?', '[{"key":"A","text":"1642","correct":true},{"key":"B","text":"1700","correct":false},{"key":"C","text":"1580","correct":false}]', '{"A":55,"B":30,"C":15}', 'A', 'mixed', 23),
('innov_193', 'Ki találta fel a mosógépet?', '[{"key":"A","text":"Jacob Christian Schäffer","correct":true},{"key":"B","text":"James King","correct":false},{"key":"C","text":"Alva Fisher","correct":false}]', '{"A":40,"B":35,"C":25}', 'A', 'mixed', 23),
('innov_194', 'Melyik találmány forradalmasította az élelmiszer-tartósítást?', '[{"key":"A","text":"Konzervdoboz","correct":true},{"key":"B","text":"Hűtőszekrény","correct":false},{"key":"C","text":"Pasztörizálás","correct":false}]', '{"A":55,"B":30,"C":15}', 'A', 'mixed', 23),
('innov_195', 'Ki fejlesztette ki az első szív-tüdő gépet?', '[{"key":"A","text":"John Heysham Gibbon","correct":true},{"key":"B","text":"Christiaan Barnard","correct":false},{"key":"C","text":"Willem Kolff","correct":false}]', '{"A":45,"B":35,"C":20}', 'A', 'mixed', 23),
('innov_196', 'Melyik évben találták fel a CD-t?', '[{"key":"A","text":"1982","correct":true},{"key":"B","text":"1975","correct":false},{"key":"C","text":"1990","correct":false}]', '{"A":60,"B":25,"C":15}', 'A', 'mixed', 23),
('innov_197', 'Ki találta fel a biztonságos liftet?', '[{"key":"A","text":"Elisha Otis","correct":true},{"key":"B","text":"Werner von Siemens","correct":false},{"key":"C","text":"Gustave Eiffel","correct":false}]', '{"A":55,"B":30,"C":15}', 'A', 'mixed', 23),
('innov_198', 'Melyik találmány alapozta meg a modern gyógyszeripart?', '[{"key":"A","text":"Szintetikus gyógyszerek","correct":true},{"key":"B","text":"Antibiotikumok","correct":false},{"key":"C","text":"Vakcinák","correct":false}]', '{"A":50,"B":35,"C":15}', 'A', 'mixed', 23),
('innov_199', 'Ki fejlesztette ki a bluetooth technológiát?', '[{"key":"A","text":"Ericsson","correct":true},{"key":"B","text":"Nokia","correct":false},{"key":"C","text":"Motorola","correct":false}]', '{"A":55,"B":30,"C":15}', 'A', 'mixed', 23),
('innov_200', 'Melyik évben szabadalmaztatták a porszívót?', '[{"key":"A","text":"1901","correct":true},{"key":"B","text":"1920","correct":false},{"key":"C","text":"1885","correct":false}]', '{"A":50,"B":35,"C":15}', 'A', 'mixed', 23);

-- Topic 23 translations
INSERT INTO public.question_translations (question_id, lang, question_text, answer_a, answer_b, answer_c) VALUES
('innov_151', 'en', 'Who invented the light bulb?', 'Thomas Edison', 'Nikola Tesla', 'Alexander Graham Bell'),
('innov_152', 'en', 'In which year did the Wright brothers first fly?', '1903', '1899', '1910'),
('innov_153', 'en', 'Who invented the telephone?', 'Alexander Graham Bell', 'Thomas Edison', 'Nikola Tesla'),
('innov_154', 'en', 'In which country was paper invented?', 'China', 'Egypt', 'India'),
('innov_155', 'en', 'Who developed the first vaccine?', 'Edward Jenner', 'Louis Pasteur', 'Robert Koch'),
('innov_156', 'en', 'In which year did Gutenberg patent the printing press?', 'Around 1440', 'Around 1500', 'Around 1380'),
('innov_157', 'en', 'Who invented dynamite?', 'Alfred Nobel', 'Albert Einstein', 'Robert Oppenheimer'),
('innov_158', 'en', 'Which invention revolutionized the textile industry?', 'Power loom', 'Steam engine', 'Spinning machine'),
('innov_159', 'en', 'Who discovered penicillin?', 'Alexander Fleming', 'Louis Pasteur', 'Joseph Lister'),
('innov_160', 'en', 'In which year did the first steam locomotive run?', '1804', '1825', '1850'),
('innov_161', 'en', 'Who invented radio waves?', 'Guglielmo Marconi', 'Nikola Tesla', 'Heinrich Hertz'),
('innov_162', 'en', 'Which invention enabled mass production?', 'Assembly line', 'Steam engine', 'Electric motor'),
('innov_163', 'en', 'Who invented the alternating current power distribution system?', 'Nikola Tesla', 'Thomas Edison', 'George Westinghouse'),
('innov_164', 'en', 'In which country was the compass invented?', 'China', 'Greece', 'Arabia'),
('innov_165', 'en', 'Who developed the theory of relativity?', 'Albert Einstein', 'Isaac Newton', 'Stephen Hawking'),
('innov_166', 'en', 'In which year was the first car patented?', '1886', '1900', '1875'),
('innov_167', 'en', 'Who invented the airship?', 'Ferdinand von Zeppelin', 'Montgolfier brothers', 'Santos-Dumont'),
('innov_168', 'en', 'Which invention revolutionized communication in the 19th century?', 'Telegraph', 'Telephone', 'Radio'),
('innov_169', 'en', 'Who invented the microscope?', 'Zacharias Janssen', 'Galileo Galilei', 'Anton van Leeuwenhoek'),
('innov_170', 'en', 'In which year was the phonograph patented?', '1877', '1890', '1865'),
('innov_171', 'en', 'Who invented the steam engine?', 'James Watt', 'Thomas Newcomen', 'Richard Trevithick'),
('innov_172', 'en', 'Which invention led to the Industrial Revolution?', 'Steam engine', 'Electricity', 'Internal combustion engine'),
('innov_173', 'en', 'Who discovered X-ray radiation?', 'Wilhelm Röntgen', 'Marie Curie', 'Ernest Rutherford'),
('innov_174', 'en', 'In which country was gunpowder invented?', 'China', 'Persia', 'India'),
('innov_175', 'en', 'Who developed the first working computer?', 'Charles Babbage', 'Alan Turing', 'John von Neumann'),
('innov_176', 'en', 'In which year was the zipper invented?', '1893', '1905', '1880'),
('innov_177', 'en', 'Who invented the television?', 'Philo Farnsworth', 'John Logie Baird', 'Guglielmo Marconi'),
('innov_178', 'en', 'Which invention enabled modern surgery?', 'Anesthesia', 'Antibiotics', 'Sterilization'),
('innov_179', 'en', 'Who invented the laser printer?', 'Gary Starkweather', 'Chester Carlson', 'Johannes Gutenberg'),
('innov_180', 'en', 'In which year did a human first fly to space?', '1961', '1957', '1969'),
('innov_181', 'en', 'Who invented nylon?', 'Wallace Carothers', 'Roy Plunkett', 'Leo Baekeland'),
('innov_182', 'en', 'Which invention is the basis of modern computing?', 'Transistor', 'Vacuum tubes', 'Relays'),
('innov_183', 'en', 'Who invented synthetic plastic?', 'Leo Baekeland', 'Wallace Carothers', 'Stephanie Kwolek'),
('innov_184', 'en', 'In which year was the ballpoint pen patented?', '1938', '1950', '1925'),
('innov_185', 'en', 'Who developed 3D printing?', 'Chuck Hull', 'Hideo Kodama', 'Scott Crump'),
('innov_186', 'en', 'Which invention led to the Green Revolution in agriculture?', 'High-yield seeds', 'Tractor', 'Irrigation systems'),
('innov_187', 'en', 'Who discovered insulin therapy?', 'Frederick Banting', 'Jonas Salk', 'Alexander Fleming'),
('innov_188', 'en', 'In which year was the refrigerator patented?', '1913', '1930', '1895'),
('innov_189', 'en', 'Who invented the Polaroid camera?', 'Edwin Land', 'George Eastman', 'Louis Daguerre'),
('innov_190', 'en', 'Which invention enabled modern communication?', 'Optical fiber', 'Copper wire', 'Satellite'),
('innov_191', 'en', 'Who developed CRISPR gene editing?', 'Jennifer Doudna and Emmanuelle Charpentier', 'James Watson', 'Francis Crick'),
('innov_192', 'en', 'In which year was the calculator invented?', '1642', '1700', '1580'),
('innov_193', 'en', 'Who invented the washing machine?', 'Jacob Christian Schäffer', 'James King', 'Alva Fisher'),
('innov_194', 'en', 'Which invention revolutionized food preservation?', 'Canning', 'Refrigerator', 'Pasteurization'),
('innov_195', 'en', 'Who developed the first heart-lung machine?', 'John Heysham Gibbon', 'Christiaan Barnard', 'Willem Kolff'),
('innov_196', 'en', 'In which year was the CD invented?', '1982', '1975', '1990'),
('innov_197', 'en', 'Who invented the safety elevator?', 'Elisha Otis', 'Werner von Siemens', 'Gustave Eiffel'),
('innov_198', 'en', 'Which invention founded the modern pharmaceutical industry?', 'Synthetic drugs', 'Antibiotics', 'Vaccines'),
('innov_199', 'en', 'Who developed Bluetooth technology?', 'Ericsson', 'Nokia', 'Motorola'),
('innov_200', 'en', 'In which year was the vacuum cleaner patented?', '1901', '1920', '1885');
