
-- Topic 26: Élelmiszer és gasztronómia - 50 új kérdés
INSERT INTO public.questions (id, question, answers, audience, third, source_category, topic_id) VALUES
('etel_151', 'Melyik országból származik a sushi?', '[{"key":"A","text":"Japán","correct":true},{"key":"B","text":"Kína","correct":false},{"key":"C","text":"Korea","correct":false}]', '{"A":90,"B":5,"C":5}', 'A', 'mixed', 26),
('etel_152', 'Mi a francia konyha egyik legismertebb mártása?', '[{"key":"A","text":"Béarnaise","correct":true},{"key":"B","text":"Marinara","correct":false},{"key":"C","text":"Teriyaki","correct":false}]', '{"A":70,"B":20,"C":10}', 'A', 'mixed', 26),
('etel_153', 'Melyik országból származik a pizza?', '[{"key":"A","text":"Olaszország","correct":true},{"key":"B","text":"Görögország","correct":false},{"key":"C","text":"Spanyolország","correct":false}]', '{"A":95,"B":3,"C":2}', 'A', 'mixed', 26),
('etel_154', 'Mi a wasabi alapanyaga?', '[{"key":"A","text":"Wasabi retek","correct":true},{"key":"B","text":"Zöld paprika","correct":false},{"key":"C","text":"Avokádó","correct":false}]', '{"A":65,"B":20,"C":15}', 'A', 'mixed', 26),
('etel_155', 'Melyik országból származik a gulyás?', '[{"key":"A","text":"Magyarország","correct":true},{"key":"B","text":"Ausztria","correct":false},{"key":"C","text":"Csehország","correct":false}]', '{"A":90,"B":5,"C":5}', 'A', 'mixed', 26),
('etel_156', 'Mi a paella fő összetevője?', '[{"key":"A","text":"Rizs","correct":true},{"key":"B","text":"Tészta","correct":false},{"key":"C","text":"Kuszkusz","correct":false}]', '{"A":80,"B":10,"C":10}', 'A', 'mixed', 26),
('etel_157', 'Melyik országból származik a croissant?', '[{"key":"A","text":"Ausztria (később Franciaország)","correct":true},{"key":"B","text":"Franciaország","correct":false},{"key":"C","text":"Belgium","correct":false}]', '{"A":45,"B":45,"C":10}', 'A', 'mixed', 26),
('etel_158', 'Mi az umami íz forrása?', '[{"key":"A","text":"Glutamát","correct":true},{"key":"B","text":"Cukor","correct":false},{"key":"C","text":"Só","correct":false}]', '{"A":65,"B":20,"C":15}', 'A', 'mixed', 26),
('etel_159', 'Melyik országból származik a pad thai?', '[{"key":"A","text":"Thaiföld","correct":true},{"key":"B","text":"Vietnam","correct":false},{"key":"C","text":"Indonézia","correct":false}]', '{"A":85,"B":10,"C":5}', 'A', 'mixed', 26),
('etel_160', 'Mi a miso alapanyaga?', '[{"key":"A","text":"Fermentált szójabab","correct":true},{"key":"B","text":"Rizs","correct":false},{"key":"C","text":"Tengeri alga","correct":false}]', '{"A":70,"B":20,"C":10}', 'A', 'mixed', 26),
('etel_161', 'Melyik országból származik a falafel?', '[{"key":"A","text":"Közel-Kelet (Egyiptom/Levante)","correct":true},{"key":"B","text":"India","correct":false},{"key":"C","text":"Törökország","correct":false}]', '{"A":65,"B":20,"C":15}', 'A', 'mixed', 26),
('etel_162', 'Mi a csokoládé fő összetevője?', '[{"key":"A","text":"Kakaóbab","correct":true},{"key":"B","text":"Kávébab","correct":false},{"key":"C","text":"Mogyoró","correct":false}]', '{"A":90,"B":5,"C":5}', 'A', 'mixed', 26),
('etel_163', 'Melyik országból származik a tacos?', '[{"key":"A","text":"Mexikó","correct":true},{"key":"B","text":"Spanyolország","correct":false},{"key":"C","text":"Peru","correct":false}]', '{"A":90,"B":5,"C":5}', 'A', 'mixed', 26),
('etel_164', 'Mi a parmezán sajt eredeti neve?', '[{"key":"A","text":"Parmigiano-Reggiano","correct":true},{"key":"B","text":"Grana Padano","correct":false},{"key":"C","text":"Pecorino Romano","correct":false}]', '{"A":70,"B":20,"C":10}', 'A', 'mixed', 26),
('etel_165', 'Melyik országból származik a kimchi?', '[{"key":"A","text":"Korea","correct":true},{"key":"B","text":"Japán","correct":false},{"key":"C","text":"Kína","correct":false}]', '{"A":80,"B":10,"C":10}', 'A', 'mixed', 26),
('etel_166', 'Mi a champagne különlegessége?', '[{"key":"A","text":"Csak a Champagne régióból származhat","correct":true},{"key":"B","text":"Különleges szőlőfajtából készül","correct":false},{"key":"C","text":"Mindig édes","correct":false}]', '{"A":75,"B":15,"C":10}', 'A', 'mixed', 26),
('etel_167', 'Melyik országból származik a curry?', '[{"key":"A","text":"India","correct":true},{"key":"B","text":"Thaiföld","correct":false},{"key":"C","text":"Malajzia","correct":false}]', '{"A":80,"B":15,"C":5}', 'A', 'mixed', 26),
('etel_168', 'Mi a foie gras alapanyaga?', '[{"key":"A","text":"Libamáj vagy kacsemáj","correct":true},{"key":"B","text":"Csirkemáj","correct":false},{"key":"C","text":"Sertésmáj","correct":false}]', '{"A":75,"B":15,"C":10}', 'A', 'mixed', 26),
('etel_169', 'Melyik országból származik a tiramisu?', '[{"key":"A","text":"Olaszország","correct":true},{"key":"B","text":"Franciaország","correct":false},{"key":"C","text":"Spanyolország","correct":false}]', '{"A":90,"B":5,"C":5}', 'A', 'mixed', 26),
('etel_170', 'Mi a szójaszósz fermentációs ideje?', '[{"key":"A","text":"Hónapok-évek","correct":true},{"key":"B","text":"Napok","correct":false},{"key":"C","text":"Órák","correct":false}]', '{"A":65,"B":25,"C":10}', 'A', 'mixed', 26),
('etel_171', 'Melyik országból származik a baklava?', '[{"key":"A","text":"Törökország/Görögország","correct":true},{"key":"B","text":"Libanon","correct":false},{"key":"C","text":"Irán","correct":false}]', '{"A":65,"B":20,"C":15}', 'A', 'mixed', 26),
('etel_172', 'Mi a kávé legdrágább fajtája?', '[{"key":"A","text":"Kopi Luwak","correct":true},{"key":"B","text":"Blue Mountain","correct":false},{"key":"C","text":"Geisha","correct":false}]', '{"A":70,"B":20,"C":10}', 'A', 'mixed', 26),
('etel_173', 'Melyik országból származik a pho leves?', '[{"key":"A","text":"Vietnam","correct":true},{"key":"B","text":"Thaiföld","correct":false},{"key":"C","text":"Kína","correct":false}]', '{"A":80,"B":15,"C":5}', 'A', 'mixed', 26),
('etel_174', 'Mi a szarvasgomba különlegessége?', '[{"key":"A","text":"Földalatti gomba, kutyákkal/disznókkal keresik","correct":true},{"key":"B","text":"Csak hegyvidéken terem","correct":false},{"key":"C","text":"Mérges, de főzve ehető","correct":false}]', '{"A":75,"B":15,"C":10}', 'A', 'mixed', 26),
('etel_175', 'Melyik országból származik a ceviche?', '[{"key":"A","text":"Peru","correct":true},{"key":"B","text":"Mexikó","correct":false},{"key":"C","text":"Chile","correct":false}]', '{"A":65,"B":25,"C":10}', 'A', 'mixed', 26),
('etel_176', 'Mi a legdrágább fűszer a világon?', '[{"key":"A","text":"Sáfrány","correct":true},{"key":"B","text":"Vanília","correct":false},{"key":"C","text":"Kardamom","correct":false}]', '{"A":80,"B":15,"C":5}', 'A', 'mixed', 26),
('etel_177', 'Melyik országból származik a rendang?', '[{"key":"A","text":"Indonézia","correct":true},{"key":"B","text":"Malajzia","correct":false},{"key":"C","text":"Szingapúr","correct":false}]', '{"A":55,"B":30,"C":15}', 'A', 'mixed', 26),
('etel_178', 'Mi a kobe marhahús különlegessége?', '[{"key":"A","text":"A Kobe régióból származó wagyu","correct":true},{"key":"B","text":"Speciális takarmányozás","correct":false},{"key":"C","text":"Csak fiatal állatok","correct":false}]', '{"A":65,"B":25,"C":10}', 'A', 'mixed', 26),
('etel_179', 'Melyik országból származik a döner kebab?', '[{"key":"A","text":"Törökország","correct":true},{"key":"B","text":"Görögország","correct":false},{"key":"C","text":"Libanon","correct":false}]', '{"A":80,"B":10,"C":10}', 'A', 'mixed', 26),
('etel_180', 'Mi a balzsamecet eredeti hazája?', '[{"key":"A","text":"Olaszország (Modena)","correct":true},{"key":"B","text":"Görögország","correct":false},{"key":"C","text":"Spanyolország","correct":false}]', '{"A":70,"B":20,"C":10}', 'A', 'mixed', 26),
('etel_181', 'Melyik országból származik a goulash (gulyás)?', '[{"key":"A","text":"Magyarország","correct":true},{"key":"B","text":"Ausztria","correct":false},{"key":"C","text":"Németország","correct":false}]', '{"A":90,"B":5,"C":5}', 'A', 'mixed', 26),
('etel_182', 'Mi az olivaolaj legmagasabb minőségi kategóriája?', '[{"key":"A","text":"Extra szűz (Extra Virgin)","correct":true},{"key":"B","text":"Szűz (Virgin)","correct":false},{"key":"C","text":"Pure olive oil","correct":false}]', '{"A":80,"B":15,"C":5}', 'A', 'mixed', 26),
('etel_183', 'Melyik országból származik a dim sum?', '[{"key":"A","text":"Kína (Kanton)","correct":true},{"key":"B","text":"Japán","correct":false},{"key":"C","text":"Hongkong","correct":false}]', '{"A":70,"B":15,"C":15}', 'A', 'mixed', 26),
('etel_184', 'Mi a quinoa?', '[{"key":"A","text":"Magféle (pszeudogabona)","correct":true},{"key":"B","text":"Gabonafajta","correct":false},{"key":"C","text":"Hüvelyes","correct":false}]', '{"A":65,"B":25,"C":10}', 'A', 'mixed', 26),
('etel_185', 'Melyik országból származik a sachertorte?', '[{"key":"A","text":"Ausztria","correct":true},{"key":"B","text":"Németország","correct":false},{"key":"C","text":"Svájc","correct":false}]', '{"A":80,"B":10,"C":10}', 'A', 'mixed', 26),
('etel_186', 'Mi a nori?', '[{"key":"A","text":"Szárított tengeri alga","correct":true},{"key":"B","text":"Rizstészta","correct":false},{"key":"C","text":"Szójaszósz","correct":false}]', '{"A":75,"B":15,"C":10}', 'A', 'mixed', 26),
('etel_187', 'Melyik országból származik a pierogi?', '[{"key":"A","text":"Lengyelország","correct":true},{"key":"B","text":"Oroszország","correct":false},{"key":"C","text":"Ukrajna","correct":false}]', '{"A":70,"B":20,"C":10}', 'A', 'mixed', 26),
('etel_188', 'Mi a matcha?', '[{"key":"A","text":"Őrölt zöld tea por","correct":true},{"key":"B","text":"Fermentált tea","correct":false},{"key":"C","text":"Virágos tea","correct":false}]', '{"A":80,"B":10,"C":10}', 'A', 'mixed', 26),
('etel_189', 'Melyik országból származik a moussaka?', '[{"key":"A","text":"Görögország","correct":true},{"key":"B","text":"Törökország","correct":false},{"key":"C","text":"Libanon","correct":false}]', '{"A":75,"B":15,"C":10}', 'A', 'mixed', 26),
('etel_190', 'Mi a garam masala?', '[{"key":"A","text":"Indiai fűszerkeverék","correct":true},{"key":"B","text":"Húsétel","correct":false},{"key":"C","text":"Desszert","correct":false}]', '{"A":75,"B":15,"C":10}', 'A', 'mixed', 26),
('etel_191', 'Melyik országból származik a ramen?', '[{"key":"A","text":"Japán (kínai eredetű)","correct":true},{"key":"B","text":"Korea","correct":false},{"key":"C","text":"Vietnam","correct":false}]', '{"A":70,"B":20,"C":10}', 'A', 'mixed', 26),
('etel_192', 'Mi a tofu alapanyaga?', '[{"key":"A","text":"Szójabab","correct":true},{"key":"B","text":"Rizs","correct":false},{"key":"C","text":"Búza","correct":false}]', '{"A":85,"B":10,"C":5}', 'A', 'mixed', 26),
('etel_193', 'Melyik országból származik a baba ganoush?', '[{"key":"A","text":"Libanon/Közel-Kelet","correct":true},{"key":"B","text":"Görögország","correct":false},{"key":"C","text":"Törökország","correct":false}]', '{"A":60,"B":25,"C":15}', 'A', 'mixed', 26),
('etel_194', 'Mi a leghíresebb olasz kávéital?', '[{"key":"A","text":"Espresso","correct":true},{"key":"B","text":"Latte","correct":false},{"key":"C","text":"Americano","correct":false}]', '{"A":80,"B":10,"C":10}', 'A', 'mixed', 26),
('etel_195', 'Melyik országból származik a börek?', '[{"key":"A","text":"Törökország","correct":true},{"key":"B","text":"Görögország","correct":false},{"key":"C","text":"Bosznia","correct":false}]', '{"A":70,"B":20,"C":10}', 'A', 'mixed', 26),
('etel_196', 'Mi a tempeh?', '[{"key":"A","text":"Fermentált szójabab termék","correct":true},{"key":"B","text":"Indonéz fűszerkeverék","correct":false},{"key":"C","text":"Rizsétel","correct":false}]', '{"A":65,"B":20,"C":15}', 'A', 'mixed', 26),
('etel_197', 'Melyik országból származik a churros?', '[{"key":"A","text":"Spanyolország","correct":true},{"key":"B","text":"Mexikó","correct":false},{"key":"C","text":"Portugália","correct":false}]', '{"A":70,"B":20,"C":10}', 'A', 'mixed', 26),
('etel_198', 'Mi a tahini?', '[{"key":"A","text":"Szezámmagpaszta","correct":true},{"key":"B","text":"Mogyorókrém","correct":false},{"key":"C","text":"Olivaolaj készítmény","correct":false}]', '{"A":75,"B":15,"C":10}', 'A', 'mixed', 26),
('etel_199', 'Melyik országból származik a bruschetta?', '[{"key":"A","text":"Olaszország","correct":true},{"key":"B","text":"Spanyolország","correct":false},{"key":"C","text":"Franciaország","correct":false}]', '{"A":85,"B":10,"C":5}', 'A', 'mixed', 26),
('etel_200', 'Mi a ghee?', '[{"key":"A","text":"Tisztított vaj (indiai)","correct":true},{"key":"B","text":"Indiai fűszerkeverék","correct":false},{"key":"C","text":"Növényi olaj","correct":false}]', '{"A":65,"B":25,"C":10}', 'A', 'mixed', 26);

-- Topic 26 translations
INSERT INTO public.question_translations (question_id, lang, question_text, answer_a, answer_b, answer_c) VALUES
('etel_151', 'en', 'Which country does sushi come from?', 'Japan', 'China', 'Korea'),
('etel_152', 'en', 'What is one of the most famous French sauces?', 'Béarnaise', 'Marinara', 'Teriyaki'),
('etel_153', 'en', 'Which country does pizza come from?', 'Italy', 'Greece', 'Spain'),
('etel_154', 'en', 'What is wasabi made from?', 'Wasabi root', 'Green pepper', 'Avocado'),
('etel_155', 'en', 'Which country does goulash come from?', 'Hungary', 'Austria', 'Czech Republic'),
('etel_156', 'en', 'What is the main ingredient of paella?', 'Rice', 'Pasta', 'Couscous'),
('etel_157', 'en', 'Which country does the croissant come from?', 'Austria (later France)', 'France', 'Belgium'),
('etel_158', 'en', 'What is the source of umami taste?', 'Glutamate', 'Sugar', 'Salt'),
('etel_159', 'en', 'Which country does pad thai come from?', 'Thailand', 'Vietnam', 'Indonesia'),
('etel_160', 'en', 'What is miso made from?', 'Fermented soybeans', 'Rice', 'Seaweed'),
('etel_161', 'en', 'Which country does falafel come from?', 'Middle East (Egypt/Levant)', 'India', 'Turkey'),
('etel_162', 'en', 'What is the main ingredient of chocolate?', 'Cocoa beans', 'Coffee beans', 'Hazelnuts'),
('etel_163', 'en', 'Which country do tacos come from?', 'Mexico', 'Spain', 'Peru'),
('etel_164', 'en', 'What is the original name of Parmesan cheese?', 'Parmigiano-Reggiano', 'Grana Padano', 'Pecorino Romano'),
('etel_165', 'en', 'Which country does kimchi come from?', 'Korea', 'Japan', 'China'),
('etel_166', 'en', 'What makes champagne special?', 'It can only come from the Champagne region', 'Made from a special grape variety', 'Always sweet'),
('etel_167', 'en', 'Which country does curry come from?', 'India', 'Thailand', 'Malaysia'),
('etel_168', 'en', 'What is foie gras made from?', 'Goose or duck liver', 'Chicken liver', 'Pork liver'),
('etel_169', 'en', 'Which country does tiramisu come from?', 'Italy', 'France', 'Spain'),
('etel_170', 'en', 'How long is soy sauce fermented?', 'Months to years', 'Days', 'Hours'),
('etel_171', 'en', 'Which country does baklava come from?', 'Turkey/Greece', 'Lebanon', 'Iran'),
('etel_172', 'en', 'What is the most expensive type of coffee?', 'Kopi Luwak', 'Blue Mountain', 'Geisha'),
('etel_173', 'en', 'Which country does pho soup come from?', 'Vietnam', 'Thailand', 'China'),
('etel_174', 'en', 'What makes truffles special?', 'Underground fungus, found with dogs/pigs', 'Only grows in mountains', 'Poisonous but edible when cooked'),
('etel_175', 'en', 'Which country does ceviche come from?', 'Peru', 'Mexico', 'Chile'),
('etel_176', 'en', 'What is the most expensive spice in the world?', 'Saffron', 'Vanilla', 'Cardamom'),
('etel_177', 'en', 'Which country does rendang come from?', 'Indonesia', 'Malaysia', 'Singapore'),
('etel_178', 'en', 'What makes Kobe beef special?', 'Wagyu from the Kobe region', 'Special feeding', 'Only young animals'),
('etel_179', 'en', 'Which country does döner kebab come from?', 'Turkey', 'Greece', 'Lebanon'),
('etel_180', 'en', 'What is the original home of balsamic vinegar?', 'Italy (Modena)', 'Greece', 'Spain'),
('etel_181', 'en', 'Which country does goulash come from?', 'Hungary', 'Austria', 'Germany'),
('etel_182', 'en', 'What is the highest quality category of olive oil?', 'Extra Virgin', 'Virgin', 'Pure olive oil'),
('etel_183', 'en', 'Which country does dim sum come from?', 'China (Canton)', 'Japan', 'Hong Kong'),
('etel_184', 'en', 'What is quinoa?', 'Seed (pseudocereal)', 'Grain', 'Legume'),
('etel_185', 'en', 'Which country does sachertorte come from?', 'Austria', 'Germany', 'Switzerland'),
('etel_186', 'en', 'What is nori?', 'Dried seaweed', 'Rice noodles', 'Soy sauce'),
('etel_187', 'en', 'Which country does pierogi come from?', 'Poland', 'Russia', 'Ukraine'),
('etel_188', 'en', 'What is matcha?', 'Ground green tea powder', 'Fermented tea', 'Flower tea'),
('etel_189', 'en', 'Which country does moussaka come from?', 'Greece', 'Turkey', 'Lebanon'),
('etel_190', 'en', 'What is garam masala?', 'Indian spice blend', 'Meat dish', 'Dessert'),
('etel_191', 'en', 'Which country does ramen come from?', 'Japan (Chinese origin)', 'Korea', 'Vietnam'),
('etel_192', 'en', 'What is tofu made from?', 'Soybeans', 'Rice', 'Wheat'),
('etel_193', 'en', 'Which country does baba ganoush come from?', 'Lebanon/Middle East', 'Greece', 'Turkey'),
('etel_194', 'en', 'What is the most famous Italian coffee drink?', 'Espresso', 'Latte', 'Americano'),
('etel_195', 'en', 'Which country does börek come from?', 'Turkey', 'Greece', 'Bosnia'),
('etel_196', 'en', 'What is tempeh?', 'Fermented soybean product', 'Indonesian spice blend', 'Rice dish'),
('etel_197', 'en', 'Which country does churros come from?', 'Spain', 'Mexico', 'Portugal'),
('etel_198', 'en', 'What is tahini?', 'Sesame paste', 'Peanut butter', 'Olive oil preparation'),
('etel_199', 'en', 'Which country does bruschetta come from?', 'Italy', 'Spain', 'France'),
('etel_200', 'en', 'What is ghee?', 'Clarified butter (Indian)', 'Indian spice blend', 'Vegetable oil');
