
-- Topic 8: Ancient Civilizations - ancient_151 to ancient_200 (source_category = 'mixed')
INSERT INTO questions (id, question, answers, correct_answer, topic_id, audience, third, source_category) VALUES
('ancient_151', 'Melyik ókori civilizáció építette a Parthenont?', '[{"key":"A","text":"Rómaiak"},{"key":"B","text":"Görögök"},{"key":"C","text":"Egyiptomiak"},{"key":"D","text":"Perzsák"}]', 'B', 8, '[10,70,15,5]', 'B', 'mixed'),
('ancient_152', 'Ki volt az első római császár?', '[{"key":"A","text":"Nero"},{"key":"B","text":"Caligula"},{"key":"C","text":"Augustus"},{"key":"D","text":"Julius Caesar"}]', 'C', 8, '[15,10,55,20]', 'C', 'mixed'),
('ancient_153', 'Melyik folyó mellett épült Babilon?', '[{"key":"A","text":"Nílus"},{"key":"B","text":"Tigris"},{"key":"C","text":"Eufrátesz"},{"key":"D","text":"Indus"}]', 'C', 8, '[20,25,45,10]', 'C', 'mixed'),
('ancient_154', 'Melyik ókori nép találta fel az ábécét?', '[{"key":"A","text":"Görögök"},{"key":"B","text":"Föníciaiak"},{"key":"C","text":"Egyiptomiak"},{"key":"D","text":"Sumérok"}]', 'B', 8, '[25,50,15,10]', 'B', 'mixed'),
('ancient_155', 'Hány évig tartott a trójai háború a legenda szerint?', '[{"key":"A","text":"5 év"},{"key":"B","text":"10 év"},{"key":"C","text":"15 év"},{"key":"D","text":"20 év"}]', 'B', 8, '[15,60,15,10]', 'B', 'mixed'),
('ancient_156', 'Melyik ókori városban tartották az első olimpiai játékokat?', '[{"key":"A","text":"Athén"},{"key":"B","text":"Spárta"},{"key":"C","text":"Olümpia"},{"key":"D","text":"Korinthosz"}]', 'C', 8, '[30,10,50,10]', 'C', 'mixed'),
('ancient_157', 'Ki építtette a Hadrianus-falat?', '[{"key":"A","text":"Augustus császár"},{"key":"B","text":"Hadrianus császár"},{"key":"C","text":"Traianus császár"},{"key":"D","text":"Marcus Aurelius"}]', 'B', 8, '[15,55,20,10]', 'B', 'mixed'),
('ancient_158', 'Melyik ókori kultúra készítette a terrakotta hadsereget?', '[{"key":"A","text":"Japán"},{"key":"B","text":"India"},{"key":"C","text":"Kína"},{"key":"D","text":"Korea"}]', 'C', 8, '[10,10,70,10]', 'C', 'mixed'),
('ancient_159', 'Melyik görög városállam volt híres a demokratikus rendszeréről?', '[{"key":"A","text":"Spárta"},{"key":"B","text":"Théba"},{"key":"C","text":"Athén"},{"key":"D","text":"Korinthosz"}]', 'C', 8, '[15,10,65,10]', 'C', 'mixed'),
('ancient_160', 'Ki volt a makedón Nagy Sándor apja?', '[{"key":"A","text":"Alexandrosz"},{"key":"B","text":"II. Fülöp"},{"key":"C","text":"Perdikkasz"},{"key":"D","text":"Antipatrosz"}]', 'B', 8, '[20,55,15,10]', 'B', 'mixed'),
('ancient_161', 'Melyik ókori civilizáció építette Machu Picchut?', '[{"key":"A","text":"Maja"},{"key":"B","text":"Azték"},{"key":"C","text":"Inka"},{"key":"D","text":"Olmék"}]', 'C', 8, '[20,15,55,10]', 'C', 'mixed'),
('ancient_162', 'Mi volt a görög istenek lakhelye?', '[{"key":"A","text":"Olümposz"},{"key":"B","text":"Parnasszosz"},{"key":"C","text":"Pelion"},{"key":"D","text":"Ida"}]', 'A', 8, '[70,15,10,5]', 'A', 'mixed'),
('ancient_163', 'Melyik római császár égette fel Rómát a legenda szerint?', '[{"key":"A","text":"Caligula"},{"key":"B","text":"Nero"},{"key":"C","text":"Commodus"},{"key":"D","text":"Domitianus"}]', 'B', 8, '[15,65,15,5]', 'B', 'mixed'),
('ancient_164', 'Melyik ókori nép használta először a vasat fegyverként?', '[{"key":"A","text":"Egyiptomiak"},{"key":"B","text":"Hettiták"},{"key":"C","text":"Asszírok"},{"key":"D","text":"Perzsák"}]', 'B', 8, '[25,45,20,10]', 'B', 'mixed'),
('ancient_165', 'Hány csoda volt az ókori világ hét csodája között?', '[{"key":"A","text":"5"},{"key":"B","text":"6"},{"key":"C","text":"7"},{"key":"D","text":"8"}]', 'C', 8, '[5,10,80,5]', 'C', 'mixed'),
('ancient_166', 'Ki volt a spártai király, aki 300 harcosával védte Thermopülét?', '[{"key":"A","text":"Leonidász"},{"key":"B","text":"Kleomenész"},{"key":"C","text":"Agészilaosz"},{"key":"D","text":"Pauszaniasz"}]', 'A', 8, '[75,10,10,5]', 'A', 'mixed'),
('ancient_167', 'Melyik ókori nép építette a zikkuratokat?', '[{"key":"A","text":"Egyiptomiak"},{"key":"B","text":"Görögök"},{"key":"C","text":"Mezopotámiaiak"},{"key":"D","text":"Perzsák"}]', 'C', 8, '[25,10,55,10]', 'C', 'mixed'),
('ancient_168', 'Mi volt az egyiptomi fáraók temetkezési helye?', '[{"key":"A","text":"Templom"},{"key":"B","text":"Piramis"},{"key":"C","text":"Palota"},{"key":"D","text":"Obeliszk"}]', 'B', 8, '[10,75,10,5]', 'B', 'mixed'),
('ancient_169', 'Melyik római épület volt a gladiátorok küzdőtere?', '[{"key":"A","text":"Pantheon"},{"key":"B","text":"Forum"},{"key":"C","text":"Colosseum"},{"key":"D","text":"Circus Maximus"}]', 'C', 8, '[10,10,70,10]', 'C', 'mixed'),
('ancient_170', 'Ki írta az Iliászt?', '[{"key":"A","text":"Szophoklész"},{"key":"B","text":"Homérosz"},{"key":"C","text":"Euripidész"},{"key":"D","text":"Arisztophanész"}]', 'B', 8, '[15,65,15,5]', 'B', 'mixed'),
('ancient_171', 'Melyik ókori kultúra készítette a nazca-vonalakat?', '[{"key":"A","text":"Inka"},{"key":"B","text":"Maja"},{"key":"C","text":"Nazca"},{"key":"D","text":"Moche"}]', 'C', 8, '[20,15,55,10]', 'C', 'mixed'),
('ancient_172', 'Mi volt a római légiók alapegysége?', '[{"key":"A","text":"Centuria"},{"key":"B","text":"Cohors"},{"key":"C","text":"Manipulus"},{"key":"D","text":"Contubernium"}]', 'A', 8, '[50,25,15,10]', 'A', 'mixed'),
('ancient_173', 'Melyik görög filozófus volt Platón tanítványa?', '[{"key":"A","text":"Szókratész"},{"key":"B","text":"Arisztotelész"},{"key":"C","text":"Epikurosz"},{"key":"D","text":"Diogenész"}]', 'B', 8, '[20,55,15,10]', 'B', 'mixed'),
('ancient_174', 'Melyik ókori birodalom központja volt Perszepolisz?', '[{"key":"A","text":"Görög"},{"key":"B","text":"Római"},{"key":"C","text":"Perzsa"},{"key":"D","text":"Egyiptomi"}]', 'C', 8, '[15,10,65,10]', 'C', 'mixed'),
('ancient_175', 'Ki volt az egyiptomi napisten?', '[{"key":"A","text":"Ozirisz"},{"key":"B","text":"Hórusz"},{"key":"C","text":"Ré"},{"key":"D","text":"Anubisz"}]', 'C', 8, '[20,20,50,10]', 'C', 'mixed');

-- Translations for ancient_151-175 (EN)
INSERT INTO question_translations (question_id, lang, question_text, answer_a, answer_b, answer_c) VALUES
('ancient_151', 'en', 'Which ancient civilization built the Parthenon?', 'Romans', 'Greeks', 'Egyptians'),
('ancient_152', 'en', 'Who was the first Roman emperor?', 'Nero', 'Caligula', 'Augustus'),
('ancient_153', 'en', 'Which river was Babylon built beside?', 'Nile', 'Tigris', 'Euphrates'),
('ancient_154', 'en', 'Which ancient people invented the alphabet?', 'Greeks', 'Phoenicians', 'Egyptians'),
('ancient_155', 'en', 'How many years did the Trojan War last according to legend?', '5 years', '10 years', '15 years'),
('ancient_156', 'en', 'In which ancient city were the first Olympic Games held?', 'Athens', 'Sparta', 'Olympia'),
('ancient_157', 'en', 'Who built Hadrian''s Wall?', 'Emperor Augustus', 'Emperor Hadrian', 'Emperor Trajan'),
('ancient_158', 'en', 'Which ancient culture created the Terracotta Army?', 'Japan', 'India', 'China'),
('ancient_159', 'en', 'Which Greek city-state was famous for its democratic system?', 'Sparta', 'Thebes', 'Athens'),
('ancient_160', 'en', 'Who was the father of Alexander the Great?', 'Alexander', 'Philip II', 'Perdiccas'),
('ancient_161', 'en', 'Which ancient civilization built Machu Picchu?', 'Maya', 'Aztec', 'Inca'),
('ancient_162', 'en', 'What was the home of the Greek gods?', 'Olympus', 'Parnassus', 'Pelion'),
('ancient_163', 'en', 'Which Roman emperor allegedly burned Rome?', 'Caligula', 'Nero', 'Commodus'),
('ancient_164', 'en', 'Which ancient people first used iron as a weapon?', 'Egyptians', 'Hittites', 'Assyrians'),
('ancient_165', 'en', 'How many wonders were in the Seven Wonders of the Ancient World?', '5', '6', '7'),
('ancient_166', 'en', 'Who was the Spartan king who defended Thermopylae with 300 warriors?', 'Leonidas', 'Cleomenes', 'Agesilaus'),
('ancient_167', 'en', 'Which ancient people built the ziggurats?', 'Egyptians', 'Greeks', 'Mesopotamians'),
('ancient_168', 'en', 'What was the burial place of Egyptian pharaohs?', 'Temple', 'Pyramid', 'Palace'),
('ancient_169', 'en', 'Which Roman building was the gladiators'' arena?', 'Pantheon', 'Forum', 'Colosseum'),
('ancient_170', 'en', 'Who wrote the Iliad?', 'Sophocles', 'Homer', 'Euripides'),
('ancient_171', 'en', 'Which ancient culture created the Nazca Lines?', 'Inca', 'Maya', 'Nazca'),
('ancient_172', 'en', 'What was the basic unit of Roman legions?', 'Century', 'Cohort', 'Maniple'),
('ancient_173', 'en', 'Which Greek philosopher was Plato''s student?', 'Socrates', 'Aristotle', 'Epicurus'),
('ancient_174', 'en', 'Which ancient empire had Persepolis as its center?', 'Greek', 'Roman', 'Persian'),
('ancient_175', 'en', 'Who was the Egyptian sun god?', 'Osiris', 'Horus', 'Ra');
