
-- Topic 28 (Vallás) - religion_151 to religion_200 English translations
INSERT INTO question_translations (question_id, lang, question_text, answer_a, answer_b, answer_c) VALUES
('religion_151', 'en', 'Who founded Buddhism?', 'Siddhartha Gautama', 'Confucius', 'Lao Tzu'),
('religion_152', 'en', 'What is the holy book of Islam?', 'Quran', 'Torah', 'Bible'),
('religion_153', 'en', 'How many pillars does Islam have?', '5', '4', '7'),
('religion_154', 'en', 'What is the Jewish day of rest called?', 'Sabbath', 'Sunday', 'Friday'),
('religion_155', 'en', 'What is the Hindu concept of rebirth called?', 'Reincarnation', 'Nirvana', 'Karma'),
('religion_156', 'en', 'Who wrote the 95 Theses?', 'Martin Luther', 'John Calvin', 'Erasmus'),
('religion_157', 'en', 'What is the most sacred city in Islam?', 'Mecca', 'Medina', 'Jerusalem'),
('religion_158', 'en', 'What is the Christian Trinity?', 'Father, Son, Holy Spirit', 'God, Jesus, Mary', 'Heaven, Earth, Hell'),
('religion_159', 'en', 'What is the Buddhist concept of liberation?', 'Nirvana', 'Samsara', 'Dharma'),
('religion_160', 'en', 'What is the Jewish New Year called?', 'Rosh Hashanah', 'Yom Kippur', 'Hanukkah'),
('religion_161', 'en', 'Which religion worships in temples with statues of deities?', 'Hinduism', 'Islam', 'Judaism'),
('religion_162', 'en', 'What is the Dalai Lama the leader of?', 'Tibetan Buddhism', 'Zen Buddhism', 'Theravada Buddhism'),
('religion_163', 'en', 'What is the Islamic pilgrimage to Mecca called?', 'Hajj', 'Umrah', 'Jihad'),
('religion_164', 'en', 'What is the Christian celebration of Jesus resurrection?', 'Easter', 'Christmas', 'Pentecost'),
('religion_165', 'en', 'What is karma in Eastern religions?', 'Law of cause and effect', 'Type of meditation', 'Sacred text'),
('religion_166', 'en', 'What is the Shinto religion native to?', 'Japan', 'China', 'Korea'),
('religion_167', 'en', 'What is the Torah?', 'Jewish holy book', 'Islamic prayer', 'Hindu god'),
('religion_168', 'en', 'What is the Hindu festival of lights called?', 'Diwali', 'Holi', 'Navratri'),
('religion_169', 'en', 'What is the Pope the head of?', 'Catholic Church', 'Orthodox Church', 'Protestant Church'),
('religion_170', 'en', 'What is the main practice in Zen Buddhism?', 'Meditation', 'Pilgrimage', 'Sacrifice'),
('religion_171', 'en', 'What is the Islamic month of fasting?', 'Ramadan', 'Muharram', 'Shaban'),
('religion_172', 'en', 'What is the Jewish festival of Passover about?', 'Exodus from Egypt', 'Creation', 'Temple destruction'),
('religion_173', 'en', 'What is the Hindu concept of duty?', 'Dharma', 'Karma', 'Moksha'),
('religion_174', 'en', 'What is the Sikh holy book called?', 'Guru Granth Sahib', 'Vedas', 'Tripitaka'),
('religion_175', 'en', 'What does the yin-yang symbol represent?', 'Balance of opposites', 'Eternal life', 'Divine power'),
('religion_176', 'en', 'What is the Christian sacrament of bread and wine?', 'Eucharist', 'Baptism', 'Confirmation'),
('religion_177', 'en', 'What is the main Hindu god of preservation?', 'Vishnu', 'Shiva', 'Brahma'),
('religion_178', 'en', 'What is the Buddhist Eightfold Path?', 'Path to enlightenment', 'Creation story', 'Afterlife description'),
('religion_179', 'en', 'What is the Wailing Wall sacred to?', 'Judaism', 'Islam', 'Christianity'),
('religion_180', 'en', 'What is Confucianism mainly about?', 'Ethics and social harmony', 'Afterlife', 'Nature worship'),
('religion_181', 'en', 'What is the Hindu goddess of wealth?', 'Lakshmi', 'Kali', 'Saraswati'),
('religion_182', 'en', 'What is the Christian symbol of the fish called?', 'Ichthys', 'Chi-Rho', 'Alpha'),
('religion_183', 'en', 'What is the Islamic declaration of faith?', 'Shahada', 'Salat', 'Zakat'),
('religion_184', 'en', 'What is the Buddhist Three Jewels?', 'Buddha, Dharma, Sangha', 'Mind, Body, Spirit', 'Past, Present, Future'),
('religion_185', 'en', 'What is the Jewish Day of Atonement?', 'Yom Kippur', 'Rosh Hashanah', 'Sukkot'),
('religion_186', 'en', 'What is the Hindu sacred river?', 'Ganges', 'Indus', 'Brahmaputra'),
('religion_187', 'en', 'What is the Orthodox Christian split from Rome called?', 'Great Schism', 'Reformation', 'Counter-Reformation'),
('religion_188', 'en', 'What is the Quaker religious movement known for?', 'Pacifism', 'Hierarchy', 'Rituals'),
('religion_189', 'en', 'What is the Hindu god with an elephant head?', 'Ganesha', 'Hanuman', 'Krishna'),
('religion_190', 'en', 'What is the Taoist concept of the way?', 'Tao', 'Chi', 'Feng'),
('religion_191', 'en', 'What is the Christian season before Easter?', 'Lent', 'Advent', 'Epiphany'),
('religion_192', 'en', 'What is the Buddhist concept of suffering?', 'Dukkha', 'Sukha', 'Mudita'),
('religion_193', 'en', 'What is the Jewish coming of age ceremony for boys?', 'Bar Mitzvah', 'Brit Milah', 'Pidyon HaBen'),
('religion_194', 'en', 'What is the Islamic call to prayer?', 'Adhan', 'Dua', 'Dhikr'),
('religion_195', 'en', 'What is the Hindu practice of non-violence?', 'Ahimsa', 'Satya', 'Brahmacharya'),
('religion_196', 'en', 'What is the Greek Orthodox Christmas date?', 'January 7', 'December 25', 'January 1'),
('religion_197', 'en', 'What is the Buddhist middle way?', 'Avoiding extremes', 'Strict asceticism', 'Pure hedonism'),
('religion_198', 'en', 'What is the Amish community known for?', 'Simple living', 'Technology', 'Urban life'),
('religion_199', 'en', 'What is the Hindu concept of ultimate reality?', 'Brahman', 'Atman', 'Maya'),
('religion_200', 'en', 'What is the Sufi branch of Islam focused on?', 'Mysticism', 'Law', 'Politics')
ON CONFLICT (question_id, lang) DO NOTHING;
