
-- Add missing English translations for Topic 4 (orvostudomany 151-200)
INSERT INTO question_translations (question_id, lang, question_text, answer_a, answer_b, answer_c)
VALUES
('orvostudomany_151', 'en', 'Who discovered penicillin?', 'Louis Pasteur', 'Alexander Fleming', 'Robert Koch'),
('orvostudomany_152', 'en', 'What is an MRI scan?', 'X-ray', 'Magnetic Resonance Imaging', 'Ultrasound'),
('orvostudomany_153', 'en', 'What is antibiotic resistance?', 'Allergy to antibiotics', 'Bacteria becoming resistant', 'Protection against viruses'),
('orvostudomany_154', 'en', 'Which medical specialty deals with the heart?', 'Neurology', 'Cardiology', 'Orthopedics'),
('orvostudomany_155', 'en', 'What is chemotherapy?', 'Physical therapy', 'Anti-cancer drug treatment', 'Pain relief'),
('orvostudomany_156', 'en', 'Which organ transplant was performed first successfully?', 'Heart', 'Kidney', 'Liver'),
('orvostudomany_157', 'en', 'What is anesthesia?', 'Pain relief during surgery', 'Pain enhancement', 'Bleeding control'),
('orvostudomany_158', 'en', 'Who developed the first successful vaccine?', 'Louis Pasteur', 'Edward Jenner', 'Jonas Salk'),
('orvostudomany_159', 'en', 'What is oncology?', 'Study of bones', 'Study of tumors', 'Dermatology'),
('orvostudomany_160', 'en', 'Which test measures blood hemoglobin levels?', 'ECG', 'Blood count', 'X-ray'),
('orvostudomany_161', 'en', 'What is a biopsy?', 'Blood test', 'Tissue sample collection', 'X-ray'),
('orvostudomany_162', 'en', 'Which medical specialty is gynecology?', 'Andrology', 'Gynecology', 'Urology'),
('orvostudomany_163', 'en', 'What is an ECG?', 'Brain activity measurement', 'Heart electrical activity measurement', 'Blood pressure measurement'),
('orvostudomany_164', 'en', 'Who performed the first heart transplant?', 'Michael DeBakey', 'Christiaan Barnard', 'Denton Cooley'),
('orvostudomany_165', 'en', 'What is radiology?', 'Sound wave application', 'Diagnostic imaging', 'Surgery'),
('orvostudomany_166', 'en', 'Against which disease did Jonas Salk develop a vaccine?', 'Measles', 'Polio', 'Smallpox'),
('orvostudomany_167', 'en', 'What is laparoscopy?', 'Open surgery', 'Minimally invasive surgery', 'X-ray examination'),
('orvostudomany_168', 'en', 'Which medical specialty is ophthalmology?', 'Otology', 'Ophthalmology', 'Orthopedics'),
('orvostudomany_169', 'en', 'What is a CT scan?', 'Ultrasound', 'Computed Tomography', 'ECG'),
('orvostudomany_170', 'en', 'Which scientist discovered the tuberculosis pathogen?', 'Louis Pasteur', 'Robert Koch', 'Alexander Fleming'),
('orvostudomany_171', 'en', 'What is the purpose of dialysis?', 'Heart failure treatment', 'Kidney failure treatment', 'Liver disease treatment'),
('orvostudomany_172', 'en', 'What is endocrinology?', 'Dermatology', 'Hormonal system science', 'Neurology'),
('orvostudomany_173', 'en', 'Who was the pioneer of modern hand hygiene?', 'Louis Pasteur', 'Ignaz Semmelweis', 'Joseph Lister'),
('orvostudomany_174', 'en', 'What is prognosis?', 'Diagnosis', 'Expected course of disease', 'Treatment plan'),
('orvostudomany_175', 'en', 'Which medical specialty deals with children?', 'Geriatrics', 'Pediatrics', 'Andrology'),
('orvostudomany_176', 'en', 'What is a pacemaker?', 'Blood clotting device', 'Heart rhythm regulator', 'Pain reliever'),
('orvostudomany_177', 'en', 'What is hematology?', 'Bone science', 'Blood and blood-forming organs science', 'Dermatology'),
('orvostudomany_178', 'en', 'Who discovered insulin?', 'Alexander Fleming', 'Frederick Banting', 'Jonas Salk'),
('orvostudomany_179', 'en', 'What is radiation therapy?', 'Light therapy', 'Ionizing radiation treatment', 'Heat treatment'),
('orvostudomany_180', 'en', 'Which medical specialty is dermatology?', 'Nephrology', 'Dermatology', 'Pulmonology'),
('orvostudomany_181', 'en', 'What is a stent?', 'Medication', 'Vessel widening device', 'Diagnostic tool'),
('orvostudomany_182', 'en', 'Who developed the smallpox vaccine?', 'Louis Pasteur', 'Edward Jenner', 'Robert Koch'),
('orvostudomany_183', 'en', 'What is pathology?', 'Sports medicine', 'Study of diseases', 'Psychiatry'),
('orvostudomany_184', 'en', 'Which medical specialty is psychiatry?', 'Pulmonology', 'Psychiatry', 'Rheumatology'),
('orvostudomany_185', 'en', 'What is an organ transplant?', 'Drug therapy', 'Replacing damaged organ with healthy one', 'Diagnostic procedure'),
('orvostudomany_186', 'en', 'Who discovered X-rays?', 'Wilhelm Röntgen', 'Marie Curie', 'Albert Einstein'),
('orvostudomany_187', 'en', 'What is rheumatology?', 'Bone science', 'Joint and connective tissue science', 'Dermatology'),
('orvostudomany_188', 'en', 'What is an antibiotic?', 'Antiviral drug', 'Antibacterial drug', 'Pain reliever'),
('orvostudomany_189', 'en', 'Which medical specialty is pulmonology?', 'Heart science', 'Lung science', 'Liver science'),
('orvostudomany_190', 'en', 'What is an ultrasound?', 'X-ray', 'Sound wave imaging', 'CT scan'),
('orvostudomany_191', 'en', 'Who discovered DNA structure?', 'Gregor Mendel', 'Watson and Crick', 'Charles Darwin'),
('orvostudomany_192', 'en', 'What is immunology?', 'Bone science', 'Immune system science', 'Dermatology'),
('orvostudomany_193', 'en', 'What is an epidemic?', 'Single disease case', 'Widespread disease outbreak', 'Chronic illness'),
('orvostudomany_194', 'en', 'Which medical specialty is nephrology?', 'Heart science', 'Kidney science', 'Lung science'),
('orvostudomany_195', 'en', 'What is a vaccine?', 'Antibiotic', 'Disease prevention through immunity', 'Pain reliever'),
('orvostudomany_196', 'en', 'Who pioneered antiseptic surgery?', 'Ignaz Semmelweis', 'Joseph Lister', 'Louis Pasteur'),
('orvostudomany_197', 'en', 'What is gastroenterology?', 'Heart science', 'Digestive system science', 'Bone science'),
('orvostudomany_198', 'en', 'What is a pandemic?', 'Local outbreak', 'Worldwide disease spread', 'Seasonal illness'),
('orvostudomany_199', 'en', 'Which medical specialty is neurology?', 'Bone science', 'Nervous system science', 'Heart science'),
('orvostudomany_200', 'en', 'What is gene therapy?', 'Drug treatment', 'Genetic modification for treatment', 'Surgery')
ON CONFLICT (question_id, lang) DO NOTHING;
