
-- Topic 29 (Filozófia) - phil_151 to phil_200 English translations
INSERT INTO question_translations (question_id, lang, question_text, answer_a, answer_b, answer_c) VALUES
('phil_151', 'en', 'Who said "I think, therefore I am"?', 'Descartes', 'Kant', 'Hegel'),
('phil_152', 'en', 'What is Platos theory of ideal forms?', 'Perfect archetypes exist beyond physical reality', 'Everything is matter', 'Knowledge is impossible'),
('phil_153', 'en', 'What is utilitarianism?', 'Greatest good for greatest number', 'Follow duty regardless of outcome', 'Virtue leads to happiness'),
('phil_154', 'en', 'Who wrote "The Republic"?', 'Plato', 'Aristotle', 'Socrates'),
('phil_155', 'en', 'What is existentialism concerned with?', 'Individual existence and freedom', 'Universal truths', 'Mathematical logic'),
('phil_156', 'en', 'What is the Socratic method?', 'Learning through questioning', 'Memorization', 'Divine revelation'),
('phil_157', 'en', 'Who founded Stoicism?', 'Zeno of Citium', 'Epicurus', 'Diogenes'),
('phil_158', 'en', 'What is Kants categorical imperative?', 'Act only by rules you would universalize', 'Maximize pleasure', 'Follow natural law'),
('phil_159', 'en', 'What is nihilism?', 'Rejection of all values and meaning', 'Belief in God', 'Trust in reason'),
('phil_160', 'en', 'Who wrote "Being and Time"?', 'Heidegger', 'Sartre', 'Husserl'),
('phil_161', 'en', 'What is empiricism?', 'Knowledge comes from experience', 'Knowledge is innate', 'Knowledge is impossible'),
('phil_162', 'en', 'Who is the father of Western philosophy?', 'Socrates', 'Thales', 'Pythagoras'),
('phil_163', 'en', 'What is the trolley problem about?', 'Moral dilemma of sacrificing one to save many', 'Train engineering', 'Urban planning'),
('phil_164', 'en', 'Who wrote "Thus Spoke Zarathustra"?', 'Nietzsche', 'Hegel', 'Schopenhauer'),
('phil_165', 'en', 'What is determinism?', 'All events are caused by prior events', 'Free will exists', 'Reality is random'),
('phil_166', 'en', 'What is Aristotles golden mean?', 'Virtue lies between extremes', 'Pleasure is the goal', 'Suffering builds character'),
('phil_167', 'en', 'Who founded phenomenology?', 'Husserl', 'Heidegger', 'Sartre'),
('phil_168', 'en', 'What is the problem of evil?', 'Why suffering exists if God is good', 'How to define evil', 'Origin of morality'),
('phil_169', 'en', 'Who wrote "Critique of Pure Reason"?', 'Kant', 'Hume', 'Locke'),
('phil_170', 'en', 'What is solipsism?', 'Only ones own mind is certain', 'Reality is shared', 'God exists'),
('phil_171', 'en', 'What is the social contract theory?', 'People agree to form societies', 'Nature determines society', 'Divine right of kings'),
('phil_172', 'en', 'Who wrote "Leviathan"?', 'Hobbes', 'Locke', 'Rousseau'),
('phil_173', 'en', 'What is pragmatism?', 'Truth is what works in practice', 'Abstract truth exists', 'Truth is unknowable'),
('phil_174', 'en', 'Who developed the concept of the Übermensch?', 'Nietzsche', 'Hegel', 'Marx'),
('phil_175', 'en', 'What is epistemology?', 'Study of knowledge', 'Study of existence', 'Study of values'),
('phil_176', 'en', 'Who wrote "Meditations"?', 'Marcus Aurelius', 'Seneca', 'Epictetus'),
('phil_177', 'en', 'What is the mind-body problem?', 'How mental and physical relate', 'Brain surgery ethics', 'Exercise philosophy'),
('phil_178', 'en', 'Who founded logical positivism?', 'Vienna Circle', 'Frankfurt School', 'Oxford Movement'),
('phil_179', 'en', 'What is free will?', 'Ability to make uncaused choices', 'Following desires', 'Obeying laws'),
('phil_180', 'en', 'Who wrote "The Prince"?', 'Machiavelli', 'Hobbes', 'Locke'),
('phil_181', 'en', 'What is ontology?', 'Study of being and existence', 'Study of knowledge', 'Study of logic'),
('phil_182', 'en', 'What is the Allegory of the Cave about?', 'Difference between reality and perception', 'Mining ethics', 'Geology'),
('phil_183', 'en', 'Who developed dialectical materialism?', 'Marx and Engels', 'Hegel', 'Feuerbach'),
('phil_184', 'en', 'What is the veil of ignorance?', 'Rawls concept for fair decision making', 'Religious practice', 'Optical illusion'),
('phil_185', 'en', 'Who wrote "The Second Sex"?', 'Simone de Beauvoir', 'Hannah Arendt', 'Iris Murdoch'),
('phil_186', 'en', 'What is ethical relativism?', 'Morality varies by culture', 'Universal morality exists', 'Morality is meaningless'),
('phil_187', 'en', 'Who founded cynicism?', 'Diogenes', 'Zeno', 'Epicurus'),
('phil_188', 'en', 'What is the ship of Theseus problem?', 'Identity through change', 'Naval history', 'Greek mythology'),
('phil_189', 'en', 'Who wrote "A Theory of Justice"?', 'John Rawls', 'Robert Nozick', 'Michael Sandel'),
('phil_190', 'en', 'What is deontology?', 'Ethics based on duty and rules', 'Ethics based on outcomes', 'Ethics based on virtue'),
('phil_191', 'en', 'Who developed ordinary language philosophy?', 'Wittgenstein', 'Russell', 'Frege'),
('phil_192', 'en', 'What is the is-ought problem?', 'Cannot derive values from facts', 'Logic puzzle', 'Grammar issue'),
('phil_193', 'en', 'Who wrote "The Communist Manifesto"?', 'Marx and Engels', 'Lenin', 'Stalin'),
('phil_194', 'en', 'What is virtue ethics?', 'Character determines right action', 'Rules determine right action', 'Outcomes determine right action'),
('phil_195', 'en', 'Who founded Epicureanism?', 'Epicurus', 'Zeno', 'Diogenes'),
('phil_196', 'en', 'What is the naturalistic fallacy?', 'Deriving good from natural facts', 'Believing in nature spirits', 'Environmental ethics'),
('phil_197', 'en', 'Who wrote "Being and Nothingness"?', 'Sartre', 'Camus', 'Beauvoir'),
('phil_198', 'en', 'What is moral realism?', 'Moral facts objectively exist', 'Morality is subjective', 'Morality is cultural'),
('phil_199', 'en', 'Who developed the concept of bad faith?', 'Sartre', 'Heidegger', 'Camus'),
('phil_200', 'en', 'What is the problem of induction?', 'Past doesnt guarantee future', 'Mathematical proof', 'Scientific method')
ON CONFLICT (question_id, lang) DO NOTHING;
