
-- Topic 25: Környezetvédelem - 50 új kérdés
INSERT INTO public.questions (id, question, answers, audience, third, source_category, topic_id) VALUES
('korny_151', 'Mi a legnagyobb üvegházhatású gáz az atmoszférában?', '[{"key":"A","text":"Szén-dioxid (CO2)","correct":true},{"key":"B","text":"Metán","correct":false},{"key":"C","text":"Dinitrogén-oxid","correct":false}]', '{"A":75,"B":15,"C":10}', 'A', 'mixed', 25),
('korny_152', 'Melyik évben írták alá a Párizsi Klímaegyezményt?', '[{"key":"A","text":"2015","correct":true},{"key":"B","text":"2012","correct":false},{"key":"C","text":"2018","correct":false}]', '{"A":65,"B":20,"C":15}', 'A', 'mixed', 25),
('korny_153', 'Mi a legnagyobb veszélyforrása a biodiverzitás csökkenésének?', '[{"key":"A","text":"Élőhelyek pusztulása","correct":true},{"key":"B","text":"Klímaváltozás","correct":false},{"key":"C","text":"Szennyezés","correct":false}]', '{"A":60,"B":25,"C":15}', 'A', 'mixed', 25),
('korny_154', 'Melyik ország bocsátja ki a legtöbb szén-dioxidot?', '[{"key":"A","text":"Kína","correct":true},{"key":"B","text":"USA","correct":false},{"key":"C","text":"India","correct":false}]', '{"A":75,"B":20,"C":5}', 'A', 'mixed', 25),
('korny_155', 'Mi a Kiotói Jegyzőkönyv fő célja?', '[{"key":"A","text":"Üvegházhatású gázok kibocsátásának csökkentése","correct":true},{"key":"B","text":"Ózonlyuk bezárása","correct":false},{"key":"C","text":"Erdőirtás megállítása","correct":false}]', '{"A":70,"B":20,"C":10}', 'A', 'mixed', 25),
('korny_156', 'Melyik évben történt a csernobili atomkatasztrófa?', '[{"key":"A","text":"1986","correct":true},{"key":"B","text":"1979","correct":false},{"key":"C","text":"1992","correct":false}]', '{"A":75,"B":15,"C":10}', 'A', 'mixed', 25),
('korny_157', 'Mi az ózonlyuk fő okozója?', '[{"key":"A","text":"CFC-k (klór-fluor-karbonok)","correct":true},{"key":"B","text":"Szén-dioxid","correct":false},{"key":"C","text":"Metán","correct":false}]', '{"A":70,"B":20,"C":10}', 'A', 'mixed', 25),
('korny_158', 'Melyik megújuló energiaforrás a leggyorsabban növekvő?', '[{"key":"A","text":"Napenergia","correct":true},{"key":"B","text":"Szélenergia","correct":false},{"key":"C","text":"Vízenergia","correct":false}]', '{"A":60,"B":30,"C":10}', 'A', 'mixed', 25),
('korny_159', 'Mi a legnagyobb óceáni műanyagszennyezési terület neve?', '[{"key":"A","text":"Nagy Csendes-óceáni Szemétsziget","correct":true},{"key":"B","text":"Atlanti Szemétsziget","correct":false},{"key":"C","text":"Indiai-óceáni Szemétsziget","correct":false}]', '{"A":80,"B":10,"C":10}', 'A', 'mixed', 25),
('korny_160', 'Melyik ország rendelkezik a legtöbb nemzeti parkkal?', '[{"key":"A","text":"Ausztrália","correct":true},{"key":"B","text":"USA","correct":false},{"key":"C","text":"Brazília","correct":false}]', '{"A":45,"B":40,"C":15}', 'A', 'mixed', 25),
('korny_161', 'Mi a szén-lábnyom mértékegysége?', '[{"key":"A","text":"Tonna CO2 ekvivalens","correct":true},{"key":"B","text":"Kilowattóra","correct":false},{"key":"C","text":"Liter olajegyenérték","correct":false}]', '{"A":70,"B":20,"C":10}', 'A', 'mixed', 25),
('korny_162', 'Melyik évben alakult meg a Greenpeace?', '[{"key":"A","text":"1971","correct":true},{"key":"B","text":"1985","correct":false},{"key":"C","text":"1960","correct":false}]', '{"A":55,"B":30,"C":15}', 'A', 'mixed', 25),
('korny_163', 'Mi az esőerdők legfontosabb szerepe?', '[{"key":"A","text":"Szén-dioxid elnyelése és oxigéntermelés","correct":true},{"key":"B","text":"Édesvíz tárolása","correct":false},{"key":"C","text":"Gyógynövények termesztése","correct":false}]', '{"A":75,"B":15,"C":10}', 'A', 'mixed', 25),
('korny_164', 'Melyik országban van a legtöbb szélenergia kapacitás?', '[{"key":"A","text":"Kína","correct":true},{"key":"B","text":"USA","correct":false},{"key":"C","text":"Németország","correct":false}]', '{"A":65,"B":25,"C":10}', 'A', 'mixed', 25),
('korny_165', 'Mi a Montreali Jegyzőkönyv fő célja?', '[{"key":"A","text":"Ózonréteget károsító anyagok betiltása","correct":true},{"key":"B","text":"Klímaváltozás elleni küzdelem","correct":false},{"key":"C","text":"Tengeri szennyezés csökkentése","correct":false}]', '{"A":65,"B":25,"C":10}', 'A', 'mixed', 25),
('korny_166', 'Melyik évben volt az első Föld Napja?', '[{"key":"A","text":"1970","correct":true},{"key":"B","text":"1980","correct":false},{"key":"C","text":"1965","correct":false}]', '{"A":55,"B":30,"C":15}', 'A', 'mixed', 25),
('korny_167', 'Mi a legnagyobb fenyegetés a korallzátonyokra?', '[{"key":"A","text":"Óceánok melegedése és savasodása","correct":true},{"key":"B","text":"Túlhalászat","correct":false},{"key":"C","text":"Műanyag szennyezés","correct":false}]', '{"A":65,"B":20,"C":15}', 'A', 'mixed', 25),
('korny_168', 'Melyik ország a napenergia termelésben vezető?', '[{"key":"A","text":"Kína","correct":true},{"key":"B","text":"USA","correct":false},{"key":"C","text":"India","correct":false}]', '{"A":70,"B":20,"C":10}', 'A', 'mixed', 25),
('korny_169', 'Mi a körforgásos gazdaság lényege?', '[{"key":"A","text":"Hulladék minimalizálása és újrahasznosítás maximalizálása","correct":true},{"key":"B","text":"Gazdasági növekedés fenntartása","correct":false},{"key":"C","text":"Importcsökkentés","correct":false}]', '{"A":75,"B":15,"C":10}', 'A', 'mixed', 25),
('korny_170', 'Melyik ökoszisztéma tárolja a legtöbb szenet?', '[{"key":"A","text":"Tőzeglápok","correct":true},{"key":"B","text":"Esőerdők","correct":false},{"key":"C","text":"Óceánok","correct":false}]', '{"A":50,"B":35,"C":15}', 'A', 'mixed', 25),
('korny_171', 'Mi a fő oka a sarki jég olvadásának?', '[{"key":"A","text":"Globális felmelegedés","correct":true},{"key":"B","text":"Ózonlyuk","correct":false},{"key":"C","text":"Tengeri áramlatok változása","correct":false}]', '{"A":85,"B":10,"C":5}', 'A', 'mixed', 25),
('korny_172', 'Melyik évben írták alá a Stockholmi Egyezményt a POP-okról?', '[{"key":"A","text":"2001","correct":true},{"key":"B","text":"1995","correct":false},{"key":"C","text":"2008","correct":false}]', '{"A":45,"B":35,"C":20}', 'A', 'mixed', 25),
('korny_173', 'Mi a legjobb módszer a szén-dioxid kibocsátás csökkentésére?', '[{"key":"A","text":"Megújuló energia használata","correct":true},{"key":"B","text":"Atomerőművek építése","correct":false},{"key":"C","text":"Erdőtelepítés","correct":false}]', '{"A":60,"B":25,"C":15}', 'A', 'mixed', 25),
('korny_174', 'Melyik állatfaj került veszélybe a klímaváltozás miatt?', '[{"key":"A","text":"Jegesmedve","correct":true},{"key":"B","text":"Elefánt","correct":false},{"key":"C","text":"Tigris","correct":false}]', '{"A":80,"B":10,"C":10}', 'A', 'mixed', 25),
('korny_175', 'Mi az IPCC rövidítés jelentése?', '[{"key":"A","text":"Éghajlatváltozási Kormányközi Testület","correct":true},{"key":"B","text":"Nemzetközi Környezetvédelmi Bizottság","correct":false},{"key":"C","text":"Globális Klímavédelmi Szervezet","correct":false}]', '{"A":55,"B":30,"C":15}', 'A', 'mixed', 25),
('korny_176', 'Melyik ország az első a megújuló energia arányában?', '[{"key":"A","text":"Izland","correct":true},{"key":"B","text":"Norvégia","correct":false},{"key":"C","text":"Dánia","correct":false}]', '{"A":55,"B":30,"C":15}', 'A', 'mixed', 25),
('korny_177', 'Mi a fő oka a tengeri élővilág pusztulásának?', '[{"key":"A","text":"Túlhalászat","correct":true},{"key":"B","text":"Műanyag szennyezés","correct":false},{"key":"C","text":"Óceánok melegedése","correct":false}]', '{"A":55,"B":30,"C":15}', 'A', 'mixed', 25),
('korny_178', 'Melyik évben volt a Deepwater Horizon olajkatasztrófa?', '[{"key":"A","text":"2010","correct":true},{"key":"B","text":"2008","correct":false},{"key":"C","text":"2015","correct":false}]', '{"A":60,"B":25,"C":15}', 'A', 'mixed', 25),
('korny_179', 'Mi a biomassza energetikai felhasználásának hátránya?', '[{"key":"A","text":"Földhasználati konfliktusok","correct":true},{"key":"B","text":"Magas költségek","correct":false},{"key":"C","text":"Alacsony hatékonyság","correct":false}]', '{"A":50,"B":30,"C":20}', 'A', 'mixed', 25),
('korny_180', 'Melyik ország a legnagyobb e-hulladék termelő?', '[{"key":"A","text":"Kína","correct":true},{"key":"B","text":"USA","correct":false},{"key":"C","text":"India","correct":false}]', '{"A":60,"B":30,"C":10}', 'A', 'mixed', 25),
('korny_181', 'Mi a zöld hidrogén előállításának módja?', '[{"key":"A","text":"Megújuló energiával történő vízbontás","correct":true},{"key":"B","text":"Földgázból előállítás","correct":false},{"key":"C","text":"Szénből előállítás","correct":false}]', '{"A":70,"B":20,"C":10}', 'A', 'mixed', 25),
('korny_182', 'Melyik nemzetközi szervezet foglalkozik a biodiverzitás védelmével?', '[{"key":"A","text":"IUCN","correct":true},{"key":"B","text":"WWF","correct":false},{"key":"C","text":"UNEP","correct":false}]', '{"A":50,"B":35,"C":15}', 'A', 'mixed', 25),
('korny_183', 'Mi az ökológiai lábnyom mérésének egysége?', '[{"key":"A","text":"Globális hektár","correct":true},{"key":"B","text":"Négyzetméter","correct":false},{"key":"C","text":"Tonna CO2","correct":false}]', '{"A":55,"B":30,"C":15}', 'A', 'mixed', 25),
('korny_184', 'Melyik évben alapították a WWF-et?', '[{"key":"A","text":"1961","correct":true},{"key":"B","text":"1975","correct":false},{"key":"C","text":"1950","correct":false}]', '{"A":50,"B":35,"C":15}', 'A', 'mixed', 25),
('korny_185', 'Mi a fenntartható fejlődés három pillére?', '[{"key":"A","text":"Gazdasági, társadalmi és környezeti","correct":true},{"key":"B","text":"Energia, víz és levegő","correct":false},{"key":"C","text":"Ipar, mezőgazdaság és szolgáltatások","correct":false}]', '{"A":70,"B":20,"C":10}', 'A', 'mixed', 25),
('korny_186', 'Melyik ország vállalta a legambiciózusabb klímacélt 2030-ra?', '[{"key":"A","text":"Európai Unió","correct":true},{"key":"B","text":"Kína","correct":false},{"key":"C","text":"USA","correct":false}]', '{"A":55,"B":30,"C":15}', 'A', 'mixed', 25),
('korny_187', 'Mi a legjobb módszer a vízkészletek védelmére?', '[{"key":"A","text":"Vízgyűjtő területek védelme","correct":true},{"key":"B","text":"Víztisztító állomások építése","correct":false},{"key":"C","text":"Kutak fúrása","correct":false}]', '{"A":60,"B":25,"C":15}', 'A', 'mixed', 25),
('korny_188', 'Melyik évben volt a fukusimai atomkatasztrófa?', '[{"key":"A","text":"2011","correct":true},{"key":"B","text":"2008","correct":false},{"key":"C","text":"2015","correct":false}]', '{"A":75,"B":15,"C":10}', 'A', 'mixed', 25),
('korny_189', 'Mi a legnagyobb környezeti kihívás a városokban?', '[{"key":"A","text":"Légszennyezés","correct":true},{"key":"B","text":"Vízhiány","correct":false},{"key":"C","text":"Hulladékkezelés","correct":false}]', '{"A":60,"B":25,"C":15}', 'A', 'mixed', 25),
('korny_190', 'Melyik ország vezet az elektromos autók arányában?', '[{"key":"A","text":"Norvégia","correct":true},{"key":"B","text":"Kína","correct":false},{"key":"C","text":"Hollandia","correct":false}]', '{"A":70,"B":20,"C":10}', 'A', 'mixed', 25),
('korny_191', 'Mi az ESG rövidítés jelentése?', '[{"key":"A","text":"Környezet, társadalom, vállalatirányítás","correct":true},{"key":"B","text":"Energia, fenntarthatóság, növekedés","correct":false},{"key":"C","text":"Gazdaság, társadalom, kormányzás","correct":false}]', '{"A":60,"B":25,"C":15}', 'A', 'mixed', 25),
('korny_192', 'Melyik élőhely a leginkább veszélyeztetett a Földön?', '[{"key":"A","text":"Trópusi esőerdők","correct":true},{"key":"B","text":"Sivatagok","correct":false},{"key":"C","text":"Tundra","correct":false}]', '{"A":75,"B":15,"C":10}', 'A', 'mixed', 25),
('korny_193', 'Mi a leghatékonyabb módja a háztartási energiafogyasztás csökkentésének?', '[{"key":"A","text":"Hőszigetelés javítása","correct":true},{"key":"B","text":"LED izzók használata","correct":false},{"key":"C","text":"Napelem telepítése","correct":false}]', '{"A":55,"B":30,"C":15}', 'A', 'mixed', 25),
('korny_194', 'Melyik szervezet határozza meg a veszélyeztetett fajok listáját?', '[{"key":"A","text":"IUCN","correct":true},{"key":"B","text":"WWF","correct":false},{"key":"C","text":"CITES","correct":false}]', '{"A":55,"B":30,"C":15}', 'A', 'mixed', 25),
('korny_195', 'Mi a legfőbb oka a méhek pusztulásának?', '[{"key":"A","text":"Növényvédő szerek","correct":true},{"key":"B","text":"Klímaváltozás","correct":false},{"key":"C","text":"Élőhely-vesztés","correct":false}]', '{"A":60,"B":25,"C":15}', 'A', 'mixed', 25),
('korny_196', 'Melyik évben fogadták el a fenntartható fejlődési célokat (SDG)?', '[{"key":"A","text":"2015","correct":true},{"key":"B","text":"2010","correct":false},{"key":"C","text":"2020","correct":false}]', '{"A":55,"B":30,"C":15}', 'A', 'mixed', 25),
('korny_197', 'Mi a legjobb alternatíva a műanyag csomagolásra?', '[{"key":"A","text":"Biológiailag lebomló anyagok","correct":true},{"key":"B","text":"Papír","correct":false},{"key":"C","text":"Üveg","correct":false}]', '{"A":55,"B":30,"C":15}', 'A', 'mixed', 25),
('korny_198', 'Melyik ország rendelkezik a legnagyobb vízenergia kapacitással?', '[{"key":"A","text":"Kína","correct":true},{"key":"B","text":"Brazília","correct":false},{"key":"C","text":"Kanada","correct":false}]', '{"A":60,"B":25,"C":15}', 'A', 'mixed', 25),
('korny_199', 'Mi a permafroszt olvadásának legfőbb veszélye?', '[{"key":"A","text":"Metán felszabadulása","correct":true},{"key":"B","text":"Tengerszint emelkedés","correct":false},{"key":"C","text":"Árvizek","correct":false}]', '{"A":60,"B":25,"C":15}', 'A', 'mixed', 25),
('korny_200', 'Melyik nemzetközi megállapodás védi a veszélyeztetett fajok kereskedelmét?', '[{"key":"A","text":"CITES","correct":true},{"key":"B","text":"IUCN Vörös Lista","correct":false},{"key":"C","text":"CBD","correct":false}]', '{"A":55,"B":30,"C":15}', 'A', 'mixed', 25);

-- Topic 25 translations
INSERT INTO public.question_translations (question_id, lang, question_text, answer_a, answer_b, answer_c) VALUES
('korny_151', 'en', 'What is the largest greenhouse gas in the atmosphere?', 'Carbon dioxide (CO2)', 'Methane', 'Nitrous oxide'),
('korny_152', 'en', 'In which year was the Paris Climate Agreement signed?', '2015', '2012', '2018'),
('korny_153', 'en', 'What is the biggest threat to biodiversity loss?', 'Habitat destruction', 'Climate change', 'Pollution'),
('korny_154', 'en', 'Which country emits the most carbon dioxide?', 'China', 'USA', 'India'),
('korny_155', 'en', 'What is the main goal of the Kyoto Protocol?', 'Reducing greenhouse gas emissions', 'Closing the ozone hole', 'Stopping deforestation'),
('korny_156', 'en', 'In which year did the Chernobyl nuclear disaster occur?', '1986', '1979', '1992'),
('korny_157', 'en', 'What is the main cause of the ozone hole?', 'CFCs (chlorofluorocarbons)', 'Carbon dioxide', 'Methane'),
('korny_158', 'en', 'Which renewable energy source is growing fastest?', 'Solar energy', 'Wind energy', 'Hydropower'),
('korny_159', 'en', 'What is the name of the largest ocean plastic pollution area?', 'Great Pacific Garbage Patch', 'Atlantic Garbage Patch', 'Indian Ocean Garbage Patch'),
('korny_160', 'en', 'Which country has the most national parks?', 'Australia', 'USA', 'Brazil'),
('korny_161', 'en', 'What is the unit of measurement for carbon footprint?', 'Tonnes of CO2 equivalent', 'Kilowatt-hours', 'Liters of oil equivalent'),
('korny_162', 'en', 'In which year was Greenpeace founded?', '1971', '1985', '1960'),
('korny_163', 'en', 'What is the most important role of rainforests?', 'Carbon dioxide absorption and oxygen production', 'Freshwater storage', 'Medicinal plant cultivation'),
('korny_164', 'en', 'Which country has the most wind energy capacity?', 'China', 'USA', 'Germany'),
('korny_165', 'en', 'What is the main purpose of the Montreal Protocol?', 'Banning ozone-depleting substances', 'Fighting climate change', 'Reducing marine pollution'),
('korny_166', 'en', 'In which year was the first Earth Day?', '1970', '1980', '1965'),
('korny_167', 'en', 'What is the biggest threat to coral reefs?', 'Ocean warming and acidification', 'Overfishing', 'Plastic pollution'),
('korny_168', 'en', 'Which country leads in solar energy production?', 'China', 'USA', 'India'),
('korny_169', 'en', 'What is the essence of the circular economy?', 'Minimizing waste and maximizing recycling', 'Maintaining economic growth', 'Reducing imports'),
('korny_170', 'en', 'Which ecosystem stores the most carbon?', 'Peatlands', 'Rainforests', 'Oceans'),
('korny_171', 'en', 'What is the main cause of polar ice melting?', 'Global warming', 'Ozone hole', 'Changes in ocean currents'),
('korny_172', 'en', 'In which year was the Stockholm Convention on POPs signed?', '2001', '1995', '2008'),
('korny_173', 'en', 'What is the best way to reduce carbon dioxide emissions?', 'Using renewable energy', 'Building nuclear power plants', 'Planting forests'),
('korny_174', 'en', 'Which animal species is endangered due to climate change?', 'Polar bear', 'Elephant', 'Tiger'),
('korny_175', 'en', 'What does the abbreviation IPCC stand for?', 'Intergovernmental Panel on Climate Change', 'International Environmental Protection Committee', 'Global Climate Protection Organization'),
('korny_176', 'en', 'Which country is first in renewable energy share?', 'Iceland', 'Norway', 'Denmark'),
('korny_177', 'en', 'What is the main cause of marine life decline?', 'Overfishing', 'Plastic pollution', 'Ocean warming'),
('korny_178', 'en', 'In which year was the Deepwater Horizon oil disaster?', '2010', '2008', '2015'),
('korny_179', 'en', 'What is the disadvantage of using biomass for energy?', 'Land use conflicts', 'High costs', 'Low efficiency'),
('korny_180', 'en', 'Which country is the largest producer of e-waste?', 'China', 'USA', 'India'),
('korny_181', 'en', 'How is green hydrogen produced?', 'Water electrolysis using renewable energy', 'From natural gas', 'From coal'),
('korny_182', 'en', 'Which international organization deals with biodiversity protection?', 'IUCN', 'WWF', 'UNEP'),
('korny_183', 'en', 'What is the unit of measurement for ecological footprint?', 'Global hectares', 'Square meters', 'Tonnes of CO2'),
('korny_184', 'en', 'In which year was WWF founded?', '1961', '1975', '1950'),
('korny_185', 'en', 'What are the three pillars of sustainable development?', 'Economic, social and environmental', 'Energy, water and air', 'Industry, agriculture and services'),
('korny_186', 'en', 'Which entity has committed to the most ambitious climate goal for 2030?', 'European Union', 'China', 'USA'),
('korny_187', 'en', 'What is the best way to protect water resources?', 'Protecting watersheds', 'Building water treatment plants', 'Drilling wells'),
('korny_188', 'en', 'In which year was the Fukushima nuclear disaster?', '2011', '2008', '2015'),
('korny_189', 'en', 'What is the biggest environmental challenge in cities?', 'Air pollution', 'Water shortage', 'Waste management'),
('korny_190', 'en', 'Which country leads in electric vehicle share?', 'Norway', 'China', 'Netherlands'),
('korny_191', 'en', 'What does the abbreviation ESG stand for?', 'Environmental, Social, Governance', 'Energy, Sustainability, Growth', 'Economy, Society, Government'),
('korny_192', 'en', 'Which habitat is most endangered on Earth?', 'Tropical rainforests', 'Deserts', 'Tundra'),
('korny_193', 'en', 'What is the most effective way to reduce household energy consumption?', 'Improving insulation', 'Using LED bulbs', 'Installing solar panels'),
('korny_194', 'en', 'Which organization determines the list of endangered species?', 'IUCN', 'WWF', 'CITES'),
('korny_195', 'en', 'What is the main cause of bee population decline?', 'Pesticides', 'Climate change', 'Habitat loss'),
('korny_196', 'en', 'In which year were the Sustainable Development Goals (SDGs) adopted?', '2015', '2010', '2020'),
('korny_197', 'en', 'What is the best alternative to plastic packaging?', 'Biodegradable materials', 'Paper', 'Glass'),
('korny_198', 'en', 'Which country has the largest hydropower capacity?', 'China', 'Brazil', 'Canada'),
('korny_199', 'en', 'What is the main danger of permafrost melting?', 'Methane release', 'Sea level rise', 'Flooding'),
('korny_200', 'en', 'Which international agreement protects trade in endangered species?', 'CITES', 'IUCN Red List', 'CBD');
