
-- Topic 24: Közlekedés - 50 új kérdés
INSERT INTO public.questions (id, question, answers, audience, third, source_category, topic_id) VALUES
('kozl_151', 'Ki építette meg az első gőzmozdony vasútvonalat?', '[{"key":"A","text":"George Stephenson","correct":true},{"key":"B","text":"Richard Trevithick","correct":false},{"key":"C","text":"James Watt","correct":false}]', '{"A":65,"B":25,"C":10}', 'A', 'mixed', 24),
('kozl_152', 'Melyik évben indult meg a rendszeres repülőjárat?', '[{"key":"A","text":"1914","correct":true},{"key":"B","text":"1920","correct":false},{"key":"C","text":"1908","correct":false}]', '{"A":50,"B":35,"C":15}', 'A', 'mixed', 24),
('kozl_153', 'Ki alapította a Ford Motor Company-t?', '[{"key":"A","text":"Henry Ford","correct":true},{"key":"B","text":"Karl Benz","correct":false},{"key":"C","text":"Gottlieb Daimler","correct":false}]', '{"A":90,"B":5,"C":5}', 'A', 'mixed', 24),
('kozl_154', 'Melyik országban találták fel a kerékpárt?', '[{"key":"A","text":"Németország","correct":true},{"key":"B","text":"Franciaország","correct":false},{"key":"C","text":"Anglia","correct":false}]', '{"A":55,"B":30,"C":15}', 'A', 'mixed', 24),
('kozl_155', 'Mi volt az első tömeggyártott autó neve?', '[{"key":"A","text":"Ford Model T","correct":true},{"key":"B","text":"Volkswagen Beetle","correct":false},{"key":"C","text":"Chevrolet Series 490","correct":false}]', '{"A":80,"B":15,"C":5}', 'A', 'mixed', 24),
('kozl_156', 'Melyik évben nyitották meg a Szuezi-csatornát?', '[{"key":"A","text":"1869","correct":true},{"key":"B","text":"1880","correct":false},{"key":"C","text":"1856","correct":false}]', '{"A":60,"B":25,"C":15}', 'A', 'mixed', 24),
('kozl_157', 'Ki tervezte az első sikeres repülőgépet?', '[{"key":"A","text":"Wright fivérek","correct":true},{"key":"B","text":"Otto Lilienthal","correct":false},{"key":"C","text":"Samuel Langley","correct":false}]', '{"A":85,"B":10,"C":5}', 'A', 'mixed', 24),
('kozl_158', 'Melyik város rendelkezik a legrégebbi metróhálózattal?', '[{"key":"A","text":"London","correct":true},{"key":"B","text":"Párizs","correct":false},{"key":"C","text":"New York","correct":false}]', '{"A":70,"B":20,"C":10}', 'A', 'mixed', 24),
('kozl_159', 'Ki építette meg az első gőzhajót?', '[{"key":"A","text":"Robert Fulton","correct":true},{"key":"B","text":"James Watt","correct":false},{"key":"C","text":"John Fitch","correct":false}]', '{"A":55,"B":30,"C":15}', 'A', 'mixed', 24),
('kozl_160', 'Melyik évben indult az első transzkontinentális vasútvonal az USA-ban?', '[{"key":"A","text":"1869","correct":true},{"key":"B","text":"1880","correct":false},{"key":"C","text":"1855","correct":false}]', '{"A":55,"B":30,"C":15}', 'A', 'mixed', 24),
('kozl_161', 'Ki tervezte a Concorde szuperszonikus repülőgépet?', '[{"key":"A","text":"Brit-francia közös fejlesztés","correct":true},{"key":"B","text":"Boeing","correct":false},{"key":"C","text":"Airbus","correct":false}]', '{"A":65,"B":25,"C":10}', 'A', 'mixed', 24),
('kozl_162', 'Melyik országban gyártották először a Shinkansen gyorsvonatot?', '[{"key":"A","text":"Japán","correct":true},{"key":"B","text":"Kína","correct":false},{"key":"C","text":"Franciaország","correct":false}]', '{"A":85,"B":10,"C":5}', 'A', 'mixed', 24),
('kozl_163', 'Ki alapította a Tesla autógyárat?', '[{"key":"A","text":"Martin Eberhard és Marc Tarpenning","correct":true},{"key":"B","text":"Elon Musk","correct":false},{"key":"C","text":"JB Straubel","correct":false}]', '{"A":40,"B":50,"C":10}', 'A', 'mixed', 24),
('kozl_164', 'Melyik évben nyitották meg a Panama-csatornát?', '[{"key":"A","text":"1914","correct":true},{"key":"B","text":"1900","correct":false},{"key":"C","text":"1920","correct":false}]', '{"A":60,"B":25,"C":15}', 'A', 'mixed', 24),
('kozl_165', 'Ki fejlesztette ki az első dízelmotor?', '[{"key":"A","text":"Rudolf Diesel","correct":true},{"key":"B","text":"Nikolaus Otto","correct":false},{"key":"C","text":"Karl Benz","correct":false}]', '{"A":80,"B":15,"C":5}', 'A', 'mixed', 24),
('kozl_166', 'Melyik város rendelkezik a leghosszabb metróhálózattal?', '[{"key":"A","text":"Shanghai","correct":true},{"key":"B","text":"Peking","correct":false},{"key":"C","text":"London","correct":false}]', '{"A":55,"B":30,"C":15}', 'A', 'mixed', 24),
('kozl_167', 'Ki tervezte a Titanic óceánjárót?', '[{"key":"A","text":"Thomas Andrews","correct":true},{"key":"B","text":"Alexander Carlisle","correct":false},{"key":"C","text":"Bruce Ismay","correct":false}]', '{"A":60,"B":25,"C":15}', 'A', 'mixed', 24),
('kozl_168', 'Melyik évben repült először a Boeing 747?', '[{"key":"A","text":"1969","correct":true},{"key":"B","text":"1975","correct":false},{"key":"C","text":"1962","correct":false}]', '{"A":55,"B":30,"C":15}', 'A', 'mixed', 24),
('kozl_169', 'Ki építette meg az első autópályát?', '[{"key":"A","text":"Németország (Autobahn)","correct":true},{"key":"B","text":"USA","correct":false},{"key":"C","text":"Olaszország","correct":false}]', '{"A":65,"B":25,"C":10}', 'A', 'mixed', 24),
('kozl_170', 'Melyik városban nyitották meg az első villamos vonalat?', '[{"key":"A","text":"Berlin","correct":true},{"key":"B","text":"Párizs","correct":false},{"key":"C","text":"London","correct":false}]', '{"A":50,"B":30,"C":20}', 'A', 'mixed', 24),
('kozl_171', 'Ki tervezte az A380 superjumbo repülőgépet?', '[{"key":"A","text":"Airbus","correct":true},{"key":"B","text":"Boeing","correct":false},{"key":"C","text":"Lockheed Martin","correct":false}]', '{"A":75,"B":20,"C":5}', 'A', 'mixed', 24),
('kozl_172', 'Melyik évben indult az első kereskedelmi sugárhajtású járat?', '[{"key":"A","text":"1952","correct":true},{"key":"B","text":"1960","correct":false},{"key":"C","text":"1945","correct":false}]', '{"A":50,"B":35,"C":15}', 'A', 'mixed', 24),
('kozl_173', 'Ki alapította a SpaceX űrközlekedési vállalatot?', '[{"key":"A","text":"Elon Musk","correct":true},{"key":"B","text":"Jeff Bezos","correct":false},{"key":"C","text":"Richard Branson","correct":false}]', '{"A":90,"B":5,"C":5}', 'A', 'mixed', 24),
('kozl_174', 'Melyik országban közlekedik a leghosszabb nagysebességű vasúthálózat?', '[{"key":"A","text":"Kína","correct":true},{"key":"B","text":"Japán","correct":false},{"key":"C","text":"Franciaország","correct":false}]', '{"A":70,"B":20,"C":10}', 'A', 'mixed', 24),
('kozl_175', 'Ki találta fel a léghajót?', '[{"key":"A","text":"Ferdinand von Zeppelin","correct":true},{"key":"B","text":"Henri Giffard","correct":false},{"key":"C","text":"Alberto Santos-Dumont","correct":false}]', '{"A":70,"B":20,"C":10}', 'A', 'mixed', 24),
('kozl_176', 'Melyik évben indult az első helikopterszolgálat?', '[{"key":"A","text":"1946","correct":true},{"key":"B","text":"1955","correct":false},{"key":"C","text":"1938","correct":false}]', '{"A":50,"B":35,"C":15}', 'A', 'mixed', 24),
('kozl_177', 'Ki fejlesztette ki az elektromos autó akkumulátorát?', '[{"key":"A","text":"Gaston Planté","correct":true},{"key":"B","text":"Thomas Edison","correct":false},{"key":"C","text":"Alessandro Volta","correct":false}]', '{"A":45,"B":35,"C":20}', 'A', 'mixed', 24),
('kozl_178', 'Melyik város rendelkezik a legnagyobb kikötővel?', '[{"key":"A","text":"Shanghai","correct":true},{"key":"B","text":"Szingapúr","correct":false},{"key":"C","text":"Rotterdam","correct":false}]', '{"A":60,"B":25,"C":15}', 'A', 'mixed', 24),
('kozl_179', 'Ki tervezte a TGV francia nagysebességű vonatot?', '[{"key":"A","text":"SNCF és Alstom","correct":true},{"key":"B","text":"Siemens","correct":false},{"key":"C","text":"Bombardier","correct":false}]', '{"A":55,"B":30,"C":15}', 'A', 'mixed', 24),
('kozl_180', 'Melyik évben indult az első űrhajó?', '[{"key":"A","text":"1961","correct":true},{"key":"B","text":"1957","correct":false},{"key":"C","text":"1969","correct":false}]', '{"A":65,"B":25,"C":10}', 'A', 'mixed', 24),
('kozl_181', 'Ki fejlesztette ki a négytaktusos motort?', '[{"key":"A","text":"Nikolaus Otto","correct":true},{"key":"B","text":"Rudolf Diesel","correct":false},{"key":"C","text":"Karl Benz","correct":false}]', '{"A":60,"B":25,"C":15}', 'A', 'mixed', 24),
('kozl_182', 'Melyik országban gyártották először a Hyperloop rendszert?', '[{"key":"A","text":"USA","correct":true},{"key":"B","text":"Japán","correct":false},{"key":"C","text":"Kína","correct":false}]', '{"A":70,"B":20,"C":10}', 'A', 'mixed', 24),
('kozl_183', 'Ki alapította a Virgin Atlantic légitársaságot?', '[{"key":"A","text":"Richard Branson","correct":true},{"key":"B","text":"Freddie Laker","correct":false},{"key":"C","text":"Willie Walsh","correct":false}]', '{"A":75,"B":15,"C":10}', 'A', 'mixed', 24),
('kozl_184', 'Melyik évben nyílt meg az Eurotunnel?', '[{"key":"A","text":"1994","correct":true},{"key":"B","text":"1990","correct":false},{"key":"C","text":"2000","correct":false}]', '{"A":60,"B":25,"C":15}', 'A', 'mixed', 24),
('kozl_185', 'Ki tervezte az első sikeres motorkerékpárt?', '[{"key":"A","text":"Gottlieb Daimler és Wilhelm Maybach","correct":true},{"key":"B","text":"Karl Benz","correct":false},{"key":"C","text":"Hildebrand és Wolfmüller","correct":false}]', '{"A":55,"B":30,"C":15}', 'A', 'mixed', 24),
('kozl_186', 'Melyik város rendelkezik a legnagyobb repülőtérrel?', '[{"key":"A","text":"Isztambul","correct":true},{"key":"B","text":"Dubai","correct":false},{"key":"C","text":"Peking","correct":false}]', '{"A":50,"B":35,"C":15}', 'A', 'mixed', 24),
('kozl_187', 'Ki fejlesztette ki a mágnesvonat technológiát?', '[{"key":"A","text":"Eric Laithwaite","correct":true},{"key":"B","text":"Werner von Siemens","correct":false},{"key":"C","text":"Shinkansen mérnökök","correct":false}]', '{"A":45,"B":35,"C":20}', 'A', 'mixed', 24),
('kozl_188', 'Melyik évben repült először űrrepülőgép?', '[{"key":"A","text":"1981","correct":true},{"key":"B","text":"1975","correct":false},{"key":"C","text":"1990","correct":false}]', '{"A":60,"B":25,"C":15}', 'A', 'mixed', 24),
('kozl_189', 'Ki alapította az Uber közlekedési platformot?', '[{"key":"A","text":"Travis Kalanick és Garrett Camp","correct":true},{"key":"B","text":"Elon Musk","correct":false},{"key":"C","text":"Jeff Bezos","correct":false}]', '{"A":60,"B":25,"C":15}', 'A', 'mixed', 24),
('kozl_190', 'Melyik országban gyártják a legtöbb autót?', '[{"key":"A","text":"Kína","correct":true},{"key":"B","text":"USA","correct":false},{"key":"C","text":"Japán","correct":false}]', '{"A":70,"B":20,"C":10}', 'A', 'mixed', 24),
('kozl_191', 'Ki tervezte a Boeing 787 Dreamliner repülőgépet?', '[{"key":"A","text":"Boeing","correct":true},{"key":"B","text":"Airbus","correct":false},{"key":"C","text":"Lockheed Martin","correct":false}]', '{"A":80,"B":15,"C":5}', 'A', 'mixed', 24),
('kozl_192', 'Melyik évben indult az első elektromos villamos?', '[{"key":"A","text":"1881","correct":true},{"key":"B","text":"1895","correct":false},{"key":"C","text":"1870","correct":false}]', '{"A":55,"B":30,"C":15}', 'A', 'mixed', 24),
('kozl_193', 'Ki fejlesztette ki a GPS navigációs rendszert?', '[{"key":"A","text":"US Department of Defense","correct":true},{"key":"B","text":"NASA","correct":false},{"key":"C","text":"DARPA","correct":false}]', '{"A":65,"B":25,"C":10}', 'A', 'mixed', 24),
('kozl_194', 'Melyik város rendelkezik a legsűrűbb tömegközlekedéssel?', '[{"key":"A","text":"Hongkong","correct":true},{"key":"B","text":"Tokió","correct":false},{"key":"C","text":"New York","correct":false}]', '{"A":55,"B":30,"C":15}', 'A', 'mixed', 24),
('kozl_195', 'Ki alapította a Waymo önvezető autó vállalatot?', '[{"key":"A","text":"Google (Alphabet)","correct":true},{"key":"B","text":"Tesla","correct":false},{"key":"C","text":"Apple","correct":false}]', '{"A":65,"B":25,"C":10}', 'A', 'mixed', 24),
('kozl_196', 'Melyik évben indult az első konténerhajó?', '[{"key":"A","text":"1956","correct":true},{"key":"B","text":"1965","correct":false},{"key":"C","text":"1945","correct":false}]', '{"A":50,"B":35,"C":15}', 'A', 'mixed', 24),
('kozl_197', 'Ki tervezte a Bugatti Veyron szuperautót?', '[{"key":"A","text":"Bugatti / Volkswagen Group","correct":true},{"key":"B","text":"Ferrari","correct":false},{"key":"C","text":"Lamborghini","correct":false}]', '{"A":65,"B":20,"C":15}', 'A', 'mixed', 24),
('kozl_198', 'Melyik országban közlekedik a legtöbb elektromos autó?', '[{"key":"A","text":"Kína","correct":true},{"key":"B","text":"Norvégia","correct":false},{"key":"C","text":"USA","correct":false}]', '{"A":60,"B":25,"C":15}', 'A', 'mixed', 24),
('kozl_199', 'Ki fejlesztette ki a Segway-t?', '[{"key":"A","text":"Dean Kamen","correct":true},{"key":"B","text":"Shane Chen","correct":false},{"key":"C","text":"Elon Musk","correct":false}]', '{"A":55,"B":30,"C":15}', 'A', 'mixed', 24),
('kozl_200', 'Melyik évben repült először drón kereskedelmi célra?', '[{"key":"A","text":"2013","correct":true},{"key":"B","text":"2018","correct":false},{"key":"C","text":"2008","correct":false}]', '{"A":50,"B":35,"C":15}', 'A', 'mixed', 24);

-- Topic 24 translations
INSERT INTO public.question_translations (question_id, lang, question_text, answer_a, answer_b, answer_c) VALUES
('kozl_151', 'en', 'Who built the first steam locomotive railway line?', 'George Stephenson', 'Richard Trevithick', 'James Watt'),
('kozl_152', 'en', 'In which year did the first regular airline service begin?', '1914', '1920', '1908'),
('kozl_153', 'en', 'Who founded the Ford Motor Company?', 'Henry Ford', 'Karl Benz', 'Gottlieb Daimler'),
('kozl_154', 'en', 'In which country was the bicycle invented?', 'Germany', 'France', 'England'),
('kozl_155', 'en', 'What was the first mass-produced car?', 'Ford Model T', 'Volkswagen Beetle', 'Chevrolet Series 490'),
('kozl_156', 'en', 'In which year was the Suez Canal opened?', '1869', '1880', '1856'),
('kozl_157', 'en', 'Who designed the first successful airplane?', 'Wright brothers', 'Otto Lilienthal', 'Samuel Langley'),
('kozl_158', 'en', 'Which city has the oldest metro network?', 'London', 'Paris', 'New York'),
('kozl_159', 'en', 'Who built the first steamboat?', 'Robert Fulton', 'James Watt', 'John Fitch'),
('kozl_160', 'en', 'In which year was the first transcontinental railroad completed in the USA?', '1869', '1880', '1855'),
('kozl_161', 'en', 'Who designed the Concorde supersonic aircraft?', 'British-French joint development', 'Boeing', 'Airbus'),
('kozl_162', 'en', 'In which country was the Shinkansen bullet train first produced?', 'Japan', 'China', 'France'),
('kozl_163', 'en', 'Who founded the Tesla car company?', 'Martin Eberhard and Marc Tarpenning', 'Elon Musk', 'JB Straubel'),
('kozl_164', 'en', 'In which year was the Panama Canal opened?', '1914', '1900', '1920'),
('kozl_165', 'en', 'Who developed the first diesel engine?', 'Rudolf Diesel', 'Nikolaus Otto', 'Karl Benz'),
('kozl_166', 'en', 'Which city has the longest metro network?', 'Shanghai', 'Beijing', 'London'),
('kozl_167', 'en', 'Who designed the Titanic ocean liner?', 'Thomas Andrews', 'Alexander Carlisle', 'Bruce Ismay'),
('kozl_168', 'en', 'In which year did the Boeing 747 first fly?', '1969', '1975', '1962'),
('kozl_169', 'en', 'Which country built the first highway?', 'Germany (Autobahn)', 'USA', 'Italy'),
('kozl_170', 'en', 'In which city was the first electric tram line opened?', 'Berlin', 'Paris', 'London'),
('kozl_171', 'en', 'Who designed the A380 superjumbo aircraft?', 'Airbus', 'Boeing', 'Lockheed Martin'),
('kozl_172', 'en', 'In which year did the first commercial jet service begin?', '1952', '1960', '1945'),
('kozl_173', 'en', 'Who founded SpaceX?', 'Elon Musk', 'Jeff Bezos', 'Richard Branson'),
('kozl_174', 'en', 'Which country has the longest high-speed rail network?', 'China', 'Japan', 'France'),
('kozl_175', 'en', 'Who invented the airship?', 'Ferdinand von Zeppelin', 'Henri Giffard', 'Alberto Santos-Dumont'),
('kozl_176', 'en', 'In which year did the first helicopter service begin?', '1946', '1955', '1938'),
('kozl_177', 'en', 'Who developed the electric car battery?', 'Gaston Planté', 'Thomas Edison', 'Alessandro Volta'),
('kozl_178', 'en', 'Which city has the largest port?', 'Shanghai', 'Singapore', 'Rotterdam'),
('kozl_179', 'en', 'Who designed the TGV French high-speed train?', 'SNCF and Alstom', 'Siemens', 'Bombardier'),
('kozl_180', 'en', 'In which year did the first spacecraft launch?', '1961', '1957', '1969'),
('kozl_181', 'en', 'Who developed the four-stroke engine?', 'Nikolaus Otto', 'Rudolf Diesel', 'Karl Benz'),
('kozl_182', 'en', 'In which country was the Hyperloop system first developed?', 'USA', 'Japan', 'China'),
('kozl_183', 'en', 'Who founded Virgin Atlantic airline?', 'Richard Branson', 'Freddie Laker', 'Willie Walsh'),
('kozl_184', 'en', 'In which year did the Eurotunnel open?', '1994', '1990', '2000'),
('kozl_185', 'en', 'Who designed the first successful motorcycle?', 'Gottlieb Daimler and Wilhelm Maybach', 'Karl Benz', 'Hildebrand and Wolfmüller'),
('kozl_186', 'en', 'Which city has the largest airport?', 'Istanbul', 'Dubai', 'Beijing'),
('kozl_187', 'en', 'Who developed maglev train technology?', 'Eric Laithwaite', 'Werner von Siemens', 'Shinkansen engineers'),
('kozl_188', 'en', 'In which year did the Space Shuttle first fly?', '1981', '1975', '1990'),
('kozl_189', 'en', 'Who founded the Uber transportation platform?', 'Travis Kalanick and Garrett Camp', 'Elon Musk', 'Jeff Bezos'),
('kozl_190', 'en', 'Which country manufactures the most cars?', 'China', 'USA', 'Japan'),
('kozl_191', 'en', 'Who designed the Boeing 787 Dreamliner?', 'Boeing', 'Airbus', 'Lockheed Martin'),
('kozl_192', 'en', 'In which year did the first electric tram operate?', '1881', '1895', '1870'),
('kozl_193', 'en', 'Who developed the GPS navigation system?', 'US Department of Defense', 'NASA', 'DARPA'),
('kozl_194', 'en', 'Which city has the densest public transportation?', 'Hong Kong', 'Tokyo', 'New York'),
('kozl_195', 'en', 'Who founded Waymo self-driving car company?', 'Google (Alphabet)', 'Tesla', 'Apple'),
('kozl_196', 'en', 'In which year did the first container ship sail?', '1956', '1965', '1945'),
('kozl_197', 'en', 'Who designed the Bugatti Veyron supercar?', 'Bugatti / Volkswagen Group', 'Ferrari', 'Lamborghini'),
('kozl_198', 'en', 'Which country has the most electric cars?', 'China', 'Norway', 'USA'),
('kozl_199', 'en', 'Who developed the Segway?', 'Dean Kamen', 'Shane Chen', 'Elon Musk'),
('kozl_200', 'en', 'In which year was a drone first used commercially?', '2013', '2018', '2008');
