
-- Add missing English translations for Topic 22 (tech 151c-200c)
INSERT INTO question_translations (question_id, lang, question_text, answer_a, answer_b, answer_c)
VALUES
('tech_151c', 'en', 'What is the basis of quantum computing?', 'Binary bits', 'Quantum bits (qubits)', 'Analog signals'),
('tech_152c', 'en', 'Which company originally developed Android?', 'Google', 'Android Inc.', 'Apple'),
('tech_153c', 'en', 'What is the main advantage of 5G technology?', 'Lower cost', 'Higher speed and lower latency', 'Better battery life'),
('tech_154c', 'en', 'What is NFC technology?', 'Long-range communication', 'Near Field Communication', 'Network encryption'),
('tech_155c', 'en', 'What is the typical Bluetooth range?', '10 meters', '100 meters', '1 kilometer'),
('tech_156c', 'en', 'What is the advantage of e-ink technology?', 'Colorful display', 'Low power consumption', 'Fast refresh rate'),
('tech_157c', 'en', 'What is the function of BIOS?', 'Run applications', 'Initialize hardware on startup', 'Browse internet'),
('tech_158c', 'en', 'What is the advantage of OLED displays?', 'Cheaper production', 'True blacks and contrast', 'Longer lifespan'),
('tech_159c', 'en', 'What is a mesh network?', 'Star topology', 'Distributed wireless network', 'Wired network'),
('tech_160c', 'en', 'What is a chatbot?', 'Video chat app', 'Automated conversation software', 'Social media'),
('tech_161c', 'en', 'What is the advantage of IPv6 over IPv4?', 'Faster speed', 'More IP addresses', 'Better graphics'),
('tech_162c', 'en', 'What is the function of cache memory?', 'Permanent storage', 'Speed up data access', 'Backup storage'),
('tech_163c', 'en', 'What is a deepfake?', 'Security feature', 'AI-generated fake media', 'Database type'),
('tech_164c', 'en', 'What is LiDAR technology?', 'Sound-based detection', 'Light-based distance measurement', 'Radio waves'),
('tech_165c', 'en', 'What is ransomware?', 'Antivirus', 'Malware that encrypts files for ransom', 'Operating system'),
('tech_166c', 'en', 'What is two-factor authentication?', 'Single password', 'Two verification methods', 'Biometric only'),
('tech_167c', 'en', 'What is augmented reality (AR)?', 'Full virtual world', 'Digital overlay on real world', 'Video game'),
('tech_168c', 'en', 'What is the advantage of cloud storage?', 'Requires hardware', 'Access from anywhere', 'No internet needed'),
('tech_169c', 'en', 'What is biometric identification?', 'Password', 'Body-based identification', 'Key card'),
('tech_170c', 'en', 'What is a smart home?', 'Regular house', 'Connected automated home', 'Mobile home'),
('tech_171c', 'en', 'What is a DDoS attack?', 'Virus', 'Overwhelming server with traffic', 'Phishing'),
('tech_172c', 'en', 'What is an e-wallet?', 'Physical wallet', 'Digital payment system', 'Bank account'),
('tech_173c', 'en', 'What is a QR code?', 'Barcode type', 'Two-dimensional scannable code', 'Password'),
('tech_174c', 'en', 'What is a podcast?', 'Video game', 'Digital audio program', 'Social media'),
('tech_175c', 'en', 'What is streaming technology?', 'Download then play', 'Real-time content delivery', 'File storage'),
('tech_176c', 'en', 'What is wearable technology?', 'Clothing', 'Electronic devices worn on body', 'Fashion'),
('tech_177c', 'en', 'What type of AI is ChatGPT?', 'Image recognition', 'Large language model', 'Search engine'),
('tech_178c', 'en', 'What is edge computing?', 'Cloud computing', 'Processing data near source', 'Central server'),
('tech_179c', 'en', 'What is a neural network?', 'Physical network', 'AI modeled on brain structure', 'Social network'),
('tech_180c', 'en', 'What is a sandbox in computing?', 'Game', 'Isolated testing environment', 'Storage device'),
('tech_181c', 'en', 'What is cryptocurrency?', 'Physical money', 'Digital decentralized currency', 'Bank transfer'),
('tech_182c', 'en', 'What is an NFT?', 'Currency', 'Non-fungible token', 'File format'),
('tech_183c', 'en', 'What is the metaverse?', 'Social media', 'Virtual shared space', 'Video game'),
('tech_184c', 'en', 'What is a bot?', 'Human operator', 'Automated software program', 'Website'),
('tech_185c', 'en', 'What is the dark web?', 'Regular internet', 'Hidden encrypted network', 'Social media'),
('tech_186c', 'en', 'What is a firewall?', 'Physical wall', 'Network security system', 'Antivirus'),
('tech_187c', 'en', 'What is a proxy server?', 'Main server', 'Intermediary server', 'Storage server'),
('tech_188c', 'en', 'What is spam?', 'Useful email', 'Unwanted bulk messages', 'Newsletter'),
('tech_189c', 'en', 'What is a cookie on websites?', 'Food', 'Data stored on browser', 'Virus'),
('tech_190c', 'en', 'What is UX design?', 'Graphic design', 'User experience design', 'Web development'),
('tech_191c', 'en', 'What is an algorithm?', 'Hardware', 'Step-by-step instructions', 'Programming language'),
('tech_192c', 'en', 'What is bandwidth?', 'Storage space', 'Data transfer capacity', 'Processing speed'),
('tech_193c', 'en', 'What is encryption?', 'Compression', 'Converting data to secure format', 'Deletion'),
('tech_194c', 'en', 'What is latency?', 'Speed', 'Delay in data transfer', 'Bandwidth'),
('tech_195c', 'en', 'What is open source software?', 'Paid software', 'Freely available source code', 'Closed source'),
('tech_196c', 'en', 'What is debugging?', 'Adding features', 'Finding and fixing errors', 'Testing'),
('tech_197c', 'en', 'What is a repository?', 'Database', 'Code storage location', 'Server'),
('tech_198c', 'en', 'What is a framework?', 'Operating system', 'Development foundation structure', 'Programming language'),
('tech_199c', 'en', 'What is the backend?', 'User interface', 'Server-side processing', 'Database'),
('tech_200c', 'en', 'What is the frontend?', 'Server code', 'User-facing interface', 'Database')
ON CONFLICT (question_id, lang) DO NOTHING;

-- Add missing English translations for Topic 27 (travel 151-200)
INSERT INTO question_translations (question_id, lang, question_text, answer_a, answer_b, answer_c)
VALUES
('travel_151', 'en', 'Which country has Reykjavik as its capital?', 'Norway', 'Iceland', 'Finland'),
('travel_152', 'en', 'On which continent is Machu Picchu located?', 'Asia', 'South America', 'Africa'),
('travel_153', 'en', 'Which city is famous for the Colosseum?', 'Athens', 'Rome', 'Paris'),
('travel_154', 'en', 'In which country is Santorini island located?', 'Italy', 'Greece', 'Turkey'),
('travel_155', 'en', 'Which city is famous for Big Ben?', 'Paris', 'London', 'Berlin'),
('travel_156', 'en', 'In which country is the Taj Mahal located?', 'Pakistan', 'India', 'Bangladesh'),
('travel_157', 'en', 'Which country has Canberra as its capital?', 'New Zealand', 'Australia', 'Canada'),
('travel_158', 'en', 'In which city is the Louvre museum?', 'London', 'Paris', 'Madrid'),
('travel_159', 'en', 'In which country is the Sagrada Familia?', 'Portugal', 'Spain', 'Italy'),
('travel_160', 'en', 'Which country has Ottawa as its capital?', 'USA', 'Canada', 'UK'),
('travel_161', 'en', 'In which city is the Brandenburg Gate?', 'Vienna', 'Berlin', 'Munich'),
('travel_162', 'en', 'In which country is Mount Fuji?', 'China', 'Japan', 'Korea'),
('travel_163', 'en', 'Which country has Lisbon as its capital?', 'Spain', 'Portugal', 'Brazil'),
('travel_164', 'en', 'In which city is St. Peters Basilica?', 'Rome', 'Vatican City', 'Florence'),
('travel_165', 'en', 'In which country is the Grand Canyon?', 'Mexico', 'USA', 'Canada'),
('travel_166', 'en', 'Which city is famous for Burj Khalifa?', 'Abu Dhabi', 'Dubai', 'Doha'),
('travel_167', 'en', 'Which country has Vienna as its capital?', 'Germany', 'Austria', 'Switzerland'),
('travel_168', 'en', 'In which city is the Anne Frank House?', 'Brussels', 'Amsterdam', 'Copenhagen'),
('travel_169', 'en', 'In which country is the ancient city of Petra?', 'Egypt', 'Jordan', 'Israel'),
('travel_170', 'en', 'Which country has Wellington as its capital?', 'Australia', 'New Zealand', 'Fiji'),
('travel_171', 'en', 'In which city is the Kremlin?', 'St. Petersburg', 'Moscow', 'Kiev'),
('travel_172', 'en', 'In which country is Niagara Falls?', 'USA only', 'USA and Canada', 'Canada only'),
('travel_173', 'en', 'Which city is famous for the Acropolis?', 'Rome', 'Athens', 'Istanbul'),
('travel_174', 'en', 'In which country is Angkor Wat?', 'Thailand', 'Cambodia', 'Vietnam'),
('travel_175', 'en', 'Which country has Brasilia as its capital?', 'Argentina', 'Brazil', 'Colombia'),
('travel_176', 'en', 'In which city is the Sistine Chapel?', 'Rome', 'Vatican City', 'Florence'),
('travel_177', 'en', 'In which country is the Matterhorn?', 'France', 'Switzerland', 'Italy'),
('travel_178', 'en', 'Which city is famous for the Golden Gate Bridge?', 'Los Angeles', 'San Francisco', 'New York'),
('travel_179', 'en', 'In which country is the Ha Long Bay?', 'Thailand', 'Vietnam', 'Malaysia'),
('travel_180', 'en', 'Which country has Cairo as its capital?', 'Libya', 'Egypt', 'Sudan'),
('travel_181', 'en', 'In which city is the Hermitage Museum?', 'Moscow', 'St. Petersburg', 'Kiev'),
('travel_182', 'en', 'In which country is Bali island?', 'Thailand', 'Indonesia', 'Philippines'),
('travel_183', 'en', 'Which city is famous for the Statue of Liberty?', 'Washington', 'New York', 'Boston'),
('travel_184', 'en', 'In which country is the Serengeti?', 'Kenya', 'Tanzania', 'South Africa'),
('travel_185', 'en', 'Which country has Stockholm as its capital?', 'Norway', 'Sweden', 'Denmark'),
('travel_186', 'en', 'In which city is the Prado Museum?', 'Barcelona', 'Madrid', 'Lisbon'),
('travel_187', 'en', 'In which country is the Great Barrier Reef?', 'New Zealand', 'Australia', 'Indonesia'),
('travel_188', 'en', 'Which city is famous for the Parthenon?', 'Rome', 'Athens', 'Istanbul'),
('travel_189', 'en', 'In which country is Mont Blanc?', 'Switzerland', 'France', 'Italy'),
('travel_190', 'en', 'Which country has Dublin as its capital?', 'Scotland', 'Ireland', 'Wales'),
('travel_191', 'en', 'In which city is the Uffizi Gallery?', 'Rome', 'Florence', 'Venice'),
('travel_192', 'en', 'In which country is the Galapagos Islands?', 'Peru', 'Ecuador', 'Colombia'),
('travel_193', 'en', 'Which city is famous for the Hagia Sophia?', 'Athens', 'Istanbul', 'Ankara'),
('travel_194', 'en', 'In which country is Victoria Falls?', 'South Africa', 'Zambia and Zimbabwe', 'Botswana'),
('travel_195', 'en', 'Which country has Copenhagen as its capital?', 'Sweden', 'Denmark', 'Norway'),
('travel_196', 'en', 'In which city is Tower Bridge?', 'Paris', 'London', 'Dublin'),
('travel_197', 'en', 'In which country is the Amazon rainforest mostly?', 'Peru', 'Brazil', 'Colombia'),
('travel_198', 'en', 'Which city is famous for the Christ the Redeemer?', 'Buenos Aires', 'Rio de Janeiro', 'Sao Paulo'),
('travel_199', 'en', 'In which country is the Blue Lagoon spa?', 'Norway', 'Iceland', 'Finland'),
('travel_200', 'en', 'Which country has Bangkok as its capital?', 'Vietnam', 'Thailand', 'Cambodia')
ON CONFLICT (question_id, lang) DO NOTHING;
