
-- Topic 30 (Pszichológia) - psych_151 to psych_200 English translations
INSERT INTO question_translations (question_id, lang, question_text, answer_a, answer_b, answer_c) VALUES
('psych_151', 'en', 'Who founded psychoanalysis?', 'Sigmund Freud', 'Carl Jung', 'Alfred Adler'),
('psych_152', 'en', 'What is classical conditioning?', 'Learning through association', 'Learning through reward', 'Learning through observation'),
('psych_153', 'en', 'Who conducted the Stanford prison experiment?', 'Philip Zimbardo', 'Stanley Milgram', 'Solomon Asch'),
('psych_154', 'en', 'What is the unconscious mind?', 'Hidden mental processes', 'Sleep state', 'Coma'),
('psych_155', 'en', 'What is cognitive dissonance?', 'Discomfort from conflicting beliefs', 'Memory loss', 'Learning disability'),
('psych_156', 'en', 'Who developed the hierarchy of needs?', 'Abraham Maslow', 'Carl Rogers', 'Erik Erikson'),
('psych_157', 'en', 'What is operant conditioning?', 'Learning through consequences', 'Learning through association', 'Learning through insight'),
('psych_158', 'en', 'Who conducted the obedience experiments?', 'Stanley Milgram', 'Philip Zimbardo', 'Solomon Asch'),
('psych_159', 'en', 'What is the id in Freuds theory?', 'Primitive desires', 'Moral conscience', 'Rational self'),
('psych_160', 'en', 'What is attachment theory about?', 'Early bonds affect development', 'Physical connections', 'Email attachments'),
('psych_161', 'en', 'Who developed analytical psychology?', 'Carl Jung', 'Sigmund Freud', 'Alfred Adler'),
('psych_162', 'en', 'What is the bystander effect?', 'Less help when others present', 'Crowd behavior', 'Traffic psychology'),
('psych_163', 'en', 'What is short-term memory capacity?', '7 plus or minus 2 items', 'Unlimited', '3 items'),
('psych_164', 'en', 'Who founded behaviorism?', 'John Watson', 'B.F. Skinner', 'Ivan Pavlov'),
('psych_165', 'en', 'What is the placebo effect?', 'Improvement from believing in treatment', 'Drug interaction', 'Allergic reaction'),
('psych_166', 'en', 'What is confirmation bias?', 'Seeking info that confirms beliefs', 'Random error', 'Memory distortion'),
('psych_167', 'en', 'Who developed the stages of psychosocial development?', 'Erik Erikson', 'Jean Piaget', 'Lawrence Kohlberg'),
('psych_168', 'en', 'What is REM sleep?', 'Rapid eye movement dream stage', 'Deep sleep', 'Light sleep'),
('psych_169', 'en', 'What is the Rorschach test?', 'Inkblot interpretation test', 'IQ test', 'Personality questionnaire'),
('psych_170', 'en', 'Who developed client-centered therapy?', 'Carl Rogers', 'Albert Ellis', 'Aaron Beck'),
('psych_171', 'en', 'What is learned helplessness?', 'Giving up after repeated failure', 'Study technique', 'Teaching method'),
('psych_172', 'en', 'What is the halo effect?', 'One trait affects overall impression', 'Lighting illusion', 'Religious experience'),
('psych_173', 'en', 'Who developed cognitive behavioral therapy?', 'Aaron Beck', 'Albert Ellis', 'Carl Rogers'),
('psych_174', 'en', 'What is the fight or flight response?', 'Stress reaction to danger', 'Argument style', 'Travel decision'),
('psych_175', 'en', 'What is neuroplasticity?', 'Brains ability to change', 'Brain surgery', 'Nerve damage'),
('psych_176', 'en', 'Who studied the stages of cognitive development?', 'Jean Piaget', 'Erik Erikson', 'Lawrence Kohlberg'),
('psych_177', 'en', 'What is repression in psychology?', 'Pushing painful memories away', 'Political oppression', 'Economic suppression'),
('psych_178', 'en', 'What is the fundamental attribution error?', 'Overestimating personality vs situation', 'Math mistake', 'Logic error'),
('psych_179', 'en', 'Who discovered split-brain research?', 'Roger Sperry', 'Paul Broca', 'Carl Wernicke'),
('psych_180', 'en', 'What is positive reinforcement?', 'Adding reward to increase behavior', 'Removing punishment', 'Positive thinking'),
('psych_181', 'en', 'What is the mere exposure effect?', 'Liking things seen more often', 'Radiation effect', 'Photography term'),
('psych_182', 'en', 'Who developed rational emotive therapy?', 'Albert Ellis', 'Aaron Beck', 'Carl Rogers'),
('psych_183', 'en', 'What is projection in psychology?', 'Attributing own feelings to others', 'Movie projection', 'Future planning'),
('psych_184', 'en', 'What is the collective unconscious?', 'Jungs shared ancestral memories', 'Group therapy', 'Mass amnesia'),
('psych_185', 'en', 'Who studied attachment in infants?', 'John Bowlby', 'Harry Harlow', 'Mary Ainsworth'),
('psych_186', 'en', 'What is extinction in conditioning?', 'Response fades without reinforcement', 'Animal death', 'Memory loss'),
('psych_187', 'en', 'What is the Dunning-Kruger effect?', 'Unskilled overestimate ability', 'Learning curve', 'Memory trick'),
('psych_188', 'en', 'Who developed the theory of multiple intelligences?', 'Howard Gardner', 'Robert Sternberg', 'Alfred Binet'),
('psych_189', 'en', 'What is cognitive load?', 'Mental effort required for task', 'Brain weight', 'Thinking speed'),
('psych_190', 'en', 'What is self-actualization?', 'Reaching full potential', 'Selfishness', 'Self-awareness'),
('psych_191', 'en', 'Who studied conformity with line experiments?', 'Solomon Asch', 'Stanley Milgram', 'Philip Zimbardo'),
('psych_192', 'en', 'What is the superego?', 'Moral conscience', 'Primitive desires', 'Rational self'),
('psych_193', 'en', 'What is anchoring bias?', 'Relying too much on first info', 'Ship navigation', 'News reporting'),
('psych_194', 'en', 'Who developed positive psychology?', 'Martin Seligman', 'Mihaly Csikszentmihalyi', 'Carol Dweck'),
('psych_195', 'en', 'What is working memory?', 'Active processing of information', 'Job experience', 'Long-term storage'),
('psych_196', 'en', 'What is the spotlight effect?', 'Overestimating how much others notice us', 'Stage lighting', 'Attention focus'),
('psych_197', 'en', 'Who discovered the speech production area?', 'Paul Broca', 'Carl Wernicke', 'Roger Sperry'),
('psych_198', 'en', 'What is groupthink?', 'Conformity overrides critical thinking', 'Team building', 'Meditation technique'),
('psych_199', 'en', 'What is the availability heuristic?', 'Judging by easily recalled examples', 'Resource management', 'Computer algorithm'),
('psych_200', 'en', 'Who studied obedience and authority?', 'Stanley Milgram', 'Solomon Asch', 'Philip Zimbardo')
ON CONFLICT (question_id, lang) DO NOTHING;
