
-- Topic 7: Világtörténelem (World History) - 50 new questions
INSERT INTO public.questions (id, question, answers, audience, third, topic_id, source_category) VALUES
('q_wh_new_001', 'Ki volt a Római Birodalom első császára?', '[{"key":"A","text":"Augustus","correct":true},{"key":"B","text":"Julius Caesar","correct":false},{"key":"C","text":"Nero","correct":false}]', '{"A":65,"B":25,"C":10}', 'A', 7, 'history'),
('q_wh_new_002', 'Melyik évben kezdődött az Első Világháború?', '[{"key":"A","text":"1914","correct":true},{"key":"B","text":"1918","correct":false},{"key":"C","text":"1939","correct":false}]', '{"A":70,"B":20,"C":10}', 'A', 7, 'history'),
('q_wh_new_003', 'Ki volt Franciaország királya a francia forradalom idején?', '[{"key":"A","text":"XVI. Lajos","correct":true},{"key":"B","text":"XIV. Lajos","correct":false},{"key":"C","text":"XV. Lajos","correct":false}]', '{"A":55,"B":30,"C":15}', 'A', 7, 'history'),
('q_wh_new_004', 'Melyik birodalom fővárosát hívták Konstantinápolynak?', '[{"key":"A","text":"Bizánci Birodalom","correct":true},{"key":"B","text":"Római Birodalom","correct":false},{"key":"C","text":"Perzsa Birodalom","correct":false}]', '{"A":60,"B":25,"C":15}', 'A', 7, 'history'),
('q_wh_new_005', 'Ki volt az első ember a Holdon?', '[{"key":"A","text":"Neil Armstrong","correct":true},{"key":"B","text":"Buzz Aldrin","correct":false},{"key":"C","text":"Jurij Gagarin","correct":false}]', '{"A":75,"B":15,"C":10}', 'A', 7, 'history'),
('q_wh_new_006', 'Melyik évben esett el a Berlini Fal?', '[{"key":"A","text":"1989","correct":true},{"key":"B","text":"1991","correct":false},{"key":"C","text":"1985","correct":false}]', '{"A":65,"B":25,"C":10}', 'A', 7, 'history'),
('q_wh_new_007', 'Ki vezette a brit erőket Waterloo-nál?', '[{"key":"A","text":"Wellington herceg","correct":true},{"key":"B","text":"Horatio Nelson","correct":false},{"key":"C","text":"III. György","correct":false}]', '{"A":50,"B":35,"C":15}', 'A', 7, 'history'),
('q_wh_new_008', 'Melyik civilizáció építette Machu Picchut?', '[{"key":"A","text":"Inka","correct":true},{"key":"B","text":"Maja","correct":false},{"key":"C","text":"Azték","correct":false}]', '{"A":60,"B":25,"C":15}', 'A', 7, 'history'),
('q_wh_new_009', 'Ki volt a Szovjetunió első vezetője?', '[{"key":"A","text":"Lenin","correct":true},{"key":"B","text":"Sztálin","correct":false},{"key":"C","text":"Trockij","correct":false}]', '{"A":70,"B":20,"C":10}', 'A', 7, 'history'),
('q_wh_new_010', 'Melyik háború során használtak először tankokat?', '[{"key":"A","text":"Első Világháború","correct":true},{"key":"B","text":"Második Világháború","correct":false},{"key":"C","text":"Polgárháború","correct":false}]', '{"A":55,"B":35,"C":10}', 'A', 7, 'history'),
('q_wh_new_011', 'Ki volt Egyiptom utolsó fáraója?', '[{"key":"A","text":"Kleopátra","correct":true},{"key":"B","text":"Nefertiti","correct":false},{"key":"C","text":"Tutanhamon","correct":false}]', '{"A":65,"B":20,"C":15}', 'A', 7, 'history'),
('q_wh_new_012', 'Melyik évben fedezte fel Kolumbusz Amerikát?', '[{"key":"A","text":"1492","correct":true},{"key":"B","text":"1500","correct":false},{"key":"C","text":"1488","correct":false}]', '{"A":75,"B":15,"C":10}', 'A', 7, 'history'),
('q_wh_new_013', 'Ki írta a Kommunista Kiáltványt?', '[{"key":"A","text":"Karl Marx","correct":true},{"key":"B","text":"Friedrich Engels egyedül","correct":false},{"key":"C","text":"Lenin","correct":false}]', '{"A":70,"B":20,"C":10}', 'A', 7, 'history'),
('q_wh_new_014', 'Melyik ország volt a leghosszabb gyarmatbirodalom?', '[{"key":"A","text":"Brit Birodalom","correct":true},{"key":"B","text":"Francia Birodalom","correct":false},{"key":"C","text":"Spanyol Birodalom","correct":false}]', '{"A":65,"B":20,"C":15}', 'A', 7, 'history'),
('q_wh_new_015', 'Ki volt a mongolok legnagyobb hódítója?', '[{"key":"A","text":"Dzsingisz kán","correct":true},{"key":"B","text":"Kubiláj kán","correct":false},{"key":"C","text":"Timur Lenk","correct":false}]', '{"A":75,"B":15,"C":10}', 'A', 7, 'history'),
('q_wh_new_016', 'Melyik csata volt a napóleoni háborúk utolsó nagy ütközete?', '[{"key":"A","text":"Waterloo","correct":true},{"key":"B","text":"Austerlitz","correct":false},{"key":"C","text":"Borogyinó","correct":false}]', '{"A":70,"B":20,"C":10}', 'A', 7, 'history'),
('q_wh_new_017', 'Melyik évben végződött a Második Világháború Európában?', '[{"key":"A","text":"1945","correct":true},{"key":"B","text":"1944","correct":false},{"key":"C","text":"1946","correct":false}]', '{"A":80,"B":10,"C":10}', 'A', 7, 'history'),
('q_wh_new_018', 'Ki volt a Harmadik Birodalom vezetője?', '[{"key":"A","text":"Adolf Hitler","correct":true},{"key":"B","text":"Heinrich Himmler","correct":false},{"key":"C","text":"Hermann Göring","correct":false}]', '{"A":85,"B":10,"C":5}', 'A', 7, 'history'),
('q_wh_new_019', 'Melyik óceánt szelték át először európai hajósok?', '[{"key":"A","text":"Atlanti-óceán","correct":true},{"key":"B","text":"Csendes-óceán","correct":false},{"key":"C","text":"Indiai-óceán","correct":false}]', '{"A":60,"B":25,"C":15}', 'A', 7, 'history'),
('q_wh_new_020', 'Ki volt az első amerikai elnök?', '[{"key":"A","text":"George Washington","correct":true},{"key":"B","text":"Thomas Jefferson","correct":false},{"key":"C","text":"Benjamin Franklin","correct":false}]', '{"A":80,"B":10,"C":10}', 'A', 7, 'history'),
('q_wh_new_021', 'Melyik évben zajlott le a Bastille ostroma?', '[{"key":"A","text":"1789","correct":true},{"key":"B","text":"1799","correct":false},{"key":"C","text":"1776","correct":false}]', '{"A":60,"B":25,"C":15}', 'A', 7, 'history'),
('q_wh_new_022', 'Ki volt a híres karthágói hadvezér, aki átszelte az Alpokat?', '[{"key":"A","text":"Hannibál","correct":true},{"key":"B","text":"Scipio","correct":false},{"key":"C","text":"Hamilcar","correct":false}]', '{"A":70,"B":20,"C":10}', 'A', 7, 'history'),
('q_wh_new_023', 'Melyik birodalom hódította meg Görögországot Kr.e. 146-ban?', '[{"key":"A","text":"Római Birodalom","correct":true},{"key":"B","text":"Perzsa Birodalom","correct":false},{"key":"C","text":"Makedón Birodalom","correct":false}]', '{"A":55,"B":25,"C":20}', 'A', 7, 'history'),
('q_wh_new_024', 'Ki volt a Reformáció elindítója?', '[{"key":"A","text":"Luther Márton","correct":true},{"key":"B","text":"Kálvin János","correct":false},{"key":"C","text":"VIII. Henrik","correct":false}]', '{"A":70,"B":20,"C":10}', 'A', 7, 'history'),
('q_wh_new_025', 'Melyik évben történt a Pearl Harbor elleni támadás?', '[{"key":"A","text":"1941","correct":true},{"key":"B","text":"1942","correct":false},{"key":"C","text":"1940","correct":false}]', '{"A":65,"B":25,"C":10}', 'A', 7, 'history'),
('q_wh_new_026', 'Ki volt a reneszánsz kor híres festője, aki a Mona Lisát festette?', '[{"key":"A","text":"Leonardo da Vinci","correct":true},{"key":"B","text":"Michelangelo","correct":false},{"key":"C","text":"Raffaello","correct":false}]', '{"A":80,"B":15,"C":5}', 'A', 7, 'history'),
('q_wh_new_027', 'Melyik birodalom székhelye volt Persepolis?', '[{"key":"A","text":"Óperzsa Birodalom","correct":true},{"key":"B","text":"Asszír Birodalom","correct":false},{"key":"C","text":"Babiloni Birodalom","correct":false}]', '{"A":50,"B":30,"C":20}', 'A', 7, 'history'),
('q_wh_new_028', 'Ki volt az orosz cár, akit az 1917-es forradalomban megdöntöttek?', '[{"key":"A","text":"II. Miklós","correct":true},{"key":"B","text":"II. Sándor","correct":false},{"key":"C","text":"III. Sándor","correct":false}]', '{"A":60,"B":25,"C":15}', 'A', 7, 'history'),
('q_wh_new_029', 'Melyik évben írták alá a Versailles-i békeszerződést?', '[{"key":"A","text":"1919","correct":true},{"key":"B","text":"1918","correct":false},{"key":"C","text":"1920","correct":false}]', '{"A":55,"B":30,"C":15}', 'A', 7, 'history'),
('q_wh_new_030', 'Ki alapította az Oszmán Birodalmat?', '[{"key":"A","text":"I. Oszmán","correct":true},{"key":"B","text":"I. Szulejmán","correct":false},{"key":"C","text":"II. Mehmed","correct":false}]', '{"A":50,"B":35,"C":15}', 'A', 7, 'history'),
('q_wh_new_031', 'Melyik országban kezdődött az ipari forradalom?', '[{"key":"A","text":"Anglia","correct":true},{"key":"B","text":"Franciaország","correct":false},{"key":"C","text":"Németország","correct":false}]', '{"A":75,"B":15,"C":10}', 'A', 7, 'history'),
('q_wh_new_032', 'Ki volt a görög mitológia főistene?', '[{"key":"A","text":"Zeusz","correct":true},{"key":"B","text":"Poszeidón","correct":false},{"key":"C","text":"Hádész","correct":false}]', '{"A":80,"B":15,"C":5}', 'A', 7, 'history'),
('q_wh_new_033', 'Melyik évben végződött a hidegháború?', '[{"key":"A","text":"1991","correct":true},{"key":"B","text":"1989","correct":false},{"key":"C","text":"1995","correct":false}]', '{"A":55,"B":35,"C":10}', 'A', 7, 'history'),
('q_wh_new_034', 'Ki volt a Magna Carta aláírója?', '[{"key":"A","text":"Földnélküli János","correct":true},{"key":"B","text":"I. Richard","correct":false},{"key":"C","text":"I. Henrik","correct":false}]', '{"A":50,"B":30,"C":20}', 'A', 7, 'history'),
('q_wh_new_035', 'Melyik ókori csodát építették Babilonban?', '[{"key":"A","text":"Függőkertek","correct":true},{"key":"B","text":"Kolosszus","correct":false},{"key":"C","text":"Mauzóleum","correct":false}]', '{"A":65,"B":20,"C":15}', 'A', 7, 'history'),
('q_wh_new_036', 'Ki volt a spanyol konkvisztádor, aki legyőzte az aztékokat?', '[{"key":"A","text":"Hernán Cortés","correct":true},{"key":"B","text":"Francisco Pizarro","correct":false},{"key":"C","text":"Vasco da Gama","correct":false}]', '{"A":55,"B":30,"C":15}', 'A', 7, 'history'),
('q_wh_new_037', 'Melyik évben alapították Rómát a legenda szerint?', '[{"key":"A","text":"Kr.e. 753","correct":true},{"key":"B","text":"Kr.e. 500","correct":false},{"key":"C","text":"Kr.e. 1000","correct":false}]', '{"A":50,"B":30,"C":20}', 'A', 7, 'history'),
('q_wh_new_038', 'Ki volt a híres francia hadvezér, aki császárrá koronázta magát?', '[{"key":"A","text":"Napóleon Bonaparte","correct":true},{"key":"B","text":"XIV. Lajos","correct":false},{"key":"C","text":"Richelieu bíboros","correct":false}]', '{"A":80,"B":15,"C":5}', 'A', 7, 'history'),
('q_wh_new_039', 'Melyik vallást alapította Mohamed próféta?', '[{"key":"A","text":"Iszlám","correct":true},{"key":"B","text":"Buddhizmus","correct":false},{"key":"C","text":"Hinduizmus","correct":false}]', '{"A":85,"B":10,"C":5}', 'A', 7, 'history'),
('q_wh_new_040', 'Ki volt a kínai nagy fal építésének elindítója?', '[{"key":"A","text":"Csin Si Huang-ti","correct":true},{"key":"B","text":"Konfuciusz","correct":false},{"key":"C","text":"Lao-ce","correct":false}]', '{"A":55,"B":30,"C":15}', 'A', 7, 'history'),
('q_wh_new_041', 'Melyik évben robbantották le az első atombombát?', '[{"key":"A","text":"1945","correct":true},{"key":"B","text":"1944","correct":false},{"key":"C","text":"1946","correct":false}]', '{"A":75,"B":15,"C":10}', 'A', 7, 'history'),
('q_wh_new_042', 'Ki volt a vikingek híres felfedezője, aki elérte Amerikát?', '[{"key":"A","text":"Leif Eriksson","correct":true},{"key":"B","text":"Erik Vörös","correct":false},{"key":"C","text":"Ragnar Lothbrok","correct":false}]', '{"A":50,"B":30,"C":20}', 'A', 7, 'history'),
('q_wh_new_043', 'Melyik ország ellen vívták a trójai háborút?', '[{"key":"A","text":"Trója","correct":true},{"key":"B","text":"Spárta","correct":false},{"key":"C","text":"Athén","correct":false}]', '{"A":70,"B":20,"C":10}', 'A', 7, 'history'),
('q_wh_new_044', 'Ki volt a híres makedón hódító, aki elfoglalta Perzsiát?', '[{"key":"A","text":"Nagy Sándor","correct":true},{"key":"B","text":"II. Fülöp","correct":false},{"key":"C","text":"Ptolemaiosz","correct":false}]', '{"A":80,"B":15,"C":5}', 'A', 7, 'history'),
('q_wh_new_045', 'Melyik évben zajlott le a mohácsi csata?', '[{"key":"A","text":"1526","correct":true},{"key":"B","text":"1456","correct":false},{"key":"C","text":"1541","correct":false}]', '{"A":60,"B":25,"C":15}', 'A', 7, 'history'),
('q_wh_new_046', 'Ki volt az első női miniszterelnök Angliában?', '[{"key":"A","text":"Margaret Thatcher","correct":true},{"key":"B","text":"Theresa May","correct":false},{"key":"C","text":"II. Erzsébet","correct":false}]', '{"A":75,"B":15,"C":10}', 'A', 7, 'history'),
('q_wh_new_047', 'Melyik birodalom uralkodója volt I. Péter?', '[{"key":"A","text":"Orosz Birodalom","correct":true},{"key":"B","text":"Oszmán Birodalom","correct":false},{"key":"C","text":"Svéd Birodalom","correct":false}]', '{"A":65,"B":20,"C":15}', 'A', 7, 'history'),
('q_wh_new_048', 'Ki volt a híres olasz navigátor, aki Brazíliát felfedezte?', '[{"key":"A","text":"Pedro Álvares Cabral","correct":true},{"key":"B","text":"Vasco da Gama","correct":false},{"key":"C","text":"Amerigo Vespucci","correct":false}]', '{"A":45,"B":35,"C":20}', 'A', 7, 'history'),
('q_wh_new_049', 'Melyik évben alakult meg az ENSZ?', '[{"key":"A","text":"1945","correct":true},{"key":"B","text":"1946","correct":false},{"key":"C","text":"1950","correct":false}]', '{"A":60,"B":25,"C":15}', 'A', 7, 'history'),
('q_wh_new_050', 'Ki volt a japán hadsereg parancsnoka Pearl Harbornál?', '[{"key":"A","text":"Jamamoto Iszoroku","correct":true},{"key":"B","text":"Tojo Hideki","correct":false},{"key":"C","text":"Hirohito császár","correct":false}]', '{"A":45,"B":35,"C":20}', 'A', 7, 'history');

-- English translations for Topic 7
INSERT INTO public.question_translations (question_id, lang, question_text, answer_a, answer_b, answer_c) VALUES
('q_wh_new_001', 'en', 'Who was the first emperor of the Roman Empire?', 'Augustus', 'Julius Caesar', 'Nero'),
('q_wh_new_002', 'en', 'In which year did World War I begin?', '1914', '1918', '1939'),
('q_wh_new_003', 'en', 'Who was the King of France during the French Revolution?', 'Louis XVI', 'Louis XIV', 'Louis XV'),
('q_wh_new_004', 'en', 'Which empire had Constantinople as its capital?', 'Byzantine Empire', 'Roman Empire', 'Persian Empire'),
('q_wh_new_005', 'en', 'Who was the first person on the Moon?', 'Neil Armstrong', 'Buzz Aldrin', 'Yuri Gagarin'),
('q_wh_new_006', 'en', 'In which year did the Berlin Wall fall?', '1989', '1991', '1985'),
('q_wh_new_007', 'en', 'Who led the British forces at Waterloo?', 'Duke of Wellington', 'Horatio Nelson', 'George III'),
('q_wh_new_008', 'en', 'Which civilization built Machu Picchu?', 'Inca', 'Maya', 'Aztec'),
('q_wh_new_009', 'en', 'Who was the first leader of the Soviet Union?', 'Lenin', 'Stalin', 'Trotsky'),
('q_wh_new_010', 'en', 'During which war were tanks first used?', 'World War I', 'World War II', 'Civil War'),
('q_wh_new_011', 'en', 'Who was the last pharaoh of Egypt?', 'Cleopatra', 'Nefertiti', 'Tutankhamun'),
('q_wh_new_012', 'en', 'In which year did Columbus discover America?', '1492', '1500', '1488'),
('q_wh_new_013', 'en', 'Who wrote the Communist Manifesto?', 'Karl Marx', 'Friedrich Engels alone', 'Lenin'),
('q_wh_new_014', 'en', 'Which country had the largest colonial empire?', 'British Empire', 'French Empire', 'Spanish Empire'),
('q_wh_new_015', 'en', 'Who was the greatest Mongol conqueror?', 'Genghis Khan', 'Kublai Khan', 'Tamerlane'),
('q_wh_new_016', 'en', 'Which battle was the last major battle of the Napoleonic Wars?', 'Waterloo', 'Austerlitz', 'Borodino'),
('q_wh_new_017', 'en', 'In which year did World War II end in Europe?', '1945', '1944', '1946'),
('q_wh_new_018', 'en', 'Who was the leader of the Third Reich?', 'Adolf Hitler', 'Heinrich Himmler', 'Hermann Göring'),
('q_wh_new_019', 'en', 'Which ocean did European sailors cross first?', 'Atlantic Ocean', 'Pacific Ocean', 'Indian Ocean'),
('q_wh_new_020', 'en', 'Who was the first American president?', 'George Washington', 'Thomas Jefferson', 'Benjamin Franklin'),
('q_wh_new_021', 'en', 'In which year did the storming of the Bastille occur?', '1789', '1799', '1776'),
('q_wh_new_022', 'en', 'Who was the famous Carthaginian general who crossed the Alps?', 'Hannibal', 'Scipio', 'Hamilcar'),
('q_wh_new_023', 'en', 'Which empire conquered Greece in 146 BC?', 'Roman Empire', 'Persian Empire', 'Macedonian Empire'),
('q_wh_new_024', 'en', 'Who started the Reformation?', 'Martin Luther', 'John Calvin', 'Henry VIII'),
('q_wh_new_025', 'en', 'In which year did the attack on Pearl Harbor occur?', '1941', '1942', '1940'),
('q_wh_new_026', 'en', 'Who was the Renaissance painter who painted the Mona Lisa?', 'Leonardo da Vinci', 'Michelangelo', 'Raphael'),
('q_wh_new_027', 'en', 'Which empire had Persepolis as its capital?', 'Persian Empire', 'Assyrian Empire', 'Babylonian Empire'),
('q_wh_new_028', 'en', 'Who was the Russian Tsar overthrown in the 1917 revolution?', 'Nicholas II', 'Alexander II', 'Alexander III'),
('q_wh_new_029', 'en', 'In which year was the Treaty of Versailles signed?', '1919', '1918', '1920'),
('q_wh_new_030', 'en', 'Who founded the Ottoman Empire?', 'Osman I', 'Suleiman I', 'Mehmed II'),
('q_wh_new_031', 'en', 'In which country did the Industrial Revolution begin?', 'England', 'France', 'Germany'),
('q_wh_new_032', 'en', 'Who was the chief god in Greek mythology?', 'Zeus', 'Poseidon', 'Hades'),
('q_wh_new_033', 'en', 'In which year did the Cold War end?', '1991', '1989', '1995'),
('q_wh_new_034', 'en', 'Who signed the Magna Carta?', 'King John', 'Richard I', 'Henry I'),
('q_wh_new_035', 'en', 'Which ancient wonder was built in Babylon?', 'Hanging Gardens', 'Colossus', 'Mausoleum'),
('q_wh_new_036', 'en', 'Who was the Spanish conquistador who defeated the Aztecs?', 'Hernán Cortés', 'Francisco Pizarro', 'Vasco da Gama'),
('q_wh_new_037', 'en', 'In which year was Rome founded according to legend?', '753 BC', '500 BC', '1000 BC'),
('q_wh_new_038', 'en', 'Who was the famous French military leader who crowned himself emperor?', 'Napoleon Bonaparte', 'Louis XIV', 'Cardinal Richelieu'),
('q_wh_new_039', 'en', 'Which religion was founded by Prophet Muhammad?', 'Islam', 'Buddhism', 'Hinduism'),
('q_wh_new_040', 'en', 'Who initiated the construction of the Great Wall of China?', 'Qin Shi Huang', 'Confucius', 'Lao Tzu'),
('q_wh_new_041', 'en', 'In which year was the first atomic bomb detonated?', '1945', '1944', '1946'),
('q_wh_new_042', 'en', 'Who was the famous Viking explorer who reached America?', 'Leif Eriksson', 'Erik the Red', 'Ragnar Lothbrok'),
('q_wh_new_043', 'en', 'Which city was the Trojan War fought against?', 'Troy', 'Sparta', 'Athens'),
('q_wh_new_044', 'en', 'Who was the famous Macedonian conqueror who conquered Persia?', 'Alexander the Great', 'Philip II', 'Ptolemy'),
('q_wh_new_045', 'en', 'In which year did the Battle of Mohács take place?', '1526', '1456', '1541'),
('q_wh_new_046', 'en', 'Who was the first female Prime Minister of England?', 'Margaret Thatcher', 'Theresa May', 'Elizabeth II'),
('q_wh_new_047', 'en', 'Which empire was Peter I the ruler of?', 'Russian Empire', 'Ottoman Empire', 'Swedish Empire'),
('q_wh_new_048', 'en', 'Who was the famous navigator who discovered Brazil?', 'Pedro Álvares Cabral', 'Vasco da Gama', 'Amerigo Vespucci'),
('q_wh_new_049', 'en', 'In which year was the UN founded?', '1945', '1946', '1950'),
('q_wh_new_050', 'en', 'Who was the Japanese naval commander at Pearl Harbor?', 'Isoroku Yamamoto', 'Hideki Tojo', 'Emperor Hirohito');
