-- Topic 13: Film & TV - Add 50 questions (film_151 to film_200)
INSERT INTO questions (id, question, answers, audience, third, source_category, topic_id) VALUES
('film_151', 'Ki rendezte a "Titanic" című filmet?', '[{"key":"A","text":"Steven Spielberg","correct":false},{"key":"B","text":"James Cameron","correct":true},{"key":"C","text":"Martin Scorsese","correct":false}]', '[20,60,20]', 'B', 'mixed', 13),
('film_152', 'Melyik színész játszotta Jack Sparrow kapitányt?', '[{"key":"A","text":"Orlando Bloom","correct":false},{"key":"B","text":"Johnny Depp","correct":true},{"key":"C","text":"Brad Pitt","correct":false}]', '[15,70,15]', 'B', 'mixed', 13),
('film_153', 'Hány Oscar-díjat nyert a "Gyűrűk Ura: A király visszatér"?', '[{"key":"A","text":"9","correct":false},{"key":"B","text":"11","correct":true},{"key":"C","text":"13","correct":false}]', '[25,55,20]', 'B', 'mixed', 13),
('film_154', 'Ki rendezte a "Ponyvaregény" című filmet?', '[{"key":"A","text":"Quentin Tarantino","correct":true},{"key":"B","text":"David Fincher","correct":false},{"key":"C","text":"Christopher Nolan","correct":false}]', '[60,20,20]', 'A', 'mixed', 13),
('film_155', 'Melyik színésznő játszotta Hermione Grangert?', '[{"key":"A","text":"Emma Stone","correct":false},{"key":"B","text":"Emma Watson","correct":true},{"key":"C","text":"Emily Blunt","correct":false}]', '[20,65,15]', 'B', 'mixed', 13),
('film_156', 'Mi volt az első teljesen számítógépes animációs film?', '[{"key":"A","text":"Toy Story","correct":true},{"key":"B","text":"Shrek","correct":false},{"key":"C","text":"Jégkorszak","correct":false}]', '[60,20,20]', 'A', 'mixed', 13),
('film_157', 'Ki játszotta James Bondot a Casino Royale-ban?', '[{"key":"A","text":"Pierce Brosnan","correct":false},{"key":"B","text":"Daniel Craig","correct":true},{"key":"C","text":"Sean Connery","correct":false}]', '[20,60,20]', 'B', 'mixed', 13),
('film_158', 'Melyik filmben hangzik el: "Én vagyok az apád"?', '[{"key":"A","text":"Star Trek","correct":false},{"key":"B","text":"Csillagok háborúja","correct":true},{"key":"C","text":"Galaktika útikalauz","correct":false}]', '[15,70,15]', 'B', 'mixed', 13),
('film_159', 'Ki rendezte az "Eredet" (Inception) című filmet?', '[{"key":"A","text":"Denis Villeneuve","correct":false},{"key":"B","text":"Christopher Nolan","correct":true},{"key":"C","text":"Ridley Scott","correct":false}]', '[20,60,20]', 'B', 'mixed', 13),
('film_160', 'Melyik színész játszotta az első Vasembert?', '[{"key":"A","text":"Chris Evans","correct":false},{"key":"B","text":"Robert Downey Jr.","correct":true},{"key":"C","text":"Chris Hemsworth","correct":false}]', '[15,70,15]', 'B', 'mixed', 13),
('film_161', 'Hány film készült a Harry Potter sorozatból?', '[{"key":"A","text":"6","correct":false},{"key":"B","text":"8","correct":true},{"key":"C","text":"10","correct":false}]', '[20,60,20]', 'B', 'mixed', 13),
('film_162', 'Ki rendezte a "Schindler listája" című filmet?', '[{"key":"A","text":"Steven Spielberg","correct":true},{"key":"B","text":"Francis Ford Coppola","correct":false},{"key":"C","text":"Stanley Kubrick","correct":false}]', '[60,20,20]', 'A', 'mixed', 13),
('film_163', 'Melyik színésznő ismert a "Jóbarátok" Rachel szerepéről?', '[{"key":"A","text":"Courteney Cox","correct":false},{"key":"B","text":"Jennifer Aniston","correct":true},{"key":"C","text":"Lisa Kudrow","correct":false}]', '[20,65,15]', 'B', 'mixed', 13),
('film_164', 'Mi a "Trónok harca" eredeti nyelve?', '[{"key":"A","text":"Angol","correct":true},{"key":"B","text":"Kínai","correct":false},{"key":"C","text":"Spanyol","correct":false}]', '[60,20,20]', 'A', 'mixed', 13),
('film_165', 'Ki játszotta Neo-t a Mátrix filmekben?', '[{"key":"A","text":"Keanu Reeves","correct":true},{"key":"B","text":"Nicolas Cage","correct":false},{"key":"C","text":"Tom Cruise","correct":false}]', '[65,20,15]', 'A', 'mixed', 13),
('film_166', 'Melyik évben jelent meg az első Csillagok háborúja film?', '[{"key":"A","text":"1975","correct":false},{"key":"B","text":"1977","correct":true},{"key":"C","text":"1980","correct":false}]', '[20,60,20]', 'B', 'mixed', 13),
('film_167', 'Ki rendezte az "E.T. - A földönkívüli" című filmet?', '[{"key":"A","text":"Steven Spielberg","correct":true},{"key":"B","text":"George Lucas","correct":false},{"key":"C","text":"Robert Zemeckis","correct":false}]', '[60,20,20]', 'A', 'mixed', 13),
('film_168', 'Melyik színész játszotta Wolverine-t?', '[{"key":"A","text":"Hugh Jackman","correct":true},{"key":"B","text":"Chris Pratt","correct":false},{"key":"C","text":"Ryan Reynolds","correct":false}]', '[65,20,15]', 'A', 'mixed', 13),
('film_169', 'Hány évadja van az "Agymenők" sorozatnak?', '[{"key":"A","text":"10","correct":false},{"key":"B","text":"12","correct":true},{"key":"C","text":"14","correct":false}]', '[25,55,20]', 'B', 'mixed', 13),
('film_170', 'Ki rendezte a "Joker" (2019) című filmet?', '[{"key":"A","text":"Todd Phillips","correct":true},{"key":"B","text":"Matt Reeves","correct":false},{"key":"C","text":"Zack Snyder","correct":false}]', '[55,25,20]', 'A', 'mixed', 13),
('film_171', 'Melyik színésznő játszotta Katniss Everdeent?', '[{"key":"A","text":"Jennifer Lawrence","correct":true},{"key":"B","text":"Emma Stone","correct":false},{"key":"C","text":"Scarlett Johansson","correct":false}]', '[60,20,20]', 'A', 'mixed', 13),
('film_172', 'Mi volt a Pixar első rövidfilmje?', '[{"key":"A","text":"Luxo Jr.","correct":true},{"key":"B","text":"Tin Toy","correct":false},{"key":"C","text":"Geri játéka","correct":false}]', '[55,25,20]', 'A', 'mixed', 13),
('film_173', 'Ki játszotta Hannibál Lektert "A bárányok hallgatnak" filmben?', '[{"key":"A","text":"Anthony Hopkins","correct":true},{"key":"B","text":"Kevin Spacey","correct":false},{"key":"C","text":"Gary Oldman","correct":false}]', '[65,20,15]', 'A', 'mixed', 13),
('film_174', 'Melyik városban játszódik a "Vérző acél" (Breaking Bad)?', '[{"key":"A","text":"Los Angeles","correct":false},{"key":"B","text":"Albuquerque","correct":true},{"key":"C","text":"Denver","correct":false}]', '[25,55,20]', 'B', 'mixed', 13),
('film_175', 'Ki rendezte a "Keresztapa" trilógiát?', '[{"key":"A","text":"Francis Ford Coppola","correct":true},{"key":"B","text":"Martin Scorsese","correct":false},{"key":"C","text":"Brian De Palma","correct":false}]', '[60,25,15]', 'A', 'mixed', 13),
('film_176', 'Melyik filmben játszott először együtt DiCaprio és Kate Winslet?', '[{"key":"A","text":"Forradalmárok útja","correct":false},{"key":"B","text":"Titanic","correct":true},{"key":"C","text":"Életrevalók","correct":false}]', '[20,65,15]', 'B', 'mixed', 13),
('film_177', 'Hány kötetből áll a "Gyűrűk Ura" könyvsorozat?', '[{"key":"A","text":"Kettő","correct":false},{"key":"B","text":"Három","correct":true},{"key":"C","text":"Négy","correct":false}]', '[20,60,20]', 'B', 'mixed', 13),
('film_178', 'Ki rendezte az "Avatar" (2009) filmet?', '[{"key":"A","text":"Steven Spielberg","correct":false},{"key":"B","text":"James Cameron","correct":true},{"key":"C","text":"Peter Jackson","correct":false}]', '[20,60,20]', 'B', 'mixed', 13),
('film_179', 'Melyik színész játszotta Sherlock Holmes-t a BBC sorozatban?', '[{"key":"A","text":"Benedict Cumberbatch","correct":true},{"key":"B","text":"Robert Downey Jr.","correct":false},{"key":"C","text":"Martin Freeman","correct":false}]', '[60,25,15]', 'A', 'mixed', 13),
('film_180', 'Mi a neve Chandler Bing feleségének a Jóbarátokban?', '[{"key":"A","text":"Phoebe","correct":false},{"key":"B","text":"Monica","correct":true},{"key":"C","text":"Rachel","correct":false}]', '[20,60,20]', 'B', 'mixed', 13),
('film_181', 'Ki rendezte a "2001: Űrodüsszeia" című filmet?', '[{"key":"A","text":"Stanley Kubrick","correct":true},{"key":"B","text":"Ridley Scott","correct":false},{"key":"C","text":"George Lucas","correct":false}]', '[60,25,15]', 'A', 'mixed', 13),
('film_182', 'Melyik színész játszotta Thor-t a Marvel filmekben?', '[{"key":"A","text":"Chris Evans","correct":false},{"key":"B","text":"Chris Hemsworth","correct":true},{"key":"C","text":"Chris Pratt","correct":false}]', '[20,60,20]', 'B', 'mixed', 13),
('film_183', 'Mi a "The Office" amerikai változatának főszereplőjének neve?', '[{"key":"A","text":"Steve Carell","correct":true},{"key":"B","text":"Rainn Wilson","correct":false},{"key":"C","text":"John Krasinski","correct":false}]', '[55,25,20]', 'A', 'mixed', 13),
('film_184', 'Hány Rocky film készült?', '[{"key":"A","text":"5","correct":false},{"key":"B","text":"6","correct":true},{"key":"C","text":"7","correct":false}]', '[25,55,20]', 'B', 'mixed', 13),
('film_185', 'Ki rendezte a "Ragyogás" című filmet?', '[{"key":"A","text":"Stanley Kubrick","correct":true},{"key":"B","text":"Roman Polanski","correct":false},{"key":"C","text":"Alfred Hitchcock","correct":false}]', '[55,25,20]', 'A', 'mixed', 13),
('film_186', 'Melyik színésznő játszotta Wonder Woman-t?', '[{"key":"A","text":"Gal Gadot","correct":true},{"key":"B","text":"Scarlett Johansson","correct":false},{"key":"C","text":"Brie Larson","correct":false}]', '[65,20,15]', 'A', 'mixed', 13),
('film_187', 'Mi a "Stranger Things" eredeti nyelve?', '[{"key":"A","text":"Angol","correct":true},{"key":"B","text":"Spanyol","correct":false},{"key":"C","text":"Koreai","correct":false}]', '[60,20,20]', 'A', 'mixed', 13),
('film_188', 'Ki rendezte az "Alkonyat" filmsorozatot?', '[{"key":"A","text":"Catherine Hardwicke","correct":true},{"key":"B","text":"Sofia Coppola","correct":false},{"key":"C","text":"Kathryn Bigelow","correct":false}]', '[50,25,25]', 'A', 'mixed', 13),
('film_189', 'Melyik színész játszotta Dél-Koreában a "Parasite" apját?', '[{"key":"A","text":"Song Kang-ho","correct":true},{"key":"B","text":"Lee Byung-hun","correct":false},{"key":"C","text":"Choi Min-sik","correct":false}]', '[50,25,25]', 'A', 'mixed', 13),
('film_190', 'Hány évadja van a "Breaking Bad" sorozatnak?', '[{"key":"A","text":"4","correct":false},{"key":"B","text":"5","correct":true},{"key":"C","text":"6","correct":false}]', '[20,60,20]', 'B', 'mixed', 13),
('film_191', 'Ki rendezte a "Száll a kakukk fészkére" filmet?', '[{"key":"A","text":"Milos Forman","correct":true},{"key":"B","text":"Sidney Lumet","correct":false},{"key":"C","text":"William Friedkin","correct":false}]', '[55,25,20]', 'A', 'mixed', 13),
('film_192', 'Melyik színész ismert az "Ocean" filmekről?', '[{"key":"A","text":"George Clooney","correct":true},{"key":"B","text":"Tom Hanks","correct":false},{"key":"C","text":"Denzel Washington","correct":false}]', '[60,20,20]', 'A', 'mixed', 13),
('film_193', 'Mi volt a Netflix első saját gyártású sorozata?', '[{"key":"A","text":"Orange Is the New Black","correct":false},{"key":"B","text":"House of Cards","correct":true},{"key":"C","text":"Stranger Things","correct":false}]', '[25,55,20]', 'B', 'mixed', 13),
('film_194', 'Ki játszotta Forrest Gumpot?', '[{"key":"A","text":"Tom Hanks","correct":true},{"key":"B","text":"Robin Williams","correct":false},{"key":"C","text":"Kevin Costner","correct":false}]', '[70,15,15]', 'A', 'mixed', 13),
('film_195', 'Melyik színésznő játszotta Black Widow-t?', '[{"key":"A","text":"Scarlett Johansson","correct":true},{"key":"B","text":"Gal Gadot","correct":false},{"key":"C","text":"Brie Larson","correct":false}]', '[65,20,15]', 'A', 'mixed', 13),
('film_196', 'Ki rendezte a "Tökéletes trükk" című filmet?', '[{"key":"A","text":"David Fincher","correct":false},{"key":"B","text":"Christopher Nolan","correct":true},{"key":"C","text":"Denis Villeneuve","correct":false}]', '[25,55,20]', 'B', 'mixed', 13),
('film_197', 'Hány évad van a "Friends" (Jóbarátok) sorozatból?', '[{"key":"A","text":"8","correct":false},{"key":"B","text":"10","correct":true},{"key":"C","text":"12","correct":false}]', '[20,60,20]', 'B', 'mixed', 13),
('film_198', 'Ki rendezte "A Sötét Lovag" trilógiát?', '[{"key":"A","text":"Christopher Nolan","correct":true},{"key":"B","text":"Zack Snyder","correct":false},{"key":"C","text":"Tim Burton","correct":false}]', '[60,25,15]', 'A', 'mixed', 13),
('film_199', 'Melyik színész játszotta Tarzant a 2016-os filmben?', '[{"key":"A","text":"Alexander Skarsgård","correct":true},{"key":"B","text":"Kellan Lutz","correct":false},{"key":"C","text":"Dwayne Johnson","correct":false}]', '[50,25,25]', 'A', 'mixed', 13),
('film_200', 'Mi a "The Crown" című sorozat témája?', '[{"key":"A","text":"Brit királyi család","correct":true},{"key":"B","text":"Középkori uralkodók","correct":false},{"key":"C","text":"Amerikai elnökök","correct":false}]', '[60,20,20]', 'A', 'mixed', 13);

-- English translations for Topic 13
INSERT INTO question_translations (question_id, lang, question_text, answer_a, answer_b, answer_c) VALUES
('film_151', 'en', 'Who directed the movie "Titanic"?', 'Steven Spielberg', 'James Cameron', 'Martin Scorsese'),
('film_152', 'en', 'Which actor played Captain Jack Sparrow?', 'Orlando Bloom', 'Johnny Depp', 'Brad Pitt'),
('film_153', 'en', 'How many Oscars did "The Lord of the Rings: Return of the King" win?', '9', '11', '13'),
('film_154', 'en', 'Who directed "Pulp Fiction"?', 'Quentin Tarantino', 'David Fincher', 'Christopher Nolan'),
('film_155', 'en', 'Which actress played Hermione Granger?', 'Emma Stone', 'Emma Watson', 'Emily Blunt'),
('film_156', 'en', 'What was the first fully computer-animated feature film?', 'Toy Story', 'Shrek', 'Ice Age'),
('film_157', 'en', 'Who played James Bond in Casino Royale?', 'Pierce Brosnan', 'Daniel Craig', 'Sean Connery'),
('film_158', 'en', 'Which film features the line "I am your father"?', 'Star Trek', 'Star Wars', 'Hitchhiker''s Guide to the Galaxy'),
('film_159', 'en', 'Who directed "Inception"?', 'Denis Villeneuve', 'Christopher Nolan', 'Ridley Scott'),
('film_160', 'en', 'Which actor played the first Iron Man?', 'Chris Evans', 'Robert Downey Jr.', 'Chris Hemsworth'),
('film_161', 'en', 'How many films were made in the Harry Potter series?', '6', '8', '10'),
('film_162', 'en', 'Who directed "Schindler''s List"?', 'Steven Spielberg', 'Francis Ford Coppola', 'Stanley Kubrick'),
('film_163', 'en', 'Which actress is known for playing Rachel in "Friends"?', 'Courteney Cox', 'Jennifer Aniston', 'Lisa Kudrow'),
('film_164', 'en', 'What is the original language of "Game of Thrones"?', 'English', 'Chinese', 'Spanish'),
('film_165', 'en', 'Who played Neo in the Matrix films?', 'Keanu Reeves', 'Nicolas Cage', 'Tom Cruise'),
('film_166', 'en', 'In which year was the first Star Wars film released?', '1975', '1977', '1980'),
('film_167', 'en', 'Who directed "E.T. the Extra-Terrestrial"?', 'Steven Spielberg', 'George Lucas', 'Robert Zemeckis'),
('film_168', 'en', 'Which actor played Wolverine?', 'Hugh Jackman', 'Chris Pratt', 'Ryan Reynolds'),
('film_169', 'en', 'How many seasons does "The Big Bang Theory" have?', '10', '12', '14'),
('film_170', 'en', 'Who directed "Joker" (2019)?', 'Todd Phillips', 'Matt Reeves', 'Zack Snyder'),
('film_171', 'en', 'Which actress played Katniss Everdeen?', 'Jennifer Lawrence', 'Emma Stone', 'Scarlett Johansson'),
('film_172', 'en', 'What was Pixar''s first short film?', 'Luxo Jr.', 'Tin Toy', 'Geri''s Game'),
('film_173', 'en', 'Who played Hannibal Lecter in "The Silence of the Lambs"?', 'Anthony Hopkins', 'Kevin Spacey', 'Gary Oldman'),
('film_174', 'en', 'Which city is "Breaking Bad" set in?', 'Los Angeles', 'Albuquerque', 'Denver'),
('film_175', 'en', 'Who directed "The Godfather" trilogy?', 'Francis Ford Coppola', 'Martin Scorsese', 'Brian De Palma'),
('film_176', 'en', 'Which film did DiCaprio and Kate Winslet first appear together?', 'Revolutionary Road', 'Titanic', 'The Intouchables'),
('film_177', 'en', 'How many volumes are in "The Lord of the Rings" book series?', 'Two', 'Three', 'Four'),
('film_178', 'en', 'Who directed "Avatar" (2009)?', 'Steven Spielberg', 'James Cameron', 'Peter Jackson'),
('film_179', 'en', 'Which actor played Sherlock Holmes in the BBC series?', 'Benedict Cumberbatch', 'Robert Downey Jr.', 'Martin Freeman'),
('film_180', 'en', 'What is the name of Chandler Bing''s wife in Friends?', 'Phoebe', 'Monica', 'Rachel'),
('film_181', 'en', 'Who directed "2001: A Space Odyssey"?', 'Stanley Kubrick', 'Ridley Scott', 'George Lucas'),
('film_182', 'en', 'Which actor played Thor in Marvel films?', 'Chris Evans', 'Chris Hemsworth', 'Chris Pratt'),
('film_183', 'en', 'Who is the main star of the American version of "The Office"?', 'Steve Carell', 'Rainn Wilson', 'John Krasinski'),
('film_184', 'en', 'How many Rocky films were made?', '5', '6', '7'),
('film_185', 'en', 'Who directed "The Shining"?', 'Stanley Kubrick', 'Roman Polanski', 'Alfred Hitchcock'),
('film_186', 'en', 'Which actress played Wonder Woman?', 'Gal Gadot', 'Scarlett Johansson', 'Brie Larson'),
('film_187', 'en', 'What is the original language of "Stranger Things"?', 'English', 'Spanish', 'Korean'),
('film_188', 'en', 'Who directed the "Twilight" film series?', 'Catherine Hardwicke', 'Sofia Coppola', 'Kathryn Bigelow'),
('film_189', 'en', 'Which actor played the father in South Korea''s "Parasite"?', 'Song Kang-ho', 'Lee Byung-hun', 'Choi Min-sik'),
('film_190', 'en', 'How many seasons does "Breaking Bad" have?', '4', '5', '6'),
('film_191', 'en', 'Who directed "One Flew Over the Cuckoo''s Nest"?', 'Milos Forman', 'Sidney Lumet', 'William Friedkin'),
('film_192', 'en', 'Which actor is known for the "Ocean''s" films?', 'George Clooney', 'Tom Hanks', 'Denzel Washington'),
('film_193', 'en', 'What was Netflix''s first original series?', 'Orange Is the New Black', 'House of Cards', 'Stranger Things'),
('film_194', 'en', 'Who played Forrest Gump?', 'Tom Hanks', 'Robin Williams', 'Kevin Costner'),
('film_195', 'en', 'Which actress played Black Widow?', 'Scarlett Johansson', 'Gal Gadot', 'Brie Larson'),
('film_196', 'en', 'Who directed "The Prestige"?', 'David Fincher', 'Christopher Nolan', 'Denis Villeneuve'),
('film_197', 'en', 'How many seasons of "Friends" are there?', '8', '10', '12'),
('film_198', 'en', 'Who directed "The Dark Knight" trilogy?', 'Christopher Nolan', 'Zack Snyder', 'Tim Burton'),
('film_199', 'en', 'Which actor played Tarzan in the 2016 film?', 'Alexander Skarsgård', 'Kellan Lutz', 'Dwayne Johnson'),
('film_200', 'en', 'What is "The Crown" TV series about?', 'British Royal Family', 'Medieval rulers', 'American presidents');